// RESPONSIBILITY: Executes Trainer workout/exercise mutations with ownership, persistence, and audit rules.
// FLOW: Workout command controller → command service → trainer-scoped repository → audit.

import { Injectable } from '@nestjs/common'; import { CoreRequestContext } from '@/backend_trainer/core/context/core-request-context'; import { CoreAuditService } from '@/backend_trainer/core/audit/core-audit.service'; import { WorkoutRepository } from '@/backend_trainer/modules/backend_trainer/workout/repositories/workout-repository'; import { WorkoutExercisesRepository } from '@/backend_trainer/modules/backend_trainer/workout/repositories/workout-exercises.repository'; import { WorkoutCreateWorkoutDto } from '@/backend_trainer/modules/backend_trainer/workout/dtos/workout-create-workout.dto'; import { WorkoutUpdateWorkoutDto } from '@/backend_trainer/modules/backend_trainer/workout/dtos/workout-update-workout.dto'; import { WorkoutCreateExerciseDto } from '@/backend_trainer/modules/backend_trainer/workout/dtos/workout-create-exercise.dto'; import { WorkoutUpdateExerciseDto } from '@/backend_trainer/modules/backend_trainer/workout/dtos/workout-update-exercise.dto';
import { WorkoutMapper } from '@/backend_trainer/modules/backend_trainer/workout/workout.mapper';
import { WorkoutExerciseMapper } from '@/backend_trainer/modules/backend_trainer/workout/workout-exercise.mapper';
@Injectable() export class WorkoutCommandService {
 constructor(private readonly workouts:WorkoutRepository,private readonly exercises:WorkoutExercisesRepository,private readonly audit:CoreAuditService){}
 /** Creates a trainer-owned workout plan. */ async createWorkout(dto:WorkoutCreateWorkoutDto):Promise<ReturnType<typeof WorkoutMapper>>{const trainerId=CoreRequestContext.get().userId??'';const row=await this.workouts.createWorkoutPlan({trainerId,name:dto.name,level:dto.level,days:dto.days,exercisesCount:dto.exercises,focus:dto.focus,duration:dto.duration,tags:dto.tags ? dto.tags.split(',').map((value)=>value.trim()).filter(Boolean) : [],goal:dto.goal??null,startDate:dto.startDate??null,endDate:dto.endDate??null,instructions:dto.instructions??null,assignedMemberId:dto.assignedMemberId??null,isActive:true,workoutExercises:dto.workoutExercises??[]});await this.audit.record('WORKOUT_CREATED','WORKOUT',row.id,null,{name:row.name});return WorkoutMapper(row);}
 /** Updates a trainer-owned workout plan. */ async updateWorkout(id:string,dto:WorkoutUpdateWorkoutDto):Promise<ReturnType<typeof WorkoutMapper>>{const trainerId=CoreRequestContext.get().userId??'';const before=await this.workouts.findByIdOrThrow(trainerId,id);const row=await this.workouts.updateWorkoutPlanById(trainerId,id,{name:dto.name,level:dto.level,days:dto.days,exercisesCount:dto.exercises,focus:dto.focus,duration:dto.duration,tags:dto.tags === undefined ? undefined : dto.tags.split(',').map((value)=>value.trim()).filter(Boolean),goal:dto.goal,startDate:dto.startDate,endDate:dto.endDate,instructions:dto.instructions,assignedMemberId:dto.assignedMemberId});await this.audit.record('WORKOUT_UPDATED','WORKOUT',id,{name:before.name},{name:row.name});return WorkoutMapper(row);}
 /** Soft-deletes a trainer-owned workout plan. */ async deleteWorkout(id:string):Promise<null>{const trainerId=CoreRequestContext.get().userId??'';await this.workouts.findByIdOrThrow(trainerId,id);await this.workouts.softDeleteWorkoutById(trainerId,id);await this.audit.record('WORKOUT_DELETED','WORKOUT',id,null,{deleted:true});return null;}
 /** Creates a trainer-owned reusable exercise. */ async createExercise(dto:WorkoutCreateExerciseDto):Promise<ReturnType<typeof WorkoutExerciseMapper>>{const trainerId=CoreRequestContext.get().userId??'';const row=await this.exercises.createExercise({trainerId,name:dto.name,category:dto.category??null,muscleGroup:dto.muscle ? [dto.muscle] : null,equipment:dto.equipment??null,difficulty:dto.difficulty,instructions:dto.instructions??null,videoUrl:dto.videoUrl??null,imageUrl:dto.imageUrl??null,reps:dto.reps??null,duration:dto.duration??null,description:dto.description??null,isActive:true});await this.audit.record('EXERCISE_CREATED','EXERCISE',row.id,null,{name:row.name});return WorkoutExerciseMapper(row);}
 /** Updates one trainer-owned exercise. */ async updateExercise(id:string,dto:WorkoutUpdateExerciseDto):Promise<ReturnType<typeof WorkoutExerciseMapper>>{const trainerId=CoreRequestContext.get().userId??'';const before=await this.exercises.findByIdOrThrow(trainerId,id);const row=await this.exercises.updateExerciseById(trainerId,id,{name:dto.name,category:dto.category,muscleGroup:dto.muscle ? [dto.muscle] : undefined,equipment:dto.equipment,difficulty:dto.difficulty,instructions:dto.instructions,videoUrl:dto.videoUrl,imageUrl:dto.imageUrl,reps:dto.reps,duration:dto.duration,description:dto.description});await this.audit.record('EXERCISE_UPDATED','EXERCISE',id,{name:before.name},{name:row.name});return WorkoutExerciseMapper(row);}
 /** Soft-deletes one trainer-owned exercise. */ async deleteExercise(id:string):Promise<null>{const trainerId=CoreRequestContext.get().userId??'';await this.exercises.findByIdOrThrow(trainerId,id);await this.exercises.softDeleteExerciseById(trainerId,id);await this.audit.record('EXERCISE_DELETED','EXERCISE',id,null,{deleted:true});return null;}
}
