import { z } from 'zod';
// Generated by ts-to-zod


export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const couponTypeSchema = z.union([z.literal("percentage"), z.literal("flat")]);

export const couponStatusSchema = z.union([z.literal("active"), z.literal("inactive"), z.literal("expired")]);

export const couponSchema = z.object({
    id: z.string(),
    code: z.string(),
    description: z.string(),
    type: couponTypeSchema,
    value: z.number(),
    minOrderAmount: z.number(),
    maxDiscount: z.number(),
    usageLimit: z.number(),
    usedCount: z.number(),
    assignedGyms: z.array(z.string()),
    assignedGymNames: z.array(z.string()),
    validFrom: z.string(),
    validUntil: z.string(),
    status: couponStatusSchema,
    createdAt: z.string()
});

export const couponFormValuesSchema = z.object({
    code: z.string(),
    description: z.string(),
    type: couponTypeSchema,
    value: z.string(),
    minOrderAmount: z.string(),
    maxDiscount: z.string(),
    usageLimit: z.string(),
    assignedGyms: z.array(z.string()),
    validFrom: z.string(),
    validUntil: z.string()
});

export const couponsKpiDataSchema = z.object({
    totalCoupons: z.number(),
    activeCoupons: z.number(),
    totalRedeemed: z.number(),
    revenueLost: z.number()
});

export const couponFormSchema = z.object({
  code: z.string().min(3, '__i18n:coupons.validation.codeMin').max(20, '__i18n:coupons.validation.codeMax').toUpperCase(),
  description: z.string().min(5, '__i18n:coupons.validation.descriptionRequired'),
  type: z.enum(['percentage', 'flat']),
  value: z.string().refine(v => !isNaN(Number(v)) && Number(v) > 0, '__i18n:coupons.validation.positiveNumber'),
  minOrderAmount: z.string().refine(v => !isNaN(Number(v)) && Number(v) >= 0, '__i18n:coupons.validation.nonNegativeNumber'),
  maxDiscount: z.string().refine(v => !isNaN(Number(v)) && Number(v) >= 0, '__i18n:coupons.validation.nonNegativeNumber'),
  usageLimit: z.string().refine(v => !isNaN(Number(v)) && Number(v) > 0, '__i18n:coupons.validation.usageMin'),
  assignedGyms: z.array(z.string()).min(1, '__i18n:coupons.validation.gymsRequired'),
  validFrom: z.string().min(1, '__i18n:coupons.validation.startRequired'),
  validUntil: z.string().min(1, '__i18n:coupons.validation.endRequired'),
});

