"use client";
// RESPONSIBILITY: Renders the dashboard branch leaderboard with accessible, functional column sorting.

import { useMemo, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import type { LeaderboardSortDirection, LeaderboardSortKey } from '@/app/admin/dashboard/dashboard_types/AdminDashboardBranchLeaderboardTypes';
import { formatCurrency } from '@/lib/formatters';
import { useAdminDashboardLogic } from '@/app/admin/dashboard/dashboard_context/useAdminDashboardLogic';
import { TrendingUp, TrendingDown, Minus, Building2 } from 'lucide-react';
import AdminDashboardBranchLeaderboardSortIcon from '@/app/admin/dashboard/dashboard_components/AdminDashboardBranchLeaderboard/AdminDashboardBranchLeaderboardSortIcon';
import type { BranchPerformance } from '@/app/admin/dashboard/dashboard_types/AdminDashboardTypes';
import { sortAdminBranchPerformanceRows } from '@/app/admin/dashboard/dashboard_utils/AdminDashboardSortBranchPerformanceRows';
import { AdminDashboardEmptyState } from '@/app/admin/dashboard/dashboard_components/AdminDashboardEmptyState/AdminDashboardEmptyState';


export default function AdminDashboardBranchLeaderboard(){
  const {stats}=useAdminDashboardLogic(); const router=useRouter(); const pathname=usePathname(); const searchParams=useSearchParams(); const selectedBranchId=searchParams.get('branchId') || 'all';
  const [sortKey,setSortKey]=useState<LeaderboardSortKey>('revenue'); const [sortDir,setSortDir]=useState<LeaderboardSortDirection>('desc');
  const rows=useMemo(()=>sortAdminBranchPerformanceRows(stats?.branchLeaderboard??[],sortKey,sortDir),[stats?.branchLeaderboard,sortKey,sortDir]);
  const handleBranchSelect=(branchId:string)=>{const params=new URLSearchParams(searchParams.toString());if(branchId==='all')params.delete('branchId');else params.set('branchId',branchId);params.delete('page');router.replace(`${pathname}${params.toString()?`?${params.toString()}`:''}`,{scroll:false});}; const handleSort=(key:LeaderboardSortKey)=>{if(sortKey===key)setSortDir((d)=>d==='asc'?'desc':'asc');else{setSortKey(key);setSortDir('desc');}};
  if (!stats) return null;
  if (stats.branchLeaderboard.length === 0) return <AdminDashboardEmptyState title="No branch leaderboard data" description="No branch performance records are available for the current dashboard scope." />;
  return <div className="bg-card backdrop-blur-xl border border-border rounded-2xl shadow-card p-6"><div className="flex items-center gap-3 mb-6"><div className="p-2.5 bg-primary-subtle text-on-primary rounded-xl"><Building2 size={20}/></div><div><h2 className="text-lg font-bold text-primary">Branch Leaderboard</h2><p className="text-xs text-secondary">Top performing locations by revenue</p></div></div><div className="overflow-x-auto"><table data-admin-responsive-table className="w-full text-left border-collapse"><thead><tr className="border-b border-border text-xs font-semibold text-secondary uppercase tracking-wider"><th className="pb-3 pl-2">Rank</th>{(['name','revenue','activeMembers'] as const).map((key)=><th role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); event.currentTarget.click(); } }}  key={key} onClick={()=>handleSort(key)} className="pb-3 cursor-pointer select-none"><div className={`${key==='name'?'text-left':'text-right'} flex items-center gap-1.5 ${key!=='name'?'justify-end':''}`}>{key==='name'?'Branch Name':key==='revenue'?'Revenue':'Active Members'}<AdminDashboardBranchLeaderboardSortIcon column={key} sortKey={sortKey} sortDir={sortDir}/></div></th>)}<th className="pb-3 text-center">Trend</th></tr></thead><tbody className="divide-y divide-border/20">{rows.map((branch,index)=>{const selected=selectedBranchId===branch.id;return <tr key={branch.id} className={`motion-safe:transition-colors group cursor-pointer ${selected?'bg-primary-subtle border-l-2 border-primary':'hover:bg-surface-hover'}`} tabIndex={0} onClick={()=>handleBranchSelect(branch.id)} onKeyDown={(e)=>{if(e.key==='Enter'||e.key===' ')handleBranchSelect(branch.id);}}><td className="py-3 pl-2 text-xs font-bold text-secondary">{index+1}.</td><td className="py-3"><span className="text-sm font-semibold text-on-primary">{branch.name}</span></td><td className="py-3 text-right"><span className="text-sm font-bold text-success">{formatCurrency(branch.revenue)}</span></td><td className="py-3 text-right"><span className="text-sm font-medium text-on-primary">{branch.activeMembers}</span></td><td className="py-3 text-center"><div className="flex justify-center">{branch.trend==='up'&&<TrendingUp size={16} className="text-success"/>}{branch.trend==='down'&&<TrendingDown size={16} className="text-danger"/>}{branch.trend==='flat'&&<Minus size={16} className="text-secondary"/>}</div></td></tr>;})}</tbody></table></div></div>
}
