// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const attendanceStatusSchema = z.union([z.literal("present"), z.literal("absent"), z.literal("late")]);

export const dateRangeFilterSchema = z.union([z.literal("today"), z.literal("yesterday"), z.literal("this_week"), z.literal("this_month"), z.literal("last_month")]);

export const adminAttendanceRecordSchema = z.object({
    id: z.string(),
    memberId: z.string(),
    memberName: z.string(),
    memberPhone: z.string(),
    branchId: z.string(),
    branchName: z.string(),
    checkInTime: z.string(),
    checkOutTime: z.string().nullable(),
    date: z.string(),
    status: attendanceStatusSchema,
    planName: z.string(),
    trainerId: z.string().optional(),
    trainerName: z.string().optional(),
    sessionType: z.union([z.literal("General"), z.literal("PT"), z.literal("Class")]).optional()
});

export const adminAttendanceSummarySchema = z.object({
    todayTotal: z.number(),
    todayPresent: z.number(),
    todayLate: z.number(),
    weeklyAverage: z.number(),
    peakHour: z.string(),
    trendVsLastWeek: z.number(),
    uniqueMembersThisMonth: z.number()
});

export const adminAttendanceTrendPointSchema = z.object({
    date: z.string(),
    count: z.number()
});
