// RESPONSIBILITY: Renders server-backed affiliate payout history passed from the feature page query.
'use client';
import { Loader2 } from 'lucide-react';
import { formatCurrency, formatDate } from '@/lib/formatters';
import type { AffiliatePayoutRecord } from '@/app/superadmin/affiliates/affiliates_types/SuperadminAffiliatesTypes';
import type { SuperadminAffiliatesPayoutHistoryProps } from '@/app/superadmin/affiliates/affiliates_components/SuperadminAffiliatesPayoutHistory/SuperadminAffiliatesPayoutHistoryTypes';

export default function SuperadminAffiliatesPayoutHistory({ payouts, isPending, isError, onRetry }: SuperadminAffiliatesPayoutHistoryProps) {
  if (isPending) return <div className="flex min-h-48 items-center justify-center gap-2 text-secondary" aria-busy="true"><Loader2 size={18} className="motion-safe:animate-spin" /> Loading payout history…</div>;
  if (isError) return <div role="alert" className="rounded-lg border border-danger/30 bg-danger-bg p-5 text-sm text-danger">Unable to load payout history. <button type="button" onClick={onRetry} className="ml-1 underline underline-offset-2">Retry</button></div>;
  if (payouts.length === 0) return <div className="rounded-lg border border-border bg-card p-8 text-center text-secondary">No payout history available.</div>;
  return <div className="overflow-x-auto rounded-xl border border-border bg-card shadow-card"><table className="w-full min-w-max border-collapse text-left"><thead><tr className="border-b border-border bg-primary-subtle text-secondary"><th className="p-4 text-xs font-semibold uppercase tracking-wider">Date</th><th className="p-4 text-xs font-semibold uppercase tracking-wider">Affiliate</th><th className="p-4 text-xs font-semibold uppercase tracking-wider">Amount</th><th className="p-4 text-xs font-semibold uppercase tracking-wider">Method</th><th className="p-4 text-xs font-semibold uppercase tracking-wider">Ref ID</th><th className="p-4 text-xs font-semibold uppercase tracking-wider">Status</th></tr></thead><tbody className="divide-y divide-border">{payouts.map((payout: AffiliatePayoutRecord) => <tr key={payout.id} className="motion-safe:transition-colors hover:bg-input"><td className="p-4 text-sm text-secondary">{formatDate(payout.paidAt)}</td><td className="p-4"><span className="font-medium text-primary">{payout.affiliateName}</span><span className="block text-xs text-disabled">{payout.affiliateId}</span></td><td className="p-4 font-medium text-primary">{formatCurrency(payout.amount)}</td><td className="p-4 text-sm text-secondary">{payout.method === 'BANK_TRANSFER' ? 'Bank Transfer' : 'PayPal'}</td><td className="p-4 text-xs font-mono text-secondary">{payout.referenceId}</td><td className="p-4">{payout.status === 'COMPLETED' ? <span className="rounded-full border border-success/20 bg-success-bg px-2.5 py-1 text-xs font-semibold text-success">Completed</span> : <span className="rounded-full border border-warning/20 bg-warning-bg px-2.5 py-1 text-xs font-semibold text-warning">Pending</span>}</td></tr>)}</tbody></table></div>;
}
