// RESPONSIBILITY: Provides working local filters, saved-view application, and bulk-action selection for Superadmin tenant operations.
'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Filter, UsersRound } from 'lucide-react';
import toast from 'react-hot-toast';
import SuperadminV1Panel from '@/app/superadmin/superadmin_components/SuperadminShared/SuperadminV1Panel';
import type { SuperadminGymsV1SectionProps } from '@/app/superadmin/gyms/gyms_types/SuperadminGymsV1Types';
import { GymsUrlConfig } from '@/app/superadmin/gyms/superadmin_gyms_url_config';
export default function SuperadminGymsV1FiltersSavedViewsAndBulkActionsSection({ data }: SuperadminGymsV1SectionProps) {
    const router=useRouter(); const [selectedFilter,setSelectedFilter]=useState(''); const [pending,setPending]=useState('');
    const applyFilter=()=>{if(!selectedFilter)return;router.push(`${GymsUrlConfig.PAGES.MAIN}?segmentId=${encodeURIComponent(selectedFilter)}`)};
    const clear=()=>{setSelectedFilter('');router.push(GymsUrlConfig.PAGES.MAIN);};
    return <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><SuperadminV1Panel title="Advanced tenant filters" description="Select a saved signal, then apply it to the tenant list."><div className="grid grid-cols-2 gap-2">{data.filters.map(filter=><button key={filter} type="button" aria-pressed={selectedFilter===filter} onClick={()=>setSelectedFilter(filter)} className={`rounded-md border px-3 py-2 text-left text-xs focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary motion-safe:transition-all motion-safe:duration-base ${selectedFilter===filter?'border-primary bg-primary-subtle text-primary':'border-border bg-input text-foreground'}`}>{filter}</button>)}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><button type="button" disabled={!selectedFilter} onClick={applyFilter} className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">Apply filters</button><button type="button" onClick={clear} className="rounded-md border border-border px-3 py-2 text-sm text-foreground">Clear</button></div>{selectedFilter?<p className="mt-3 text-xs text-secondary" role="status">Selected filter: {selectedFilter}</p>:null}</SuperadminV1Panel><SuperadminV1Panel title="Saved views" description="One-click answers for common tenant questions."><div className="space-y-2">{data.saved.map(name=><button key={name} type="button" onClick={()=>{setSelectedFilter(name);toast.success(`Saved view ${name} selected.`,{id:`superadmin-gyms-v1-view-${name}`})}} className={`flex w-full items-center justify-between rounded-md border px-3 py-2 text-left text-sm ${selectedFilter===name?'border-primary bg-primary-subtle text-primary':'border-border text-foreground'}`}><span className="truncate">{name}</span><Filter size={18} className="text-primary"/></button>)}</div></SuperadminV1Panel><SuperadminV1Panel title="Bulk actions" description="Select a tenant-action intent before continuing to the main tenant table."><div className="space-y-2">{data.bulk.map(name=><button key={name} type="button" aria-pressed={pending===name} onClick={()=>{setPending(name);toast.success(`${name} is ready for selected tenants.`,{id:`superadmin-gyms-v1-bulk-${name}`})}} className={`flex w-full items-center gap-2 rounded-md border px-3 py-2 text-left text-sm ${pending===name?'border-primary bg-primary-subtle text-primary':'border-border text-foreground'}`}><UsersRound size={18} className="text-secondary"/>{name}</button>)}</div>{pending?<p className="mt-3 text-xs text-secondary" role="status">Bulk action ready: {pending}</p>:null}</SuperadminV1Panel></div>;
}
