// Generated by ts-to-zod
import { z } from "zod";

export const notificationSeveritySchema = z.union([z.literal("INFO"), z.literal("WARNING"), z.literal("CRITICAL")]);

export const adminNotificationSchema = z.object({
    id: z.string(),
    title: z.string(),
    body: z.string(),
    severity: notificationSeveritySchema,
    read: z.boolean(),
    createdAt: z.string(),
    branchId: z.string().optional(),
    branchName: z.string().optional()
});

export const notificationItemSchema = z.object({
    id: z.string(),
    text: z.string(),
    time: z.string(),
    unread: z.boolean()
});

export const notificationsFetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);
