import { IsNull } from 'typeorm';
// RESPONSIBILITY: Owns Trainer exercise search, create, update, and soft-delete persistence.
// FLOW: Workout service → WorkoutExercisesRepository → tenant TypeORM.

import { Injectable } from '@nestjs/common'; import { CoreBaseRepository } from '@/backend_trainer/core/database/core-base.repository'; import { CoreNotFoundException } from '@/backend_trainer/core/errors/core-not-found.exception'; import { CoreTenantDataSourceResolver } from '@/backend_trainer/core/database/core-tenant-datasource.resolver'; import { WorkoutExerciseEntity } from '@/backend_trainer/modules/backend_trainer/workout/workout-exercise.entity';
export interface WorkoutExerciseListQuery { page:number;limit:number;search?:string;sortBy:string;sortDirection:string; }
@Injectable() export class WorkoutExercisesRepository extends CoreBaseRepository {
 constructor(private readonly resolver:CoreTenantDataSourceResolver){super();}
 /** Lists active trainer-owned exercises with allowlisted sort fields. */ async findMany(trainerId:string,q:WorkoutExerciseListQuery):Promise<{rows:WorkoutExerciseEntity[];total:number}>{const repo=await this.resolver.getRepository(WorkoutExerciseEntity);const allowed={name:'e.name',difficulty:'e.difficulty',category:'e.category'} as const;const qb=repo.createQueryBuilder('e').where('e.deleted_at IS NULL AND e.is_active=true AND e.trainer_id=:trainerId',{trainerId});if(q.search)qb.andWhere('(e.name ILIKE :s OR e.category ILIKE :s)',{s:`%${q.search}%`});qb.orderBy(allowed[q.sortBy as keyof typeof allowed]??allowed.name,q.sortDirection==='asc'?'ASC':'DESC').skip((q.page-1)*q.limit).take(q.limit);const [rows,total]=await qb.getManyAndCount();return {rows,total};}
 /** Finds one trainer-owned exercise. */ async findById(trainerId:string,id:string):Promise<WorkoutExerciseEntity|null>{return (await this.resolver.getRepository(WorkoutExerciseEntity)).findOneBy({id,trainerId,deletedAt: IsNull()});}
 /** Returns one trainer-owned exercise or typed not-found. */ async findByIdOrThrow(trainerId:string,id:string):Promise<WorkoutExerciseEntity>{return this.requireEntity(await this.findById(trainerId,id), 'DOMAIN.WORKOUT.EXERCISE',id);}
 /** Creates an exercise. */ async createExercise(input:Partial<WorkoutExerciseEntity>):Promise<WorkoutExerciseEntity>{const repo=await this.resolver.getRepository(WorkoutExerciseEntity);return repo.save(repo.create(input));}
 /** Updates one trainer-owned exercise. */ async updateExerciseById(trainerId:string,id:string,input:Partial<WorkoutExerciseEntity>):Promise<WorkoutExerciseEntity>{const repo=await this.resolver.getRepository(WorkoutExerciseEntity);const result=await repo.update({id,trainerId,deletedAt: IsNull()},input);if(!result.affected)throw new CoreNotFoundException('DOMAIN.WORKOUT.EXERCISE',id);return this.findByIdOrThrow(trainerId,id);}
 /** Soft-deletes one trainer-owned exercise. */ async softDeleteExerciseById(trainerId:string,id:string):Promise<void>{const result=await (await this.resolver.getRepository(WorkoutExerciseEntity)).softDelete({id,trainerId,deletedAt: IsNull()});if(!result.affected)throw new CoreNotFoundException('DOMAIN.WORKOUT.EXERCISE',id);}
}
