// RESPONSIBILITY: Renders the Trainer Profile personal/security forms and delegates state, validation, and mutations to the profile hook.
'use client';
// DATA FLOW: useTrainerProfileLogic → RHF/TanStack Query → TrainerProfileApi.
import { useState } from 'react';
import { Controller } from 'react-hook-form';
import { Eye, EyeOff, Loader2, Lock, Save, User } from 'lucide-react';
import { useTrainerProfileLogic } from '@/app/trainer/profile/profile_hooks/useTrainerProfileLogic';
import { TRAINER_SPECIALIZATIONS } from '@/app/trainer/profile/profile_utils/TrainerProfileSharedConstants';
import { useTrainerUnsavedChangesGuard } from '@/app/trainer/trainer_utils/TrainerUseWarnIfUnsavedChanges';

export default function TrainerProfileMain() {
  const logic = useTrainerProfileLogic();
  const { profileForm, passwordForm, user, activeTab, setActiveTab, profileMutation, passwordMutation, isPending, isError, isDirty } = logic;
  const guardNavigation = useTrainerUnsavedChangesGuard(isDirty);
  const [passwordVisibility, setPasswordVisibility] = useState({ current: false, next: false, confirm: false });

  if (isPending) return <div className="max-w-3xl mx-auto p-6 space-y-6"><div className="h-24 rounded-xl bg-card border border-border motion-safe:animate-pulse" /><div className="h-72 rounded-xl bg-card border border-border motion-safe:animate-pulse" /></div>;
  if (isError || !user) return <div role="alert" className="max-w-3xl mx-auto p-6 text-sm text-danger">Unable to load your profile.</div>;

  const passwordFields = [
    { name: 'currentPassword' as const, label: 'Current Password', key: 'current' as const },
    { name: 'newPassword' as const, label: 'New Password', key: 'next' as const },
    { name: 'confirmPassword' as const, label: 'Confirm New Password', key: 'confirm' as const },
  ];

  return <div className="min-h-full pb-10"><div className="max-w-3xl mx-auto space-y-6 p-6">
    <div className="bg-card border border-border rounded-xl p-6 flex items-center gap-5"><div className="w-16 h-16 rounded-full bg-primary flex items-center justify-center text-2xl font-bold text-on-primary shrink-0">{logic.displayInitial}</div><div><p className="text-lg font-bold text-primary">{user.name}</p><p className="text-sm text-secondary">{user.email}</p></div></div>
    <div className="flex flex-wrap gap-1 bg-input border border-border rounded-xl p-1 w-fit">
      <button type="button" onClick={() => void guardNavigation(() => setActiveTab('personal'))} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium motion-safe:transition-colors ${activeTab === 'personal' ? 'bg-card text-primary shadow-card' : 'text-secondary hover:text-primary'} focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page`}><User size={18} />Personal Info</button>
      <button type="button" onClick={() => void guardNavigation(() => setActiveTab('security'))} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium motion-safe:transition-colors ${activeTab === 'security' ? 'bg-card text-primary shadow-card' : 'text-secondary hover:text-primary'} focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page`}><Lock size={18} />Security</button>
    </div>
    {activeTab === 'personal' && (<form onSubmit={profileForm.handleSubmit((values) => profileMutation.mutate(values))} className="bg-card border border-border rounded-xl p-6 space-y-5"><h2 className="text-base font-semibold text-primary">Personal Information</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
      <div><label htmlFor="trainer-profile-name" className="block text-sm font-medium text-secondary mb-1.5">Full Name</label><input id="trainer-profile-name" {...profileForm.register('name')} className="w-full px-4 py-2.5 bg-input border border-border rounded-lg text-primary text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" />{profileForm.formState.errors.name && <p className="text-xs text-danger mt-1">{profileForm.formState.errors.name.message}</p>}</div>
      <div><label htmlFor="trainer-profile-email" className="block text-sm font-medium text-secondary mb-1.5">Email Address</label><input id="trainer-profile-email" value={user.email} readOnly className="w-full px-4 py-2.5 bg-input border border-border rounded-lg text-secondary text-sm cursor-not-allowed opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div>
      <div><label htmlFor="trainer-profile-phone" className="block text-sm font-medium text-secondary mb-1.5">Phone Number</label><input id="trainer-profile-phone" {...profileForm.register('phone')} className="w-full px-4 py-2.5 bg-input border border-border rounded-lg text-primary text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" />{profileForm.formState.errors.phone && <p className="text-xs text-danger mt-1">{profileForm.formState.errors.phone.message}</p>}</div>
      <Controller control={profileForm.control} name="specialization" render={({ field }) => <div><span className="block text-sm font-medium text-secondary mb-2">Specialization</span><div className="flex flex-wrap gap-2">{TRAINER_SPECIALIZATIONS.map((item) => { const selected = field.value.includes(item); return <button key={item} type="button" aria-pressed={selected} onClick={() => field.onChange(selected ? field.value.filter((value) => value !== item) : [...field.value, item])} className={`px-3 py-1.5 rounded-full text-xs font-semibold border motion-safe:transition-all ${selected ? 'bg-primary text-on-primary border-primary' : 'bg-input text-secondary border-border'} focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page`}>{item}</button>; })}</div></div>} />
    </div><div className="flex justify-end"><button type="submit" disabled={profileMutation.isPending} className="motion-safe:transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page min-w-32 flex items-center justify-center gap-2 px-5 py-2.5 bg-primary text-on-primary font-semibold rounded-lg disabled:opacity-60">{profileMutation.isPending ? <><Loader2 size={18} className="motion-safe:animate-spin" />Saving…</> : <><Save size={18} />Save Changes</>}</button></div></form>)}
    {activeTab === 'security' && (<form onSubmit={passwordForm.handleSubmit((values) => passwordMutation.mutate(values))} className="bg-card border border-border rounded-xl p-6 space-y-5"><h2 className="text-base font-semibold text-primary">Change Password</h2>{passwordFields.map((field) => { const visible = passwordVisibility[field.key]; return <div key={field.name} className="max-w-md"><label htmlFor={`trainer-${field.name}`} className="block text-sm font-medium text-secondary mb-1.5">{field.label}</label><div className="relative"><input id={`trainer-${field.name}`} type={visible ? 'text' : 'password'} {...passwordForm.register(field.name)} className="w-full px-4 py-2.5 pr-10 bg-input border border-border rounded-lg text-primary text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /> <button type="button" aria-label={visible ? 'Hide password' : 'Show password'} onClick={() => setPasswordVisibility((current) => ({ ...current, [field.key]: !current[field.key] }))} className="absolute right-3 top-1/2 -translate-y-1/2 text-secondary hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page">{visible ? <EyeOff size={18} /> : <Eye size={18} />}</button></div>{passwordForm.formState.errors[field.name] && <p className="text-xs text-danger mt-1">{passwordForm.formState.errors[field.name]?.message}</p>}</div>; })}<div className="flex justify-end"><button type="submit" disabled={passwordMutation.isPending} className="motion-safe:transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page min-w-36 flex items-center justify-center gap-2 px-5 py-2.5 bg-primary text-on-primary font-semibold rounded-lg disabled:opacity-60">{passwordMutation.isPending ? <><Loader2 size={18} className="motion-safe:animate-spin" />Updating…</> : <><Lock size={18} />Update Password</>}</button></div></form>)}
  </div></div>;
}
