// RESPONSIBILITY: Defines stable machine-readable errors for PublicLanding transport and contract failures.
export const LANDING_API_ERROR_CODES = {
  INVALID_RESPONSE: 'LANDING_INVALID_RESPONSE',
  BOOKING_REQUEST_FAILED: 'LANDING_BOOKING_REQUEST_FAILED',
  CONTACT_REQUEST_FAILED: 'LANDING_CONTACT_REQUEST_FAILED',
  NETWORK_FAILURE: 'LANDING_NETWORK_FAILURE',
} as const;
