import { z } from 'zod';
// Generated by ts-to-zod


export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const couponTypeSchema = z.union([z.literal("percentage"), z.literal("flat")]);

export const couponStatusSchema = z.union([z.literal("active"), z.literal("inactive"), z.literal("expired")]);

export const couponSchema = z.object({
    id: z.string(),
    code: z.string(),
    description: z.string(),
    type: couponTypeSchema,
    value: z.number(),
    minOrderAmount: z.number(),
    maxDiscount: z.number(),
    usageLimit: z.number(),
    usedCount: z.number(),
    assignedGyms: z.array(z.string()),
    assignedGymNames: z.array(z.string()),
    validFrom: z.string(),
    validUntil: z.string(),
    status: couponStatusSchema,
    createdAt: z.string()
});

export const couponFormValuesSchema = z.object({
    code: z.string(),
    description: z.string(),
    type: couponTypeSchema,
    value: z.string(),
    minOrderAmount: z.string(),
    maxDiscount: z.string(),
    usageLimit: z.string(),
    assignedGyms: z.array(z.string()),
    validFrom: z.string(),
    validUntil: z.string()
});

export const couponsKpiDataSchema = z.object({
    totalCoupons: z.number(),
    activeCoupons: z.number(),
    totalRedeemed: z.number(),
    revenueLost: z.number()
});

export const couponFormSchema = z.object({
  code: z.string().min(3, 'Code must be at least 3 characters').max(20, 'Code too long').toUpperCase(),
  description: z.string().min(5, 'Description required'),
  type: z.enum(['percentage', 'flat']),
  value: z.string().refine(v => !isNaN(Number(v)) && Number(v) > 0, 'Must be a positive number'),
  minOrderAmount: z.string().refine(v => !isNaN(Number(v)) && Number(v) >= 0, 'Must be 0 or more'),
  maxDiscount: z.string().refine(v => !isNaN(Number(v)) && Number(v) >= 0, 'Must be 0 or more'),
  usageLimit: z.string().refine(v => !isNaN(Number(v)) && Number(v) > 0, 'Must be at least 1'),
  assignedGyms: z.array(z.string()).min(1, 'Assign to at least one gym'),
  validFrom: z.string().min(1, 'Start date required'),
  validUntil: z.string().min(1, 'End date required'),
});

