// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const couponTypeSchema = z.union([z.literal("percentage"), z.literal("flat")]);

export const couponStatusSchema = z.union([z.literal("active"), z.literal("inactive"), z.literal("expired")]);

export const couponSchema = z.object({
    id: z.string(),
    code: z.string(),
    description: z.string(),
    type: couponTypeSchema,
    value: z.number(),
    minOrderAmount: z.number(),
    maxDiscount: z.number(),
    usageLimit: z.number(),
    usedCount: z.number(),
    assignedGyms: z.array(z.string()),
    assignedGymNames: z.array(z.string()),
    validFrom: z.string(),
    validUntil: z.string(),
    status: couponStatusSchema,
    createdAt: z.string()
});

export const couponFormValuesSchema = z.object({
    code: z.string(),
    description: z.string(),
    type: couponTypeSchema,
    value: z.string(),
    minOrderAmount: z.string(),
    maxDiscount: z.string(),
    usageLimit: z.string(),
    assignedGyms: z.array(z.string()),
    validFrom: z.string(),
    validUntil: z.string()
});

export const couponsKpiDataSchema = z.object({
    totalCoupons: z.number(),
    activeCoupons: z.number(),
    totalRedeemed: z.number(),
    revenueLost: z.number()
});
