// RESPONSIBILITY: Renders the lead-conversion modal; lifecycle and calculations live in the dedicated form hook.
'use client';
import { X, Save } from 'lucide-react';
import ManagerConvertLeadForm from '@/app/manager/inquiries/inquiries_components/ConvertLeadModal/ManagerConvertLeadForm';
import ManagerConvertLeadSuccess from '@/app/manager/inquiries/inquiries_components/ConvertLeadModal/ManagerConvertLeadSuccess';
import { useManagerConvertLeadForm } from '@/app/manager/inquiries/inquiries_hooks/ManagerUseManagerConvertLeadForm';

export default function ManagerConvertLeadModal() {
  const { activeLead, plans, plansLoading, form, planId, billingCycle, customDays, saving, successData, submit, handleClose, closeConvert } = useManagerConvertLeadForm();
  if (!activeLead) return null;
  return <div className="fixed inset-0 z-40 flex items-center justify-center p-4 bg-overlay-backdrop"><div className="bg-overlay rounded-2xl shadow-dialog w-full max-w-xl overflow-visible border border-border max-h-full flex flex-col"><div className="sticky top-0 bg-overlay px-6 py-4 border-b border-border flex items-center justify-between z-10 rounded-t-2xl"><div><h3 className="text-lg font-bold text-primary">Convert to Member</h3><p className="text-xs text-secondary mt-0.5">Complete admission for {activeLead.name}</p></div><button type="button" onClick={handleClose} aria-label="Close conversion form" className="p-2 rounded-full hover:bg-primary-subtle text-secondary motion-safe:transition-colors"><X size={18} /></button></div>{successData ? <ManagerConvertLeadSuccess successData={successData} closeConvert={closeConvert} /> : <form onSubmit={submit} className="overflow-y-auto flex-1 custom-scrollbar p-4 flex flex-col gap-4">{plansLoading ? <div className="h-64 rounded-xl bg-skeleton-base motion-safe:animate-pulse" aria-label="Loading membership plans" /> : <ManagerConvertLeadForm useFormReturn={form} plans={plans} watchPlanId={planId} watchBillingCycle={billingCycle} watchCustomDays={customDays} /> }<div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-border mt-2"><button type="button" onClick={handleClose} className="flex-1 py-2.5 border border-border rounded-xl text-sm font-medium text-primary motion-safe:transition-colors">Cancel</button><button type="submit" disabled={saving || plansLoading} className="min-w-40 flex-1 py-2.5 rounded-xl text-sm font-bold bg-primary text-on-primary flex items-center justify-center gap-2 disabled:opacity-70 motion-safe:transition-colors">{saving ? 'Saving...' : <><Save size={18} /> Convert Inquiry</>}</button></div></form>}</div></div>;
}
