// RESPONSIBILITY: Owns Trainer notification, read-state, and preference persistence/query operations.
// FLOW: Notifications service → repository → tenant TypeORM.

import { IsNull } from 'typeorm';
// RESPONSIBILITY: Owns notification list/read/preference queries and updates for the Trainer module.
// FLOW: Notification services → TrainerNotificationsRepository → tenant TypeORM repository.

import { CoreTransactionContext } from '@/backend_trainer/backend_core/core_database/core-transaction.context';
import { CoreBaseRepository } from '@/backend_trainer/backend_core/core_database/core-base.repository';
import { Injectable } from '@nestjs/common'; import { CoreTenantDatasourceResolver } from '@/backend_trainer/backend_core/core_database/core-tenant-datasource.resolver'; import { TrainerNotificationsNotificationEntity } from '@/backend_trainer/backend_trainer_modules/trainer_notifications/trainer-notifications-notification.entity';
import type { NotificationsNotificationDomain } from '@/backend_trainer/backend_trainer_modules/trainer_notifications/trainer-notifications-notification.domain';
import { NotificationsNotificationMapper } from '@/backend_trainer/backend_trainer_modules/trainer_notifications/trainer-notifications-notification.mapper';
import type { NotificationType } from '@/backend_trainer/backend_trainer_modules/trainer_notifications/trainer-notifications-enums'; import { TrainerNotificationsNotificationPreferenceEntity } from '@/backend_trainer/backend_trainer_modules/trainer_notifications/trainer-notifications-notification-preference.entity';

/**
 * Intent: Defines the TrainerNotificationsRepository boundary for the modules architecture.
 * Edge Cases: Preserve tenant scope, validation, authorization, nullability, transactions, and canonical errors when changing this construct.
 * Side Effects: Preserve the owning construct’s existing persistence, cache, event, and audit behavior without introducing cross-module state changes.
 * AI Note: Keep this construct isolated from unrelated modules and preserve frozen contracts; never bypass repository/domain boundaries.
 */
@Injectable() export class TrainerNotificationsRepository extends CoreBaseRepository { constructor(private readonly resolver:CoreTenantDatasourceResolver){super();}
  /** Intent: Persists one trainer notification in the tenant transaction. Edge Cases: Related entity IDs must already be authorized by the producer. Side-Effects: Creates the offline recovery record used by REST history and realtime delivery. AI Note: This method never emits sockets; the delivery service emits only after transaction commit. */
  async createNotification(input:{trainerId:string;title:string;message:string;type?:NotificationType|null;actionUrl?:string|null;relatedEntityId?:string|null;relatedEntityType?:string|null;metadata?:Record<string,unknown>|null},context?:CoreTransactionContext):Promise<ReturnType<typeof NotificationsNotificationMapper>>{const repo=context?.getRepository(TrainerNotificationsNotificationEntity) ?? await this.resolver.getRepository(TrainerNotificationsNotificationEntity);const entity=await repo.save(repo.create({trainerId:input.trainerId,title:input.title,message:input.message,type:input.type ?? null,actionUrl:input.actionUrl ?? null,relatedEntityId:input.relatedEntityId ?? null,relatedEntityType:input.relatedEntityType ?? null,metadata:input.metadata ?? null,isRead:false}));return NotificationsNotificationMapper(entity);}
  /** Lists notifications with unread filtering and pagination. */ async findMany(trainerId:string,query:{page:number;limit:number;unreadOnly?:boolean;search?:string;sortBy:'createdAt'|'title';sortDirection:'asc'|'desc'|'ASC'|'DESC'}):Promise<{rows:NotificationsNotificationDomain[];total:number;unreadCount:number}>{const repo=await this.resolver.getRepository(TrainerNotificationsNotificationEntity); const qb=repo.createQueryBuilder('n').where('n.trainer_id=:trainerId AND n.deleted_at IS NULL',{trainerId}); if(query.unreadOnly) qb.andWhere('n.is_read=false'); if(query.search) qb.andWhere('(n.title ILIKE :search OR n.message ILIKE :search)',{search:`%${query.search}%`}); const total=await qb.getCount(); const unreadCount=await repo.countBy({trainerId,isRead:false}); const sortColumn=query.sortBy==='title'?'n.title':'n.created_at'; const direction=query.sortDirection.toUpperCase()==='ASC'?'ASC':'DESC'; const rows=await qb.orderBy(sortColumn,direction).skip((query.page-1)*query.limit).take(query.limit).getMany(); return {rows:rows.map(NotificationsNotificationMapper),total,unreadCount};}
  /** Returns one active notification owned by the authenticated Trainer. */ async findByIdForTrainer(trainerId:string,id:string):Promise<NotificationsNotificationDomain|null>{return (await this.resolver.getRepository(TrainerNotificationsNotificationEntity)).findOneBy({id,trainerId,deletedAt:IsNull()}).then((row)=>row?NotificationsNotificationMapper(row):null);}
  /** Marks one trainer notification as read. */ async markRead(id:string,trainerId:string,context?:CoreTransactionContext):Promise<NotificationsNotificationDomain|null>{const repo=context?.getRepository(TrainerNotificationsNotificationEntity) ?? await this.resolver.getRepository(TrainerNotificationsNotificationEntity); await repo.update({id,trainerId,deletedAt: IsNull()},{isRead:true}); return repo.findOneBy({id,trainerId,deletedAt: IsNull()}).then((row)=>row?NotificationsNotificationMapper(row):null);}
  /** Marks all trainer notifications as read. */ async markAllRead(trainerId:string,context?:CoreTransactionContext):Promise<number>{const result=await (context?.getRepository(TrainerNotificationsNotificationEntity) ?? await this.resolver.getRepository(TrainerNotificationsNotificationEntity)).update({trainerId,isRead:false,deletedAt: IsNull()},{isRead:true}); return result.affected ?? 0;}
  /** Reads trainer preferences without creating state as a side effect. */ async getPreferences(trainerId:string):Promise<TrainerNotificationsNotificationPreferenceEntity | null>{const repo=await this.resolver.getRepository(TrainerNotificationsNotificationPreferenceEntity); return repo.findOneBy({trainerId,deletedAt: IsNull()});}
  /** Creates or updates preference state using repository-owned mutation semantics. */ async updatePreferences(trainerId:string,input:Partial<TrainerNotificationsNotificationPreferenceEntity>,context?:CoreTransactionContext):Promise<TrainerNotificationsNotificationPreferenceEntity>{const repo=context?.getRepository(TrainerNotificationsNotificationPreferenceEntity) ?? await this.resolver.getRepository(TrainerNotificationsNotificationPreferenceEntity); const existing=await repo.findOneBy({trainerId,deletedAt: IsNull()}); if(existing){await repo.update({trainerId,deletedAt: IsNull()},input); return repo.findOneByOrFail({trainerId,deletedAt: IsNull()});} return repo.save(repo.create({trainerId,...input}));}
}
