import { z } from 'zod';
// Generated by ts-to-zod


export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const planSchema = z.object({
    id: z.string(),
    name: z.string(),
    tier: z.string(),
    price1Month: z.number(),
    price3Month: z.number(),
    price6Month: z.number(),
    price12Month: z.number(),
    features: z.array(z.string()),
    isActive: z.boolean(),
    freezeAllowed: z.boolean().optional(),
    joiningFee: z.number().optional(),
    ptSessionsIncluded: z.number().optional(),
    taxRate: z.number().optional()
});



export const plansInitialDataSchema = z.object({
    plans: z.array(planSchema)
});

export const planFormSchema = z.object({
  name: z.string().min(2, '__i18n:plans.validation.nameRequired'),
  tier: z.string(),
  price1Month:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, '__i18n:plans.validation.validPrice'),
  price3Month:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, '__i18n:plans.validation.validPrice'),
  price6Month:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, '__i18n:plans.validation.validPrice'),
  price12Month: z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, '__i18n:plans.validation.validPrice'),
  priceCustom:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, '__i18n:plans.validation.validPrice'),
  features: z.string().min(2, '__i18n:plans.validation.featuresRequired')
});

