// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const alertSeveritySchema = z.union([z.literal("critical"), z.literal("warning"), z.literal("info")]);

export const alertTypeSchema = z.union([z.literal("no_new_members"), z.literal("revenue_drop"), z.literal("high_churn"), z.literal("pending_payroll"), z.literal("low_attendance"), z.literal("expiring_members")]);

export const gymHealthAlertSchema = z.object({
    id: z.string(),
    gymId: z.string(),
    gymName: z.string(),
    alertType: alertTypeSchema,
    severity: alertSeveritySchema,
    title: z.string(),
    description: z.string(),
    metric: z.string(),
    threshold: z.string(),
    detectedAt: z.string(),
    isResolved: z.boolean(),
    resolvedAt: z.string().optional(),
    alertAge: z.number().optional(),
    assignedTo: z.string().optional(),
    snoozeUntil: z.string().optional()
});

export const gymHealthKpiDataSchema = z.object({
    totalAlerts: z.number(),
    criticalAlerts: z.number(),
    warningAlerts: z.number(),
    gymsAtRisk: z.number()
});
