// RESPONSIBILITY: Renders the staff advance payment editor using the HR form hook.
'use client';
import { formatCurrency } from '@/app/manager/manager_layout/manager_utils/ManagerFormatCurrency';

import { useManagerHrAdvanceForm } from '@/app/manager/hr/hr_hooks/ManagerUseManagerHrAdvanceForm';
import { MANAGER_HR_MAX_AMOUNT_MAJOR_UNITS } from '@/app/manager/hr/hr_utils/ManagerHrSharedConstants';
import ManagerSearchableDropdown from '@/app/manager/manager_components/ManagerShared/ManagerSearchableDropdown';
import { ManagerEnvConfig } from '@/app/manager/manager_infrastructure/ManagerEnvConfig';
import { useLocale } from "next-intl";

export default function ManagerHrAdvanceTable() {
    const locale = useLocale();
  const { saving, form, selectedStaffId, selectedStaff, staffOptions, submit, handleClose } = useManagerHrAdvanceForm();
  return <div className="max-w-2xl mx-auto bg-card p-6 rounded-xl border border-border"><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold text-primary">Give Advance Payment</h2><button type="button" aria-label="Clear advance payment form" onClick={handleClose} className="text-secondary motion-safe:transition-colors">Reset</button></div><form onSubmit={submit} className="space-y-5"><div><label className="block text-sm font-medium mb-1 text-primary">Staff Member *</label><ManagerSearchableDropdown options={staffOptions} value={selectedStaffId} onChange={(value) => form.setValue('staffId', String(value), { shouldDirty: true, shouldValidate: true })} placeholder="Select Staff" />{form.formState.errors.staffId && <p className="text-xs text-danger mt-1">{form.formState.errors.staffId.message}</p>}</div>{selectedStaff && <div className="p-4 bg-primary-subtle rounded-lg border border-border text-sm"><p><strong>Current Advance Balance:</strong> {formatCurrency(selectedStaff.advanceSalary || 0, ManagerEnvConfig.currencyCode, locale)}</p><p className="text-secondary text-xs mt-1">Advances are automatically deducted from the next payroll calculation.</p></div>}<div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label htmlFor="manager-hr-advance-amount" className="block text-sm font-medium mb-1 text-primary">Amount *</label><input id="manager-hr-advance-amount" type="number" min="1" max={MANAGER_HR_MAX_AMOUNT_MAJOR_UNITS} step="0.01" {...form.register('amount', { valueAsNumber: true })} className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-card text-primary" />{form.formState.errors.amount && <p className="text-xs text-danger mt-1">{form.formState.errors.amount.message}</p>}</div><div><label className="block text-sm font-medium mb-1 text-primary">Payment Mode</label><select {...form.register('paymentMode')} className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-card text-primary"><option value="Cash">Cash</option><option value="Bank Transfer">Bank Transfer</option><option value="UPI">UPI</option><option value="Cheque">Cheque</option></select></div></div><div><label htmlFor="manager-hr-advance-notes" className="block text-sm font-medium mb-1 text-primary">Notes / Reason</label><textarea id="manager-hr-advance-notes" {...form.register('notes')} className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-card text-primary min-h-20" placeholder="Add payment notes" /></div><div className="flex justify-end pt-4"><button type="submit" disabled={saving || !selectedStaffId} className="min-w-36 px-6 py-2 bg-primary text-on-primary rounded-lg font-medium disabled:opacity-50 motion-safe:transition-colors">{saving ? 'Processing...' : 'Give Advance'}</button></div></form></div>;
}
