// RESPONSIBILITY: Provides the canonical UUID persistence identity and lifecycle fields shared by every TypeORM entity.
// FLOW: Feature entity -> BaseEntity -> PostgreSQL UUID primary key + UTC lifecycle columns.
import { Column, CreateDateColumn, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

/**
 * Primary Intent: Establishes the single persistence identity contract for all backend entities.
 * Edge Cases: IDs are generated by PostgreSQL/TypeORM and must remain valid UUIDs across migrations and references.
 * Side-Effects: None; this abstraction only defines persistence metadata and lifecycle timestamps.
 * AI-Note: Do not replace UUID generation with strings, hashes, or feature-local primary-key strategies.
 */
export abstract class SuperadminCoreBaseEntity {
  /**
   * Primary Intent: Stable globally unique identifier used by APIs, relations, audit entries, and tenant-safe queries.
   * Edge Cases: Existing legacy identifiers require an explicit migration before this column is converted in production.
   * Side-Effects: None.
   * AI-Note: Preserve UUID semantics and update all dependent foreign-key columns in a backward-compatible migration.
   */
  @PrimaryGeneratedColumn('uuid', { name: 'id' })
  id!: string;

  /**
   * Primary Intent: UTC creation timestamp for ordering and audit provenance.
   * Edge Cases: Never use server-local time or mutate after creation.
   * Side-Effects: None.
   * AI-Note: Queries needing temporal analytics must normalize to the documented UTC contract.
   */
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  /**
   * Primary Intent: UTC last-modified timestamp used by caches, synchronization, and audit inspection.
   * Edge Cases: Repository mutations should allow TypeORM to update this value automatically.
   * Side-Effects: None.
   * AI-Note: Never manually set this field in business services.
   */
  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  /**
   * Primary Intent: Soft-delete lifecycle marker; null means active.
   * Edge Cases: Standard reads must exclude non-null deletedAt values; production deletes must not physically remove rows.
   * Side-Effects: Repository-level scopes depend on this invariant.
   * AI-Note: Use repository soft-delete methods instead of ORM delete/remove calls.
   */
  @Column({ name: 'deleted_at', type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;
}
