// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const memberSchema = z.object({
    id: z.string(),
    name: z.string(),
    email: z.string(),
    phone: z.string(),
    gender: z.string(),
    address: z.string().optional(),
    branch: z.string(),
    planId: z.string(),
    plan: z.object({
        id: z.string(),
        name: z.string(),
        tier: z.string()
    }).optional(),
    billingCycle: z.string(),
    status: z.string(),
    joinDate: z.string(),
    expiryDate: z.string(),
    paidAmount: z.number(),
    pendingAmount: z.number(),
    photo: z.string().optional(),
    createdAt: z.string()
});

export const pendingPaymentMemberSchema = memberSchema.omit({ "plan": true }).and(z.object({
    plan: z.string().optional(),
    pendingAmount: z.number().optional(),
    daysOverdue: z.number().optional()
}));

export const overviewDataPointSchema = z.object({
    date: z.string(),
    revenue: z.number()
});

export const membershipReportItemSchema = z.object({
    id: z.number().optional(),
    name: z.string().optional(),
    totalMembers: z.number().optional(),
    activeMembers: z.number().optional(),
    revenue: z.number().optional(),
    plan: z.string().optional(),
    receivable: z.number().optional(),
    received: z.number().optional(),
    remaining: z.number().optional(),
    refund: z.number().optional(),
    referralSource: z.string().optional(),
    couponCode: z.string().optional(),
    renewalCount: z.number().optional()
});

export const membershipTotalsSchema = z.object({
    activeCount: z.number().optional(),
    revenue: z.number().optional(),
    totalReceivable: z.number().optional(),
    totalReceived: z.number().optional(),
    remaining: z.number().optional(),
    refunds: z.number().optional()
});

export const storeProductSchema = z.object({
    id: z.string(),
    name: z.string(),
    category: z.string(),
    price: z.number(),
    stock: z.number(),
    description: z.string().optional(),
    imageUrl: z.string().optional(),
    isActive: z.boolean()
});

export const storeOrderItemSchema = z.object({
    id: z.string(),
    qty: z.number(),
    price: z.number(),
    product: z.object({
        name: z.string()
    })
});

export const storeOrderSchema = z.object({
    id: z.string(),
    total: z.number(),
    method: z.string(),
    status: z.string(),
    notes: z.string().optional(),
    createdAt: z.string(),
    items: z.array(storeOrderItemSchema).optional()
});

export const storeSummarySchema = z.object({
    totalProducts: z.number(),
    totalOrders: z.number(),
    totalRevenue: z.number(),
    lowStockProducts: z.array(storeProductSchema)
});

export const salesInitialDataSchema = z.object({
    overviewData: z.array(overviewDataPointSchema).optional(),
    membershipReport: z.array(membershipReportItemSchema).optional(),
    membershipTotals: membershipTotalsSchema.optional(),
    pendingPayments: z.array(pendingPaymentMemberSchema).optional(),
    pendingTotal: z.number().optional(),
    allMemberships: z.array(memberSchema).optional(),
    allMembershipsTotal: z.number().optional(),
    storeOrders: z.array(storeOrderSchema).optional(),
    storeOrdersTotal: z.number().optional(),
    storeSummary: storeSummarySchema.optional().nullable()
});

const salesTabSchema = z.unknown();

const dateFilterSchema = z.unknown();
