// RESPONSIBILITY: Versioned PostgreSQL tenant schema for the Manager domain.
// FLOW: Tenant provisioning -> migration -> native enums/tables/indexes -> Manager repositories.
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class ManagerTenantSchema1711000000100 implements MigrationInterface {
  name = 'ManagerTenantSchema1711000000100';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TABLE IF NOT EXISTS audit_logs (id uuid CONSTRAINT PK_audit_logs PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, actor_id uuid NOT NULL, actor_role varchar(32) NOT NULL, action varchar(80) NOT NULL, entity_type varchar(80) NOT NULL, entity_id uuid NOT NULL, old_value jsonb NULL, new_value jsonb NULL, ip_address varchar(64) NULL)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_audit_logs_entity ON audit_logs(entity_type,entity_id)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_audit_logs_actor ON audit_logs(actor_id)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_attendance_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_attendance (id uuid CONSTRAINT PK_manager_attendance PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_attendance_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_attendance_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_attendance_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendance_created_at ON manager_attendance(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendance_updated_at ON manager_attendance(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendance_deleted_at ON manager_attendance(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendance_status ON manager_attendance(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_communications_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_communications (id uuid CONSTRAINT PK_manager_communications PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_communications_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_communications_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_communications_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_created_at ON manager_communications(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_updated_at ON manager_communications(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_deleted_at ON manager_communications(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_status ON manager_communications(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_dashboard_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_dashboard (id uuid CONSTRAINT PK_manager_dashboard PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_dashboard_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_dashboard_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_dashboard_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboard_created_at ON manager_dashboard(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboard_updated_at ON manager_dashboard(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboard_deleted_at ON manager_dashboard(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboard_status ON manager_dashboard(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_expenses_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_expenses (id uuid CONSTRAINT PK_manager_expenses PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_expenses_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_expenses_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_expenses_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_created_at ON manager_expenses(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_updated_at ON manager_expenses(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_deleted_at ON manager_expenses(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_status ON manager_expenses(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_finance_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_finance (id uuid CONSTRAINT PK_manager_finance PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_finance_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_finance_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_finance_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finance_created_at ON manager_finance(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finance_updated_at ON manager_finance(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finance_deleted_at ON manager_finance(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finance_status ON manager_finance(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_grievance_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_grievance (id uuid CONSTRAINT PK_manager_grievance PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_grievance_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_grievance_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_grievance_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievance_created_at ON manager_grievance(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievance_updated_at ON manager_grievance(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievance_deleted_at ON manager_grievance(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievance_status ON manager_grievance(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_hrs_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_hrs (id uuid CONSTRAINT PK_manager_hrs PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_hrs_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_hrs_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_hrs_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrs_created_at ON manager_hrs(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrs_updated_at ON manager_hrs(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrs_deleted_at ON manager_hrs(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrs_status ON manager_hrs(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_inquiries_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_inquiries (id uuid CONSTRAINT PK_manager_inquiries PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_inquiries_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_inquiries_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_inquiries_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_created_at ON manager_inquiries(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_updated_at ON manager_inquiries(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_deleted_at ON manager_inquiries(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_status ON manager_inquiries(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_library_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_library (id uuid CONSTRAINT PK_manager_library PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_library_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_library_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_library_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_library_created_at ON manager_library(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_library_updated_at ON manager_library(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_library_deleted_at ON manager_library(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_library_status ON manager_library(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_maintenance_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_maintenance (id uuid CONSTRAINT PK_manager_maintenance PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_maintenance_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_maintenance_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_maintenance_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenance_created_at ON manager_maintenance(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenance_updated_at ON manager_maintenance(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenance_deleted_at ON manager_maintenance(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenance_status ON manager_maintenance(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_members_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_members (id uuid CONSTRAINT PK_manager_members PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_members_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_members_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_members_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_created_at ON manager_members(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_updated_at ON manager_members(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_deleted_at ON manager_members(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_status ON manager_members(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_notifications_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_notifications (id uuid CONSTRAINT PK_manager_notifications PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_notifications_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_notifications_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_notifications_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_created_at ON manager_notifications(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_updated_at ON manager_notifications(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_deleted_at ON manager_notifications(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_status ON manager_notifications(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_plans_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_plans (id uuid CONSTRAINT PK_manager_plans PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_plans_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_plans_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_plans_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_created_at ON manager_plans(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_updated_at ON manager_plans(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_deleted_at ON manager_plans(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_status ON manager_plans(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_profiles_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_profiles (id uuid CONSTRAINT PK_manager_profiles PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_profiles_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_profiles_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_profiles_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_created_at ON manager_profiles(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_updated_at ON manager_profiles(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_deleted_at ON manager_profiles(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_status ON manager_profiles(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_pts_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_pts (id uuid CONSTRAINT PK_manager_pts PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_pts_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_pts_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_pts_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_created_at ON manager_pts(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_updated_at ON manager_pts(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_deleted_at ON manager_pts(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_status ON manager_pts(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_referrals_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_referrals (id uuid CONSTRAINT PK_manager_referrals PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_referrals_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_referrals_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_referrals_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_created_at ON manager_referrals(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_updated_at ON manager_referrals(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_deleted_at ON manager_referrals(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_status ON manager_referrals(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_reports_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_reports (id uuid CONSTRAINT PK_manager_reports PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_reports_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_reports_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_reports_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_created_at ON manager_reports(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_updated_at ON manager_reports(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_deleted_at ON manager_reports(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_status ON manager_reports(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_sales_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_sales (id uuid CONSTRAINT PK_manager_sales PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_sales_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_sales_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_sales_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_created_at ON manager_sales(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_updated_at ON manager_sales(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_deleted_at ON manager_sales(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_status ON manager_sales(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_schedule_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_schedule (id uuid CONSTRAINT PK_manager_schedule PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_schedule_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_schedule_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_schedule_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedule_created_at ON manager_schedule(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedule_updated_at ON manager_schedule(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedule_deleted_at ON manager_schedule(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedule_status ON manager_schedule(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_settings_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_settings (id uuid CONSTRAINT PK_manager_settings PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_settings_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_settings_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_settings_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_created_at ON manager_settings(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_updated_at ON manager_settings(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_deleted_at ON manager_settings(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_status ON manager_settings(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_store_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_store (id uuid CONSTRAINT PK_manager_store PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_store_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_store_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_store_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_store_created_at ON manager_store(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_store_updated_at ON manager_store(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_store_deleted_at ON manager_store(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_store_status ON manager_store(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_workout_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_workout (id uuid CONSTRAINT PK_manager_workout PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_workout_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_workout_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_workout_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workout_created_at ON manager_workout(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workout_updated_at ON manager_workout(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workout_deleted_at ON manager_workout(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workout_status ON manager_workout(status)");
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS manager_workout');
    await queryRunner.query('DROP TYPE IF EXISTS manager_workout_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_store');
    await queryRunner.query('DROP TYPE IF EXISTS manager_store_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_settings');
    await queryRunner.query('DROP TYPE IF EXISTS manager_settings_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_schedule');
    await queryRunner.query('DROP TYPE IF EXISTS manager_schedule_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_sales');
    await queryRunner.query('DROP TYPE IF EXISTS manager_sales_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_reports');
    await queryRunner.query('DROP TYPE IF EXISTS manager_reports_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_referrals');
    await queryRunner.query('DROP TYPE IF EXISTS manager_referrals_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_pts');
    await queryRunner.query('DROP TYPE IF EXISTS manager_pts_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_profiles');
    await queryRunner.query('DROP TYPE IF EXISTS manager_profiles_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_plans');
    await queryRunner.query('DROP TYPE IF EXISTS manager_plans_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_notifications');
    await queryRunner.query('DROP TYPE IF EXISTS manager_notifications_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_members');
    await queryRunner.query('DROP TYPE IF EXISTS manager_members_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_maintenance');
    await queryRunner.query('DROP TYPE IF EXISTS manager_maintenance_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_library');
    await queryRunner.query('DROP TYPE IF EXISTS manager_library_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_inquiries');
    await queryRunner.query('DROP TYPE IF EXISTS manager_inquiries_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_hrs');
    await queryRunner.query('DROP TYPE IF EXISTS manager_hrs_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_grievance');
    await queryRunner.query('DROP TYPE IF EXISTS manager_grievance_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_finance');
    await queryRunner.query('DROP TYPE IF EXISTS manager_finance_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_expenses');
    await queryRunner.query('DROP TYPE IF EXISTS manager_expenses_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_dashboard');
    await queryRunner.query('DROP TYPE IF EXISTS manager_dashboard_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_communications');
    await queryRunner.query('DROP TYPE IF EXISTS manager_communications_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_attendance');
    await queryRunner.query('DROP TYPE IF EXISTS manager_attendance_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS audit_logs');
  }
}

