// RESPONSIBILITY: Owns backend core database schema migration.
// FLOW: Migration runner → ordered schema change → reversible database state transition.
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class ManagerTenantSchema1711000000100 implements MigrationInterface {
  name = 'ManagerTenantSchema1711000000100';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TABLE IF NOT EXISTS audit_logs (id uuid CONSTRAINT PK_audit_logs PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, actor_id uuid NOT NULL, actor_role varchar(32) NOT NULL, action varchar(80) NOT NULL, entity_type varchar(80) NOT NULL, entity_id uuid NOT NULL, old_value jsonb NULL, new_value jsonb NULL, ip_address varchar(64) NULL)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_audit_logs_entity ON audit_logs(entity_type,entity_id)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_audit_logs_actor ON audit_logs(actor_id)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_attendances_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_attendances (id uuid CONSTRAINT PK_manager_attendances PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_attendances_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_attendances_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_attendances_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendances_created_at ON manager_attendances(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendances_updated_at ON manager_attendances(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendances_deleted_at ON manager_attendances(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_attendances_status ON manager_attendances(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_communications_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_communications (id uuid CONSTRAINT PK_manager_communications PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_communications_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_communications_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_communications_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_created_at ON manager_communications(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_updated_at ON manager_communications(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_deleted_at ON manager_communications(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_communications_status ON manager_communications(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_dashboards_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_dashboards (id uuid CONSTRAINT PK_manager_dashboards PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_dashboards_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_dashboards_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_dashboards_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboards_created_at ON manager_dashboards(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboards_updated_at ON manager_dashboards(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboards_deleted_at ON manager_dashboards(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_dashboards_status ON manager_dashboards(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_expenses_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_expenses (id uuid CONSTRAINT PK_manager_expenses PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_expenses_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_expenses_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_expenses_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_created_at ON manager_expenses(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_updated_at ON manager_expenses(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_deleted_at ON manager_expenses(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_expenses_status ON manager_expenses(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_finances_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_finances (id uuid CONSTRAINT PK_manager_finances PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_finances_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_finances_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_finances_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finances_created_at ON manager_finances(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finances_updated_at ON manager_finances(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finances_deleted_at ON manager_finances(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_finances_status ON manager_finances(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_grievances_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_grievances (id uuid CONSTRAINT PK_manager_grievances PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_grievances_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_grievances_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_grievances_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievances_created_at ON manager_grievances(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievances_updated_at ON manager_grievances(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievances_deleted_at ON manager_grievances(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_grievances_status ON manager_grievances(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_hrss_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_hrss (id uuid CONSTRAINT PK_manager_hrss PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_hrss_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_hrss_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_hrss_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrss_created_at ON manager_hrss(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrss_updated_at ON manager_hrss(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrss_deleted_at ON manager_hrss(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_hrss_status ON manager_hrss(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_inquiries_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_inquiries (id uuid CONSTRAINT PK_manager_inquiries PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_inquiries_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_inquiries_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_inquiries_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_created_at ON manager_inquiries(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_updated_at ON manager_inquiries(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_deleted_at ON manager_inquiries(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_inquiries_status ON manager_inquiries(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_libraries_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_libraries (id uuid CONSTRAINT PK_manager_libraries PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_libraries_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_libraries_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_libraries_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_libraries_created_at ON manager_libraries(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_libraries_updated_at ON manager_libraries(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_libraries_deleted_at ON manager_libraries(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_libraries_status ON manager_libraries(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_maintenances_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_maintenances (id uuid CONSTRAINT PK_manager_maintenances PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_maintenances_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_maintenances_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_maintenances_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenances_created_at ON manager_maintenances(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenances_updated_at ON manager_maintenances(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenances_deleted_at ON manager_maintenances(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_maintenances_status ON manager_maintenances(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_members_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_members (id uuid CONSTRAINT PK_manager_members PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_members_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_members_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_members_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_created_at ON manager_members(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_updated_at ON manager_members(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_deleted_at ON manager_members(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_members_status ON manager_members(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_notifications_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_notifications (id uuid CONSTRAINT PK_manager_notifications PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_notifications_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_notifications_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_notifications_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_created_at ON manager_notifications(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_updated_at ON manager_notifications(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_deleted_at ON manager_notifications(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_notifications_status ON manager_notifications(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_plans_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_plans (id uuid CONSTRAINT PK_manager_plans PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_plans_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_plans_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_plans_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_created_at ON manager_plans(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_updated_at ON manager_plans(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_deleted_at ON manager_plans(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_plans_status ON manager_plans(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_profiles_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_profiles (id uuid CONSTRAINT PK_manager_profiles PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_profiles_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_profiles_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_profiles_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_created_at ON manager_profiles(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_updated_at ON manager_profiles(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_deleted_at ON manager_profiles(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_profiles_status ON manager_profiles(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_pts_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_pts (id uuid CONSTRAINT PK_manager_pts PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_pts_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_pts_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_pts_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_created_at ON manager_pts(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_updated_at ON manager_pts(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_deleted_at ON manager_pts(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_pts_status ON manager_pts(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_referrals_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_referrals (id uuid CONSTRAINT PK_manager_referrals PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_referrals_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_referrals_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_referrals_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_created_at ON manager_referrals(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_updated_at ON manager_referrals(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_deleted_at ON manager_referrals(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_referrals_status ON manager_referrals(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_reports_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_reports (id uuid CONSTRAINT PK_manager_reports PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_reports_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_reports_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_reports_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_created_at ON manager_reports(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_updated_at ON manager_reports(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_deleted_at ON manager_reports(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_reports_status ON manager_reports(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_sales_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_sales (id uuid CONSTRAINT PK_manager_sales PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_sales_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_sales_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_sales_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_created_at ON manager_sales(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_updated_at ON manager_sales(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_deleted_at ON manager_sales(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_sales_status ON manager_sales(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_schedules_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_schedules (id uuid CONSTRAINT PK_manager_schedules PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_schedules_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_schedules_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_schedules_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedules_created_at ON manager_schedules(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedules_updated_at ON manager_schedules(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedules_deleted_at ON manager_schedules(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_schedules_status ON manager_schedules(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_settings_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_settings (id uuid CONSTRAINT PK_manager_settings PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_settings_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_settings_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_settings_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_created_at ON manager_settings(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_updated_at ON manager_settings(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_deleted_at ON manager_settings(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_settings_status ON manager_settings(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_stores_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_stores (id uuid CONSTRAINT PK_manager_stores PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_stores_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_stores_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_stores_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_stores_created_at ON manager_stores(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_stores_updated_at ON manager_stores(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_stores_deleted_at ON manager_stores(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_stores_status ON manager_stores(status)");
    await queryRunner.query("DO $$ BEGIN CREATE TYPE manager_workouts_status_enum AS ENUM ('ACTIVE','INACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;");
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS manager_workouts (id uuid CONSTRAINT PK_manager_workouts PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz NULL, payload jsonb NOT NULL, status manager_workouts_status_enum NOT NULL DEFAULT 'ACTIVE', CONSTRAINT CHK_manager_workouts_payload_object CHECK (jsonb_typeof(payload)='object'), CONSTRAINT CHK_manager_workouts_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')))`,);
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workouts_created_at ON manager_workouts(created_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workouts_updated_at ON manager_workouts(updated_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workouts_deleted_at ON manager_workouts(deleted_at)");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS IDX_manager_workouts_status ON manager_workouts(status)");
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS manager_workouts');
    await queryRunner.query('DROP TYPE IF EXISTS manager_workouts_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_stores');
    await queryRunner.query('DROP TYPE IF EXISTS manager_stores_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_settings');
    await queryRunner.query('DROP TYPE IF EXISTS manager_settings_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_schedules');
    await queryRunner.query('DROP TYPE IF EXISTS manager_schedules_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_sales');
    await queryRunner.query('DROP TYPE IF EXISTS manager_sales_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_reports');
    await queryRunner.query('DROP TYPE IF EXISTS manager_reports_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_referrals');
    await queryRunner.query('DROP TYPE IF EXISTS manager_referrals_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_pts');
    await queryRunner.query('DROP TYPE IF EXISTS manager_pts_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_profiles');
    await queryRunner.query('DROP TYPE IF EXISTS manager_profiles_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_plans');
    await queryRunner.query('DROP TYPE IF EXISTS manager_plans_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_notifications');
    await queryRunner.query('DROP TYPE IF EXISTS manager_notifications_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_members');
    await queryRunner.query('DROP TYPE IF EXISTS manager_members_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_maintenances');
    await queryRunner.query('DROP TYPE IF EXISTS manager_maintenances_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_libraries');
    await queryRunner.query('DROP TYPE IF EXISTS manager_libraries_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_inquiries');
    await queryRunner.query('DROP TYPE IF EXISTS manager_inquiries_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_hrss');
    await queryRunner.query('DROP TYPE IF EXISTS manager_hrss_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_grievances');
    await queryRunner.query('DROP TYPE IF EXISTS manager_grievances_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_finances');
    await queryRunner.query('DROP TYPE IF EXISTS manager_finances_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_expenses');
    await queryRunner.query('DROP TYPE IF EXISTS manager_expenses_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_dashboards');
    await queryRunner.query('DROP TYPE IF EXISTS manager_dashboards_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_communications');
    await queryRunner.query('DROP TYPE IF EXISTS manager_communications_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS manager_attendances');
    await queryRunner.query('DROP TYPE IF EXISTS manager_attendances_status_enum');
    await queryRunner.query('DROP TABLE IF EXISTS audit_logs');
  }
}

