// RESPONSIBILITY: Renders the printable 80mm thermal receipt owned by the Store payment/order workflow. Rendering is print-only and performs no API work.
'use client';
import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { formatCurrency } from '@/app/manager/manager_layout/manager_utils/ManagerFormatCurrency';

import { ManagerEnvConfig } from '@/app/manager/manager_infrastructure/ManagerEnvConfig';
import type { ManagerStoreThermalReceiptProps } from '@/app/manager/store/store_types/ManagerStoreThermalReceiptTypes';
import { useLocale } from "next-intl";

// DATA FLOW: feature print state → receipt component props → print portal → browser print stylesheet.




export default function ManagerStoreThermalReceipt(props: ManagerStoreThermalReceiptProps) {
    const locale = useLocale();
 const { data } = props;
 const [mounted, setMounted] = useState(false);

// EFFECT: Effect lifecycle and dependency list are intentionally scoped to values that control this side effect.
 useEffect(() => {
   setMounted(true);
 }, []);

 if (!data || !mounted) return null;

 const receiptContent = (
 <div id="thermal-receipt" className="hidden print:block p-4 mx-auto bg-page text-primary font-mono leading-tight break-words" style={{ width: '80mm', maxWidth: '80mm', fontSize: '12px', boxSizing: 'border-box' }}>
 <div className="text-center border-border pb-2 mb-2" style={{ borderBottomWidth: '1.5px' }}>
 <h2 className="font-bold text-lg uppercase tracking-wider">{data.gymName}</h2>
 <p className="text-xs">Ph: {data.gymPhone}</p>
 <p className="font-bold mt-1 text-sm">PAYMENT RECEIPT</p>
 </div>
 
 <div className="mb-3 space-y-0.5 text-xs">
 <p><span className="font-bold">Receipt No:</span> {data.receiptNo}</p>
 <p><span className="font-bold">Date:</span> {data.date}</p>
 <p><span className="font-bold">Member:</span> {data.customerName}</p>
 </div>
 
 <table className="w-full mb-2 text-xs">
 <thead className="border-border" style={{ borderTopWidth: '1.5px', borderBottomWidth: '1.5px' }}>
 <tr>
 <th className="text-left font-bold py-1.5">Description</th>
 <th className="text-right font-bold py-1.5">Amount</th>
 </tr>
 </thead>
 <tbody className="border-border" style={{ borderBottomWidth: '1.5px' }}>
 {data.items.map((item, i) => (
 <tr key={`${item.name}-${item.price}-${item.amount}-${item.qty ?? 1}`}>
 <td className="py-1.5 pr-1">
 {item.name}
 {item.qty && item.qty > 1 && (
 <span className="block text-primary mt-0.5" style={{ fontSize: '10px' }}>
 {item.qty} x {formatCurrency(item.price, ManagerEnvConfig.currencyCode, locale)}
 </span>
 )}
 </td>
 <td className="text-right py-1.5 align-top">{formatCurrency(item.amount, ManagerEnvConfig.currencyCode, locale)}</td>
 </tr>
 ))}
 </tbody>
 </table>
 
 <div className="flex justify-between font-bold text-base mb-2">
 <span>TOTAL:</span>
 <span>{formatCurrency(data.total, ManagerEnvConfig.currencyCode, locale)}</span>
 </div>
 
 <div className="mb-4 text-xs">
 <p><span className="font-bold">Paid via:</span> {data.paymentMethod}</p>
 </div>
 
 <div className="text-center border-border pt-2 mt-3" style={{ borderTopWidth: '1.5px' }}>
 <p className="font-bold uppercase mb-0.5 text-sm">Thank You!</p>
 <p style={{ fontSize: '10px' }}>No Refund / No Exchange</p>
 <p className="mt-0.5" style={{ fontSize: '10px' }}>Generated by GymSmart MANAGER</p>
 </div>
 </div>
 );

 return createPortal(receiptContent, document.body);
}
