// Generated by ts-to-zod
import { z } from "zod";
import { NOTIFICATION_SEVERITY } from '@/app/frontend_admin/admin_notifications/admin_notifications_constants/AdminNotificationsConstants';

export const notificationSeveritySchema = z.enum(Object.values(NOTIFICATION_SEVERITY) as [string, ...string[]]);

export const adminNotificationSchema = z.object({
    id: z.string(),
    title: z.string(),
    body: z.string(),
    severity: notificationSeveritySchema,
    read: z.boolean(),
    createdAt: z.string(),
    branchId: z.string().optional(),
    branchName: z.string().optional()
});

export const notificationItemSchema = z.object({
    id: z.string(),
    text: z.string(),
    time: z.string(),
    unread: z.boolean()
});

