// Generated by ts-to-zod
import { z } from "zod";

export const adminQrScanStatusSchema = z.union([z.literal("IDLE"), z.literal("SCANNING"), z.literal("ACTIVE"), z.literal("EXPIRED")]);

export const adminQrScanHistoryRecordSchema = z.object({
    id: z.string(),
    time: z.string(),
    name: z.string()
});

export const adminAttendanceQrScannerModalPropsSchema = z.object({
    open: z.boolean(),
    onClose: z.function({ input: [], output: z.void() })
});
