// RESPONSIBILITY: Static hardcoded data and constants for the Tenant Onboarding module.

import type { TenantOnboarding } from '@/app/superadmin/onboarding/onboarding_types/onboarding_types';

/** Premium gold gradient applied to all KPI stat cards. Design §5a. */
export const KPI_CARD_GRADIENT = 'linear-gradient(180deg, rgba(250,204,21,0.08), rgba(255,255,255,0.02))';

export const ONBOARDING_STATUS_STYLES: Record<string, string> = {
  COMPLETED: 'bg-success/10 text-success border border-success/30',
  IN_PROGRESS: 'bg-primary/10 text-primary border border-primary/30',
  PENDING: 'bg-warning/10 text-warning border border-warning/30',
  STALLED: 'bg-danger/10 text-danger border border-danger/30',
};

export const TRIAL_STATUS_STYLES: Record<string, string> = {
  TRIAL: 'bg-primary/10 text-primary border border-primary/30',
  ACTIVE: 'bg-success/10 text-success border border-success/30',
  EXPIRED: 'bg-danger/10 text-danger border border-danger/30',
  CONVERTED: 'bg-purple-bg text-purple border border-purple/30',
};

export const MOCK_ONBOARDINGS: TenantOnboarding[] = [
  {
    id: 'gym-1234',
    gymName: 'Flex Fitness Central',
    ownerName: 'Sarah Connor',
    adminEmail: 'sarah@flexfitness.com',
    phone: '+91 98765 43210',
    plan: 'ENTERPRISE',
    signupDate: '2024-01-15',
    trialEndsAt: null,
    trialStatus: 'CONVERTED',
    onboardingStatus: 'COMPLETED',
    emailVerified: true,
    welcomeEmailSent: true,
    daysInTrial: 14,
    trialDaysLeft: 0,
    checklist: [
      { key: 'email_verified', label: 'Email Verified', done: true },
      { key: 'profile_complete', label: 'Profile Completed', done: true },
      { key: 'first_member', label: 'First Member Added', done: true },
      { key: 'payment_setup', label: 'Payment Setup', done: true },
      { key: 'plan_selected', label: 'Plan Selected', done: true },
    ],
  },
  {
    id: 'gym-5678',
    gymName: 'Iron Temple Barbell Club',
    ownerName: 'Arnold Strong',
    adminEmail: 'arnold@irontemple.com',
    phone: '+91 91234 56789',
    plan: 'PRO',
    signupDate: '2024-05-10',
    trialEndsAt: '2024-05-24',
    trialStatus: 'TRIAL',
    onboardingStatus: 'IN_PROGRESS',
    emailVerified: true,
    welcomeEmailSent: true,
    daysInTrial: 8,
    trialDaysLeft: 6,
    checklist: [
      { key: 'email_verified', label: 'Email Verified', done: true },
      { key: 'profile_complete', label: 'Profile Completed', done: true },
      { key: 'first_member', label: 'First Member Added', done: false },
      { key: 'payment_setup', label: 'Payment Setup', done: false },
      { key: 'plan_selected', label: 'Plan Selected', done: true },
    ],
  },
  {
    id: 'gym-9012',
    gymName: 'Zenith Yoga & Pilates',
    ownerName: 'Mia Wong',
    adminEmail: 'mia@zenithyoga.com',
    phone: '+91 87654 32109',
    plan: 'STARTER',
    signupDate: '2024-05-18',
    trialEndsAt: '2024-06-01',
    trialStatus: 'TRIAL',
    onboardingStatus: 'PENDING',
    emailVerified: false,
    welcomeEmailSent: false,
    daysInTrial: 0,
    trialDaysLeft: 14,
    checklist: [
      { key: 'email_verified', label: 'Email Verified', done: false },
      { key: 'profile_complete', label: 'Profile Completed', done: false },
      { key: 'first_member', label: 'First Member Added', done: false },
      { key: 'payment_setup', label: 'Payment Setup', done: false },
      { key: 'plan_selected', label: 'Plan Selected', done: false },
    ],
  },
  {
    id: 'gym-3456',
    gymName: 'PowerHouse Gym Koramangala',
    ownerName: 'Ravi Shankar',
    adminEmail: 'ravi@powerhouse.in',
    phone: '+91 99887 76655',
    plan: 'PRO',
    signupDate: '2024-04-01',
    trialEndsAt: '2024-04-15',
    trialStatus: 'EXPIRED',
    onboardingStatus: 'STALLED',
    emailVerified: true,
    welcomeEmailSent: true,
    daysInTrial: 14,
    trialDaysLeft: 0,
    checklist: [
      { key: 'email_verified', label: 'Email Verified', done: true },
      { key: 'profile_complete', label: 'Profile Completed', done: true },
      { key: 'first_member', label: 'First Member Added', done: false },
      { key: 'payment_setup', label: 'Payment Setup', done: false },
      { key: 'plan_selected', label: 'Plan Selected', done: true },
    ],
  },
  {
    id: 'gym-7890',
    gymName: 'FitZone Indiranagar',
    ownerName: 'Priya Mehta',
    adminEmail: 'priya@fitzone.in',
    phone: '+91 77665 54433',
    plan: 'STARTER',
    signupDate: '2024-05-20',
    trialEndsAt: '2024-06-03',
    trialStatus: 'TRIAL',
    onboardingStatus: 'IN_PROGRESS',
    emailVerified: true,
    welcomeEmailSent: true,
    daysInTrial: 2,
    trialDaysLeft: 12,
    checklist: [
      { key: 'email_verified', label: 'Email Verified', done: true },
      { key: 'profile_complete', label: 'Profile Completed', done: true },
      { key: 'first_member', label: 'First Member Added', done: true },
      { key: 'payment_setup', label: 'Payment Setup', done: false },
      { key: 'plan_selected', label: 'Plan Selected', done: false },
    ],
  },
];
