// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const announcementStatusSchema = z.union([z.literal("active"), z.literal("scheduled"), z.literal("expired"), z.literal("draft")]);

export const announcementPrioritySchema = z.union([z.literal("high"), z.literal("medium"), z.literal("low")]);

export const announcementAudienceSchema = z.union([z.literal("all"), z.literal("members"), z.literal("managers"), z.literal("trainers"), z.literal("staff")]);

export const announcementSchema = z.object({
    id: z.string(),
    title: z.string(),
    body: z.string(),
    priority: announcementPrioritySchema,
    status: announcementStatusSchema,
    audience: z.array(announcementAudienceSchema),
    gymIds: z.array(z.string()),
    gymNames: z.array(z.string()),
    publishedAt: z.string(),
    expiresAt: z.string(),
    createdBy: z.string(),
    createdAt: z.string(),
    viewCount: z.number(),
    viewsByBranch: z.array(z.object({
        branchId: z.string(),
        count: z.number()
    })).optional(),
    isPinned: z.boolean(),
    deliveryStatus: z.string().optional(),
    pushNotificationSent: z.boolean().optional(),
    acknowledgedCount: z.number().optional()
});

export const announcementFormValuesSchema = z.object({
    title: z.string(),
    body: z.string(),
    priority: announcementPrioritySchema,
    audience: z.array(announcementAudienceSchema),
    gymIds: z.array(z.string()),
    publishedAt: z.string(),
    expiresAt: z.string(),
    isPinned: z.boolean()
});

export const announcementKpiDataSchema = z.object({
    total: z.number(),
    active: z.number(),
    scheduled: z.number(),
    expired: z.number(),
    totalViews: z.number(),
    pinned: z.number()
});
