'use client';
// RESPONSIBILITY: Renders the Manager Settings editable experience; field state, validation, submit orchestration, and server data belong to the adjacent hook.
import { Building, Clock, Globe, Loader2, Mail, Save, Settings } from 'lucide-react';
import { Controller } from 'react-hook-form';
import { useState } from 'react';
import { useManagerSettingsForm } from '@/app/manager/settings/settings_hooks/ManagerUseManagerSettingsForm';
import ManagerSearchableDropdown from '@/app/manager/manager_components/ManagerShared/ManagerSearchableDropdown';
import { LANGUAGE_OPTIONS, TIMEZONE_OPTIONS, SETTINGS_TABS, NOTIFICATION_TEMPLATE_LABELS, type SettingsTab } from '@/app/manager/settings/settings_types/ManagerSettingsTypes';
import { MANAGER_SETTINGS_GYM_FIELD_LABELS, MANAGER_SETTINGS_MEMBERSHIP_FIELD_LABELS } from '@/app/manager/settings/settings_constants/ManagerSettingsFieldLabels';
import { MANAGER_GENERIC_ERROR_MESSAGE, getManagerErrorMessage } from '@/app/manager/manager_infrastructure/ManagerErrorMessage';

export default function ManagerSettingsMain() {
  const { settings, isLoading, isError, error, retry, saving, form, submit } = useManagerSettingsForm();
  const [activeTab, setActiveTab] = useState<SettingsTab>('region');
  const { control, register, formState: { errors } } = form;
  if (isLoading && !settings) return <div className="space-y-5 p-6 motion-safe:animate-pulse"><div className="h-8 w-48 rounded bg-skeleton-base" /><div className="h-12 w-96 max-w-full rounded bg-skeleton-base" /><div className="h-96 rounded-xl bg-skeleton-base" /></div>;
  if (isError && !settings) return <div role="alert" className="m-6 flex flex-col gap-3 rounded-xl border border-danger bg-danger-bg p-5 text-sm"><p className="font-semibold text-danger">{getManagerErrorMessage(error) || MANAGER_GENERIC_ERROR_MESSAGE}</p><button type="button" onClick={() => void retry()} className="min-h-11 w-fit rounded-lg bg-primary px-4 font-semibold text-on-danger focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">Retry</button></div>;

  return (
    <div className="mx-auto max-w-4xl space-y-6 bg-page p-4 text-primary sm:p-6">
      <div><h1 className="text-page-title font-bold text-primary">App Settings</h1><p className="mt-1 text-sm text-secondary">Manage your preferences and app behaviour.</p></div>
      <div className="flex max-w-full overflow-x-auto rounded-xl bg-input p-1" role="tablist" aria-label="Manager settings sections">
        {SETTINGS_TABS.map((tab) => <button key={tab.id} id={`manager-settings-tab-${tab.id}`} type="button" role="tab" aria-selected={activeTab === tab.id} aria-controls={`manager-settings-panel-${tab.id}`} onClick={() => setActiveTab(tab.id)} className={`min-h-11 whitespace-nowrap rounded-lg px-4 text-sm font-medium motion-safe:transition-all motion-safe:duration-base focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${activeTab === tab.id ? 'bg-card text-on-primary shadow-card' : 'text-secondary hover:bg-surface-hover hover:text-on-primary'}`}>{tab.label}</button>)}
      </div>
      <form onSubmit={submit} className="space-y-6">
        {activeTab === 'region' && <section id="manager-settings-panel-region" role="tabpanel" aria-labelledby="manager-settings-tab-region" className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2 border-b border-border pb-3"><Globe size={18} className="text-on-primary" aria-hidden="true" /><h2 className="text-base font-semibold text-on-primary">Region &amp; Language</h2></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium text-secondary">Language</label><Controller name="preferences.language" control={control} render={({ field }) => <ManagerSearchableDropdown value={field.value} onChange={field.onChange} options={[...LANGUAGE_OPTIONS]} placeholder="Select language" />} /></div><div><label className="mb-1.5 block text-sm font-medium text-secondary">Timezone</label><Controller name="preferences.timezone" control={control} render={({ field }) => <ManagerSearchableDropdown value={field.value} onChange={field.onChange} options={[...TIMEZONE_OPTIONS]} placeholder="Select timezone" />} /></div></div>{([['preferences.pushNotificationsEnabled','Push Notifications','Receive alerts for new members and payments'],['preferences.emailDailyReports','Email Daily Reports','Get daily summary of collections and attendance']] as const).map(([name,label,description]) => <Controller key={name} name={name} control={control} render={({ field }) => <label className="flex min-h-11 items-center justify-between gap-4 rounded-xl border border-border bg-input p-3"><div><p className="text-sm font-medium text-on-primary">{label}</p><p className="mt-0.5 text-xs text-secondary">{description}</p></div><input type="checkbox" checked={field.value} onChange={field.onChange} className="h-4 w-4 rounded border-border text-on-primary focus-visible:ring-2 focus-visible:ring-primary" aria-label={label} /></label>} />)}</section>}

        {activeTab === 'gym_profile' && <section id="manager-settings-panel-gym_profile" role="tabpanel" aria-labelledby="manager-settings-tab-gym_profile" className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2 border-b border-border pb-3"><Building size={18} className="text-on-primary" aria-hidden="true" /><h2 className="text-base font-semibold text-on-primary">Gym Profile</h2></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2">{(Object.keys(MANAGER_SETTINGS_GYM_FIELD_LABELS) as Array<keyof typeof MANAGER_SETTINGS_GYM_FIELD_LABELS>).map((fieldName) => { const id = `gym-${String(fieldName)}`; const fieldError = errors.gymProfile?.[fieldName]?.message; return <div key={fieldName}><label htmlFor={id} className="mb-1.5 block text-sm font-medium text-secondary">{MANAGER_SETTINGS_GYM_FIELD_LABELS[fieldName]}</label><input id={id} {...register(`gymProfile.${fieldName}`)} aria-invalid={Boolean(fieldError)} aria-describedby={fieldError ? `${id}-error` : undefined} className="w-full rounded-lg border border-border bg-input px-3 py-2 text-sm text-on-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" />{fieldError && <p id={`${id}-error`} role="alert" className="mt-1 text-xs text-danger">{String(fieldError)}</p>}</div>; })}</div></section>}

        {activeTab === 'operating_hours' && <section id="manager-settings-panel-operating_hours" role="tabpanel" aria-labelledby="manager-settings-tab-operating_hours" className="space-y-5 rounded-xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2 border-b border-border pb-3"><Clock size={18} className="text-on-primary" aria-hidden="true" /><h2 className="text-base font-semibold text-on-primary">Operating Hours</h2></div>{(settings?.operatingHours ?? []).map((item, index) => <div key={item.day} className="flex flex-col gap-3 rounded-xl border border-border bg-input p-3 sm:flex-row sm:items-center"><Controller name={`operatingHours.${index}.isOpen`} control={control} render={({ field }) => <label className="flex min-h-11 items-center gap-2 sm:w-32"><input type="checkbox" checked={field.value} onChange={field.onChange} className="h-4 w-4 rounded border-border text-on-primary focus-visible:ring-2 focus-visible:ring-primary" />{item.day}</label>} /><label className="flex flex-1 items-center gap-2 text-xs text-secondary">Open <input aria-label={`${item.day} opening time`} type="time" {...register(`operatingHours.${index}.openTime`)} className="min-h-11 flex-1 rounded-lg border border-border bg-card px-3 py-1.5 text-sm text-on-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /></label><span className="text-secondary sm:pt-2">to</span><label className="flex flex-1 items-center gap-2 text-xs text-secondary">Close <input aria-label={`${item.day} closing time`} type="time" {...register(`operatingHours.${index}.closeTime`)} className="min-h-11 flex-1 rounded-lg border border-border bg-card px-3 py-1.5 text-sm text-on-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /></label></div>)}</section>}



        <div className="flex justify-end pt-2"><button type="submit" disabled={saving} className="flex min-h-11 min-w-32 items-center justify-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-on-primary shadow-card motion-safe:transition-all motion-safe:duration-base motion-safe:active:scale-95 disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page">{saving ? <Loader2 size={18} className="motion-safe:animate-spin" aria-hidden="true" /> : <Save size={18} aria-hidden="true" />}{saving ? 'Saving…' : 'Save Settings'}</button></div>
      </form>
    </div>
  );
}
