// RESPONSIBILITY: Renders saved tenant segments with real Apply and Edit actions delegated to the page orchestrator.
'use client';
import { ListFilter, Save } from 'lucide-react';
import { displayValue, formatDate, formatNumber } from '@/lib/formatters';
import SuperadminSegmentsSavedGroupsEmptyState from '@/app/superadmin/segments/segments_components/SuperadminSegmentsSavedGroupsEmptyState';
import SuperadminTooltip from '@/app/superadmin/superadmin_components/SuperadminShared/SuperadminTooltip';
import SuperadminV1Panel from '@/app/superadmin/superadmin_components/SuperadminShared/SuperadminV1Panel';
import type { SuperadminSegmentsSectionProps } from '@/app/superadmin/segments/segments_types/SuperadminSegmentsTypes';
export default function SuperadminSegmentsSavedGroupsPanel({ data, onEdit, onApply }: SuperadminSegmentsSectionProps) {
    return <SuperadminV1Panel title="Saved Groups" description="Segments hold filter rules and audience counts; tenant records remain API-owned."><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{data.segments.length === 0 ? <SuperadminSegmentsSavedGroupsEmptyState/> : data.segments.map(segment => <article key={segment.id} className="rounded-lg border border-border bg-input p-4 motion-safe:transition-all motion-safe:duration-base motion-safe:hover:-translate-y-1"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><ListFilter size={18} className="text-primary"/><SuperadminTooltip content={segment.name}><h3 className="max-w-40 truncate font-semibold text-foreground">{segment.name}</h3></SuperadminTooltip></div><p className="mt-2 text-xs text-secondary">{displayValue(segment.description, '—')}</p></div><span className="rounded-full bg-primary-subtle px-2 py-1 text-xs font-semibold text-primary">{formatNumber(segment.tenantCount)} gyms</span></div><div className="mt-3 flex items-center justify-between text-xs text-secondary"><span>{formatNumber(segment.rules)} rules</span><SuperadminTooltip content={segment.usedIn}><span className="max-w-40 truncate">{segment.usedIn}</span></SuperadminTooltip></div><p className="mt-2 text-xs text-secondary">Updated: {displayValue(segment.updatedAt ? formatDate(segment.updatedAt) : null, '—')}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>onApply?.(segment)} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-xs font-medium text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><ListFilter size={18}/>Apply to Gyms</button><button type="button" onClick={()=>onEdit?.(segment)} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-xs font-medium text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Save size={18}/>Edit Rules</button></div></article>)}</div></SuperadminV1Panel>;
}
