
'use client';
// RESPONSIBILITY: View-only renderer for System & Audit. All client state, query/mutation orchestration, URL-backed filters, and export logic live in useSuperadminSystemClient.ts.
import { Database, ShieldAlert, Activity, Filter, RefreshCcw, Search, Loader2, Clock, Download } from 'lucide-react';
import SuperadminSystemEmptyState from '@/app/superadmin/system/system_components/SuperadminSystemEmptyState/SuperadminSystemEmptyState';
import SuperadminSystemSlaTab from '@/app/superadmin/system/system_components/SuperadminSystemSlaTab';
import SuperadminPagination from '@/app/superadmin/superadmin_components/SuperadminShared/SuperadminPagination';
import { useSuperadminSystemClient } from '@/app/superadmin/system/system_components/useSuperadminSystemClient';

export default function SuperadminSystemClient() {
  const model = useSuperadminSystemClient();
  if (model.isLoading) return <div className="flex h-96 items-center justify-center"><Loader2 className="w-8 h-8 motion-safe:animate-spin text-primary" /></div>;
  if (model.isError) return <div className="flex h-96 items-center justify-center text-danger">Unable to load system data. Please retry.</div>;
  return (
    <div className="space-y-8">
      <div><h1 className="text-2xl font-bold text-foreground">System &amp; Audit</h1><p className="text-secondary mt-1">Global database migration health and cross-gym uptime tracking.</p></div>
      <div className="flex gap-1 bg-input border border-border rounded-xl p-1 w-fit">
        <button onClick={() => model.setTab('migrations')} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium motion-safe:transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${model.tab === 'migrations' ? 'bg-card text-foreground shadow-sm' : 'text-secondary hover:text-foreground'}`}><Database className="w-5 h-5" strokeWidth={2}/> Migrations &amp; Audit</button>
        <button onClick={() => model.setTab('sla')} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium motion-safe:transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${model.tab === 'sla' ? 'bg-card text-foreground shadow-sm' : 'text-secondary hover:text-foreground'}`}><Clock className="w-5 h-5" strokeWidth={2}/> Uptime Tracker</button>
      </div>
      {model.tab === 'migrations' ? <div className="space-y-8 motion-safe:animate-superadmin-fade-in-up">
        <div><div className="flex items-center gap-2 mb-4"><Database className="w-5 h-5 text-primary"/><h2 className="text-xl font-bold text-foreground">Migration Health</h2></div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{model.tenants.map(tenant => { const outdated = tenant.databaseVersion !== (process.env.NEXT_PUBLIC_CURRENT_SCHEMA_VERSION || 'v2.4.1'); return <div key={tenant.id} className={`border rounded-xl p-6 ${outdated ? 'bg-warning-bg border-warning/30' : 'bg-card border-border'}`}><div className="flex justify-between items-start mb-4"><div><h3 className="font-semibold text-foreground">{tenant.name}</h3><p className="text-xs text-disabled mt-1">Database: gym_{tenant.id.replace('-', '_')}</p></div><span className={`px-2 py-1 rounded text-xs font-mono font-medium ${outdated ? 'bg-warning/20 text-warning' : 'bg-success-bg text-success'}`}>{tenant.databaseVersion}</span></div>{outdated ? <button onClick={() => model.handleRunMigration(tenant.id)} disabled={model.migratingTenants[tenant.id]} className="w-full flex justify-center items-center gap-2 bg-warning hover:bg-warning text-black py-2 rounded-lg text-sm font-medium motion-safe:transition-colors disabled:opacity-50">{model.migratingTenants[tenant.id] ? <Loader2 className="w-4 h-4 motion-safe:animate-spin"/> : <RefreshCcw className="w-4 h-4"/>}{model.migratingTenants[tenant.id] ? 'Migrating...' : 'Run Migrations'}</button> : <button disabled className="w-full flex justify-center items-center gap-2 bg-border text-disabled py-2 rounded-lg text-sm font-medium cursor-not-allowed"><Activity className="w-4 h-4"/> Fully Synced</button>}</div>; })}</div></div>
        <div className="pt-8 border-t border-border"><div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-4"><div className="flex flex-wrap items-center gap-2"><ShieldAlert className="w-5 h-5 text-primary"/><h2 className="text-xl font-bold text-foreground">Global Audit Log</h2></div><div className="flex flex-wrap items-center gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-disabled"/><input aria-label="Search audit logs" type="text" placeholder="Search logs..." value={model.logSearch} onChange={e => model.setLogSearch(e.target.value)} className="bg-card border border-border text-foreground text-sm rounded-lg pl-9 pr-4 py-2 focus:outline-none focus:border-primary"/></div><button aria-label="Filter audit logs" className="p-2 bg-card border border-border rounded-lg text-secondary hover:text-foreground motion-safe:transition-colors"><Filter className="w-4 h-4"/></button><button onClick={model.handleExportCSV} className="flex items-center gap-2 p-2 bg-input border border-border rounded-lg text-sm font-medium text-foreground hover:bg-card-hover motion-safe:transition-colors"><Download className="w-4 h-4"/> Export CSV</button></div></div>
          <div className="bg-card border border-border rounded-xl overflow-hidden flex flex-col min-h-96"><div className="overflow-x-auto flex-1"><table className="w-full text-left border-collapse"><thead><tr className="bg-card border-b border-border text-secondary text-sm"><th className="p-4 font-medium">Timestamp</th><th className="p-4 font-medium">Target</th><th className="p-4 font-medium">Actor</th><th className="p-4 font-medium">Action</th></tr></thead><tbody className="divide-y divide-border">{model.logs.map(log => <tr key={log.id} className="superadmin-table-row group hover:bg-input motion-safe:transition-colors text-sm"><td className="p-4 text-secondary whitespace-nowrap">{new Date(log.timestamp).toLocaleString()}</td><td className="p-4 text-primary font-medium">{log.targetResource}</td><td className="p-4"><p className="text-foreground">{log.actorName}</p><span className="text-xs text-disabled bg-border px-2 py-0.5 rounded mt-1 inline-block">{log.actorRole}</span></td><td className="p-4"><span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold bg-info-bg text-info font-mono">{log.action}</span></td></tr>)}{model.logs.length === 0 && <SuperadminSystemEmptyState/>}</tbody></table></div><SuperadminPagination currentPage={model.currentPage} totalPages={model.totalPages} onPageChange={model.setCurrentPage}/></div>
        </div>
      </div> : <SuperadminSystemSlaTab />}
    </div>
  );
}
