// RESPONSIBILITY: Renders ManagerCommunicationsComposer's feature UI and orchestrates presentation through module-owned state/hooks; it does not own API transport or business rules.
'use client';
import { useState } from 'react';
import { MessageCircle, Mail, Send, Loader2, Users, Eye, Zap } from 'lucide-react';
import { useTranslations } from 'next-intl';
import ManagerCommunicationsBulkMessageModal from '@/app/frontend_manager/manager_communications/manager_communications_components/manager_communications_bulk_message_modal/ManagerCommunicationsBulkMessageModal';
import ManagerCommunicationsSegmentPicker from '@/app/frontend_manager/manager_communications/manager_communications_components/manager_communications_segment_picker/ManagerCommunicationsSegmentPicker';
import { COMM_MESSAGE_TEMPLATES } from '@/app/frontend_manager/manager_communications/manager_communications_constants/ManagerCommunicationsSharedConstants';
import { useManagerCommunicationsForm } from '@/app/frontend_manager/manager_communications/manager_communications_hooks/useManagerCommunicationsForm';
import { ManagerCommunicationsUrlConfig } from '@/app/frontend_manager/manager_communications/manager_communications_url_config';
import type { CommChannel } from '@/app/frontend_manager/manager_communications/manager_communications_types/ManagerCommunicationsTypes';
import type { CommSegment } from '@/app/frontend_manager/manager_communications/manager_communications_types/ManagerCommunicationsTypes';



/** @description Renders the ManagerCommunicationsComposer component for its owning Manager frontend boundary. @dependencies Local dependencies are owned by this feature module (7 documented module/import dependencies).. @edge-case Preserves loading state, error state, modal lifecycle. */
export default function ManagerCommunicationsComposer() {
  const t = useTranslations('MANAGER_COMMUNICATIONS');

  const { selectedChannel, setSelectedChannel, selectedSegment, segmentRecipients, loadingRecipients, sending, form, applyTemplate, submit, handleCancel } = useManagerCommunicationsForm();
  const [showPreview, setShowPreview] = useState(false);
  const watchedChannel = form.watch('channel');
  const watchedMessage = form.watch('message');
  const bulkRecipients = segmentRecipients.map((r) => ({ name: r.name, phone: r.phone, email: r.email }));

  return <div className="bg-card border border-border rounded-xl p-6 space-y-6 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1">
    <ManagerCommunicationsSegmentPicker />
    <div className="space-y-2"><div id="manager-communications-channel-label" className="block text-sm font-semibold text-secondary uppercase tracking-wider">{t("COPY_2_CHOOSE_CHANNEL")}</div><div data-testid="manager_communications-managercommunicationscomposer-radiogroup"role="radiogroup" aria-labelledby="manager-communications-channel-label" className="flex flex-wrap gap-3">
      <label className={[`flex items-center gap-2 px-5 py-2.5 rounded-xl border text-sm font-semibold cursor-pointer motion-safe:transition-all ${watchedChannel === 'whatsapp' ? 'bg-social-whatsapp text-on-primary border-social-whatsapp' : 'bg-input border-border text-secondary'}`, "motion-safe:duration-base ease-in-out"].filter(Boolean).join(' ')}>
        <input data-testid="manager_communications-manager-communications-composer-input-radio-select-1" type="radio" value="whatsapp" {...form.register('channel')} className="sr-only focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" checked={watchedChannel === 'whatsapp'} onChange={() => { setSelectedChannel('whatsapp'); form.setValue('channel', 'whatsapp', { shouldDirty: true, shouldValidate: true }); }} />
        <MessageCircle size={18} strokeWidth={2} />{t("COPY_WHATSAPP_2")}</label>
      <label className={[`flex items-center gap-2 px-5 py-2.5 rounded-xl border text-sm font-semibold cursor-pointer motion-safe:transition-all ${watchedChannel === 'email' ? 'bg-primary text-on-primary border-primary' : 'bg-input border-border text-secondary'}`, "motion-safe:duration-base ease-in-out"].filter(Boolean).join(' ')}>
        <input data-testid="manager_communications-manager-communications-composer-input-radio-select-2" type="radio" value="email" {...form.register('channel')} className="sr-only focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" checked={watchedChannel === 'email'} onChange={() => { setSelectedChannel('email'); form.setValue('channel', 'email', { shouldDirty: true, shouldValidate: true }); }} />
        <Mail size={18} strokeWidth={2}/>{t("COPY_EMAIL_1")}</label>
    </div></div>
    <div className="space-y-4"><label className="block text-sm font-semibold text-secondary uppercase tracking-wider">{t("COPY_3_COMPOSE_MESSAGE")}</label>
      <div className="bg-input border border-border rounded-lg p-3"><label className="block text-xs font-semibold text-primary mb-2 flex items-center gap-1.5"><Zap size={18} strokeWidth={2} className="text-warning"/>{t("COPY_QUICK_TEMPLATES")}</label><div className="flex flex-wrap gap-2">{(Object.keys(COMM_MESSAGE_TEMPLATES) as CommSegment[]).map((segment, mapIndex) => <button className={ ["focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page", "px-3 py-1.5 text-xs font-medium bg-card border border-border rounded-md motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"].filter((value) => Boolean(value)).join(' ') } data-testid={`manager_communications-communications-managercommunicationscomposer-button-3-compose-message-${mapIndex}`} key={segment} type="button" onClick={() => applyTemplate(segment)} >{COMM_MESSAGE_TEMPLATES[segment].subject}</button>)}</div></div>
      <div><label htmlFor="manager-communications-title" className="block text-xs font-medium text-secondary mb-1">{t("COPY_CAMPAIGN_TITLE")}</label><input data-testid="manager_communications-manager-communications-composer-manager-communications-title" id="manager-communications-title" {...form.register('title')} className="w-full bg-input border border-border rounded-lg px-3 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" />{form.formState.errors.title && <p className="text-xs text-danger mt-1">{form.formState.errors.title.message}</p>}</div>
      {watchedChannel === 'email' && <div><label htmlFor="manager-communications-subject" className="block text-xs font-medium text-secondary mb-1">{t("COPY_EMAIL_SUBJECT_1")}</label><input data-testid="manager_communications-manager-communications-composer-manager-communications-subject" id="manager-communications-subject" {...form.register('subject')} className="w-full bg-input border border-border rounded-lg px-3 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div>}
      <div><label htmlFor="manager-communications-message" className="block text-xs font-medium text-secondary mb-1">{t("COPY_MESSAGE_BODY")}</label><textarea data-testid="manager_communications-manager-communications-composer-manager-communications-message" id="manager-communications-message" rows={6} {...form.register('message')} className="w-full bg-input border border-border rounded-xl px-3 py-2.5 text-sm text-primary resize-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /><p className="text-xs text-secondary mt-1">{watchedMessage.length}{t("COPY_CHARACTERS")}</p></div>
    </div>
    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pt-4 border-t border-border"><div className="flex items-center gap-2 text-sm text-secondary">{loadingRecipients ? <Loader2 size={18} strokeWidth={2} className="motion-safe:animate-spin"/> : <Users size={18} strokeWidth={2}/>}{(() => { if (loadingRecipients) { return t('COPY_LOADING_RECIPIENTS'); } return t(segmentRecipients.length === 1 ? 'TEXT_RECIPIENT_SINGULAR' : 'TEXT_RECIPIENT_PLURAL', { count: segmentRecipients.length }); })()}</div><div className="flex gap-3">{segmentRecipients.length > 0 && <button className={ ["focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page", "flex items-center gap-2 px-4 py-2 bg-input border border-border rounded-lg text-sm font-medium motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"].filter((value) => Boolean(value)).join(' ') } data-testid="manager_communications-manager-communications-composer-button-preview" type="button" onClick={() => setShowPreview(true)} ><Eye size={18} strokeWidth={2}/>{t("COPY_PREVIEW_SEND")}</button>}<button data-testid="manager_communications-manager-communications-composer-button-submit" type="button" onClick={submit} disabled={sending || loadingRecipients || segmentRecipients.length === 0} className="min-w-32 flex items-center gap-2 px-5 py-2 bg-primary text-on-primary rounded-lg text-sm font-semibold disabled:opacity-50 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{sending ? <Loader2 size={18} strokeWidth={2} className="motion-safe:animate-spin"/> : <Send size={18} strokeWidth={2}/>}{sending ? t('COPY_SENDING_3') : t('COPY_SEND_CAMPAIGN')}</button></div></div>
    {showPreview && <ManagerCommunicationsBulkMessageModal data-testid="manager_communications-managercommunicationscomposer-managercommunicationsbulkmessagemodal-1" whatsappUrlBuilder={(phone, message) => `${ManagerCommunicationsUrlConfig.INTEGRATIONS.WHATSAPP_WEB_BASE}/${phone}?text=${encodeURIComponent(message)}`} open={showPreview} onClose={() => setShowPreview(false)} recipients={bulkRecipients} type={watchedChannel as CommChannel} defaultMessage={watchedMessage} />}
  </div>;
}
