// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const planTierSchema = z.union([z.literal("starter"), z.literal("growth"), z.literal("pro"), z.literal("enterprise")]);

export const invoiceStatusSchema = z.union([z.literal("paid"), z.literal("pending"), z.literal("failed"), z.literal("refunded")]);

export const paymentMethodTypeSchema = z.union([z.literal("card"), z.literal("upi"), z.literal("netbanking")]);

export const currentSubscriptionSchema = z.object({
    planId: z.string(),
    planName: z.string(),
    tier: planTierSchema,
    monthlyPrice: z.number(),
    annualPrice: z.number(),
    billingCycle: z.union([z.literal("monthly"), z.literal("annual")]),
    status: z.union([z.literal("active"), z.literal("cancelled"), z.literal("past_due")]),
    currentPeriodStart: z.string(),
    currentPeriodEnd: z.string(),
    nextBillingDate: z.string(),
    autoRenew: z.boolean(),
    gymCount: z.number(),
    memberLimit: z.number(),
    staffLimit: z.number(),
    storageGb: z.number()
});

export const saaSPlanSchema = z.object({
    id: z.string(),
    name: z.string(),
    tier: planTierSchema,
    monthlyPrice: z.number(),
    annualPrice: z.number(),
    gymLimit: z.number(),
    memberLimit: z.number(),
    staffLimit: z.number(),
    storageGb: z.number(),
    features: z.array(z.string()),
    isPopular: z.boolean(),
    isCurrent: z.boolean()
});

export const invoiceSchema = z.object({
    id: z.string(),
    invoiceNo: z.string(),
    date: z.string(),
    dueDate: z.string(),
    amount: z.number(),
    status: invoiceStatusSchema,
    planName: z.string(),
    billingCycle: z.union([z.literal("monthly"), z.literal("annual")]),
    pdfUrl: z.string(),
    taxAmount: z.number().optional(),
    gstNumber: z.string().optional()
});

export const paymentMethodSchema = z.object({
    id: z.string(),
    type: paymentMethodTypeSchema,
    last4: z.string().optional(),
    brand: z.string().optional(),
    upiId: z.string().optional(),
    bankName: z.string().optional(),
    expiryMonth: z.number().optional(),
    expiryYear: z.number().optional(),
    isDefault: z.boolean()
});

export const subscriptionKpiDataSchema = z.object({
    currentPlan: z.string(),
    monthlySpend: z.number(),
    totalInvoices: z.number(),
    nextBillingAmount: z.number(),
    daysUntilRenewal: z.number(),
    savedWithAnnual: z.number()
});
