// RESPONSIBILITY: Owns the complete MSW transport contract for the Admin module.
// DATA FLOW: Admin API client → MSW handler → AdminMockFixtures → TanStack Query/UI
import { http, HttpResponse } from 'msw';
import type { AuditKPIData, AuditLog } from '@/app/admin/audit_logs/audit_types/audit_types';
import type { BlacklistedMember, BlacklistKPIData } from '@/app/admin/blacklist/blacklist_types/blacklist_types';
import type { Coupon, CouponsKPIData } from '@/app/admin/coupons/coupons_types/coupons_types';
import type { ExportJob, DataExportKPIData } from '@/app/admin/data-export/data_export_types/data_export_types';
import {
  MOCK_ANNOUNCEMENTS,
  MOCK_ANNOUNCEMENT_KPI,
  MOCK_ADMIN_ATTENDANCE_SUMMARY,
  MOCK_ADMIN_ATTENDANCE_RECORDS,
  MOCK_ADMIN_ATTENDANCE_TREND,
  MOCK_ADMIN_DASHBOARD,
  MOCK_ADMIN_FINANCE_SUMMARY,
  MOCK_ADMIN_PAYMENTS,
  MOCK_ADMIN_BRANCH_PNL,
  MOCK_ADMIN_HR_SUMMARY,
  MOCK_ADMIN_STAFF,
  MOCK_ADMIN_PAYROLLS,
  MOCK_ADMIN_STAFF_PERFORMANCE,
  MOCK_ADMIN_LEDGER,
  MOCK_ADMIN_MEMBERS_SUMMARY,
  MOCK_ADMIN_MEMBERS,
  MOCK_ADMIN_PLANS,
  MOCK_ADMIN_PLAN_REVENUE,
  MOCK_ADMIN_PROFILE,
  MOCK_ADMIN_REPORTS,
  MOCK_ADMIN_SALES_OVERVIEW,
  MOCK_ADMIN_MEMBERSHIP_REPORT,
  MOCK_ADMIN_MEMBERSHIP_TOTALS,
  MOCK_ADMIN_PENDING_PAYMENTS,
  MOCK_ADMIN_ALL_MEMBERSHIPS,
  MOCK_ADMIN_SETTINGS,
  MOCK_ADMIN_USAGE_DATA,
} from '@/app/admin/admin_mocks/fixtures/AdminMockFixtures';

const ok = <T>(data: T, message = 'Success') =>
  HttpResponse.json({ success: true, message, data, meta: { total: Array.isArray(data) ? data.length : 1, page: 1, limit: 50, totalPages: 1 } });

export const adminHandlers = [
  http.get('*/admin/branches/fetchBranches', () => ok([{ id: 'b1', name: 'Andheri East', city: 'Mumbai', activeMembers: 420, revenue: 185000, trend: 'up' }, { id: 'b2', name: 'Bandra West', city: 'Mumbai', activeMembers: 340, revenue: 142000, trend: 'up' }, { id: 'b3', name: 'Powai', city: 'Mumbai', activeMembers: 220, revenue: 98000, trend: 'flat' }, { id: 'b4', name: 'Thane', city: 'Thane', activeMembers: 180, revenue: 60000, trend: 'down' }])),
  http.get('*/admin/usage/fetchMyUsage', () => ok(MOCK_ADMIN_USAGE_DATA)),
  http.get('/api/admin/announcements/fetchAnnouncements', () => ok(MOCK_ANNOUNCEMENTS)),
  http.get('/api/admin/announcements/fetchKPIs', () => ok(MOCK_ANNOUNCEMENT_KPI)),
  http.post('/api/admin/announcements/createAnnouncement', () => ok(MOCK_ANNOUNCEMENTS[0]!, 'Announcement created')),
  http.post('/api/admin/announcements/updateAnnouncement', () => ok(MOCK_ANNOUNCEMENTS[0]!, 'Announcement updated')),
  http.delete('/api/admin/announcements/deleteAnnouncement', () => ok(null, 'Announcement deleted')),
  http.post('/api/admin/announcements/togglePin', () => ok(MOCK_ANNOUNCEMENTS[0]!, 'Announcement updated')),
  http.get('*/admin/audit_logs/fetchLogs', () => ok<AuditLog[]>([
    { id: 'al1', timestamp: '2026-09-16T09:00:00Z', action: 'Payment recorded', user: 'Admin', branchId: 'b1', details: 'Membership payment recorded for Rahul Sharma', severity: 'medium', ip: '10.0.0.10', module: 'Finance', userAgent: 'Chrome' },
    { id: 'al2', timestamp: '2026-09-15T13:30:00Z', action: 'Member updated', user: 'Manager', branchId: 'b2', details: 'Updated contact details', severity: 'low', ip: '10.0.0.11', module: 'Members' },
    { id: 'al3', timestamp: '2026-09-15T11:15:00Z', action: 'Permission change', user: 'Admin', branchId: 'b4', details: 'Disabled reports export for manager role', severity: 'high', ip: '10.0.0.12', module: 'Settings' },
  ])),
  http.get('*/admin/audit_logs/fetchKPIs', () => ok<AuditKPIData>({ totalEvents: 1284, highSeverity: 8, mediumSeverity: 64, lowSeverity: 1212, eventsToday: 37, uniqueUsers: 19 })),
  http.get('/api/admin/blacklist/fetchBlacklist', () => ok<BlacklistedMember[]>([
    { id: 'bl1', memberId: 'm1', memberName: 'Rahul Sharma', memberPhone: '98****1234', memberEmail: 'r***@example.com', reason: 'Repeated policy violations', blacklistedBy: 'Admin', blacklistedAt: '2026-09-10T09:00:00Z', scope: 'global', assignedGyms: [], assignedGymNames: [], isActive: true, history: [] },
    { id: 'bl2', memberId: 'm9', memberName: 'Arjun Reddy', memberPhone: '97****6789', memberEmail: 'a***@example.com', reason: 'Branch-specific incident', blacklistedBy: 'Manager', blacklistedAt: '2026-09-08T10:00:00Z', scope: 'specific', assignedGyms: ['b4'], assignedGymNames: ['Thane'], isActive: true, history: [] },
  ])),
  http.get('/api/admin/blacklist/fetchKPIs', () => ok<BlacklistKPIData>({ totalBlacklisted: 2, globalBans: 1, gymSpecificBans: 1, addedThisMonth: 2 })),
  http.post('/api/admin/blacklist/addToBlacklist', () => ok(null, 'Member added to blacklist')),
  http.delete('/api/admin/blacklist/removeFromBlacklist', () => ok(null, 'Member removed from blacklist')),
  http.post('/api/admin/blacklist/toggleBlacklist', () => ok(null, 'Blacklist status updated')),
  http.post('/api/admin/blacklist/propagateToAllBranches', () => ok(null, 'Blacklist propagated')),
  http.get('/api/admin/coupons/fetchCoupons', () => ok<Coupon[]>([
    { id: 'c1', code: 'WELCOME20', description: 'New member discount', type: 'percentage', value: 20, minOrderAmount: 2000, maxDiscount: 1000, usageLimit: 100, usedCount: 42, assignedGyms: ['b1', 'b2'], assignedGymNames: ['Andheri East', 'Bandra West'], validFrom: '2026-09-01', validUntil: '2026-12-31', status: 'active', createdAt: '2026-08-30' },
    { id: 'c2', code: 'FLAT500', description: 'Flat 500 discount', type: 'flat', value: 500, minOrderAmount: 5000, maxDiscount: 500, usageLimit: 50, usedCount: 23, assignedGyms: ['b3'], assignedGymNames: ['Powai'], validFrom: '2026-09-01', validUntil: '2026-11-30', status: 'active', createdAt: '2026-08-28' },
    { id: 'c3', code: 'SUMMER30', description: 'Summer sale discount', type: 'percentage', value: 30, minOrderAmount: 3000, maxDiscount: 1500, usageLimit: 200, usedCount: 200, assignedGyms: [], assignedGymNames: [], validFrom: '2026-04-01', validUntil: '2026-06-30', status: 'expired', createdAt: '2026-03-20' },
  ])),
  http.post('/api/admin/coupons/createCoupon', () => ok(null, 'Coupon created')),
  http.post('/api/admin/coupons/updateCoupon', () => ok(null, 'Coupon updated')),
  http.delete('/api/admin/coupons/deleteCoupon', () => ok(null, 'Coupon deleted')),
  http.post('/api/admin/coupons/toggleCoupon', () => ok(null, 'Coupon status updated')),
  http.get('/api/admin/dashboard/fetchDashboardStats', () => ok(MOCK_ADMIN_DASHBOARD)),
  http.get('*/admin/data-export/fetchJobs', () => ok<ExportJob[]>([
    { id: 'exp1', dataType: 'members', format: 'csv', gymIds: ['b1'], gymNames: ['Andheri East'], dateFrom: '2026-09-01', dateTo: '2026-09-15', status: 'completed', rowCount: 1250, fileSizeKb: 412, createdAt: '2026-09-15T08:00:00Z', completedAt: '2026-09-15T08:02:00Z', createdBy: 'Admin' },
    { id: 'exp2', dataType: 'payments', format: 'excel', gymIds: ['b1', 'b2'], gymNames: ['Andheri East', 'Bandra West'], dateFrom: '2026-09-01', dateTo: '2026-09-16', status: 'processing', rowCount: 420, createdAt: '2026-09-16T08:00:00Z', createdBy: 'Admin' },
  ])),
  http.get('*/admin/data-export/fetchKPIs', () => ok<DataExportKPIData>({ totalExports: 24, totalRowsExported: 18450, lastExportDate: '2026-09-15', pendingJobs: 2 })),
  http.post('*/admin/data-export/createExport', () => ok({ id: 'exp3', status: 'PROCESSING', fileName: 'new-export.csv' }, 'Export started')),
  http.delete('*/admin/data-export/deleteJob', () => ok(null, 'Export deleted')),
  http.get('*/admin/finance/payments/fetchPayments', () => ok({ payments: MOCK_ADMIN_PAYMENTS, total: MOCK_ADMIN_PAYMENTS.length })),
  http.post('*/admin/finance/payments/createPayment', () => ok(MOCK_ADMIN_PAYMENTS[0]!, 'Payment recorded')),
  http.get('*/admin/finance/summary', () => ok(MOCK_ADMIN_FINANCE_SUMMARY)),
  http.get('*/admin/finance/pnl/comparison', () => ok(MOCK_ADMIN_BRANCH_PNL)),
  http.get('*/admin/finance/payments/fetchExpenses', () => ok([{ id: 'e1', category: 'Rent', amount: 85000, branch: 'Andheri East', date: '2026-09-01', status: 'approved' }, { id: 'e2', category: 'Utilities', amount: 21000, branch: 'Bandra West', date: '2026-09-05', status: 'approved' }])),
  http.get('*/admin/gym-health-alerts/fetchAlerts', () => ok([{ id: 'a1', title: 'Low Attendance', branchName: 'Thane', severity: 'high', value: 42, threshold: 60, createdAt: '2026-09-16T07:00:00Z', resolved: false }, { id: 'a2', title: 'Low Stock', branchName: 'Powai', severity: 'medium', value: 8, threshold: 10, createdAt: '2026-09-15T10:00:00Z', resolved: false }])),
  http.get('*/admin/gym-health-alerts/fetchKPIs', () => ok({ totalAlerts: 7, criticalAlerts: 1, unresolvedAlerts: 4, resolvedToday: 3 })),
  http.post('*/admin/gym-health-alerts/resolveAlert', () => ok(null, 'Alert resolved')),
  http.post('*/admin/gym-health-alerts/dismissAlert', () => ok(null, 'Alert dismissed')),
  http.get('/api/admin/payouts/fetchPayouts', () => ok([{ id: 'po1', recipient: 'Ravi Trainer', amount: 24000, status: 'PENDING', dueDate: '2026-09-18', branch: 'Andheri East' }, { id: 'po2', recipient: 'Sunita Coach', amount: 18000, status: 'PAID', dueDate: '2026-09-10', branch: 'Bandra West' }])),
  http.get('/api/admin/payouts/fetchPnL', () => ok({ revenue: 920000, payouts: 270000, profit: 650000 })),
  http.get('/api/admin/payouts/fetchKPIs', () => ok({ pendingAmount: 24000, paidThisMonth: 310000, payoutCount: 18 })),
  http.post('/api/admin/payouts/markPaid', () => ok(null, 'Payout marked paid')),
  http.get('/api/admin/permissions/fetchPermissions', () => ok({ roleDefaults: [{ role: 'manager', permissions: { 'members.view': true, 'members.create': true, 'members.edit': true, 'finance.view': true, 'reports.view': true } }, { role: 'trainer', permissions: { 'members.view': true, 'attendance.view': true, 'attendance.mark': true } }], gymOverrides: [{ gymId: 'b4', gymName: 'Thane', role: 'manager', overrides: { 'reports.export': false } }] })),
  http.post('/api/admin/permissions/updateRolePermissions', () => ok(null, 'Permissions updated')),
  http.post('/api/admin/permissions/updateGymOverride', () => ok(null, 'Gym override updated')),
  http.get('*/admin/plans/fetchAllPlans', () => ok(MOCK_ADMIN_PLANS)),
  http.get('*/admin/plans/fetchPlanById', () => ok(MOCK_ADMIN_PLANS[0]!)),
  http.post('*/admin/plans/createPlan', () => ok(MOCK_ADMIN_PLANS[0]!, 'Plan created')),
  http.post('*/admin/plans/updatePlan', () => ok(MOCK_ADMIN_PLANS[0]!, 'Plan updated')),
  http.delete('*/admin/plans/deletePlan', () => ok(null, 'Plan deleted')),
  http.get('*/admin/plans/fetchPlanRevenue', () => ok(MOCK_ADMIN_PLAN_REVENUE)),
  http.get('/api/admin/reports/fetchReportData', () => ok(MOCK_ADMIN_REPORTS)),
  http.post('/api/admin/reports/exportReport', () => ok({ fileName: 'admin-report.csv', downloadUrl: '/api/admin/reports/download/admin-report.csv' }, 'Report export started')),
  http.get('/api/admin/sales/fetchOverview', () => ok(MOCK_ADMIN_SALES_OVERVIEW)),
  http.get('/api/admin/sales/fetchMembershipReport', () => ok(MOCK_ADMIN_MEMBERSHIP_REPORT)),
  http.get('/api/admin/sales/fetchPendingPayments', () => ok(MOCK_ADMIN_PENDING_PAYMENTS)),
  http.get('/api/admin/sales/fetchAllMemberships', () => ok(MOCK_ADMIN_ALL_MEMBERSHIPS)),
  http.get('*/admin/settings/fetchSettings', () => ok(MOCK_ADMIN_SETTINGS)),
  http.post('*/admin/settings/updateSettings', () => ok(MOCK_ADMIN_SETTINGS, 'Settings updated')),
  http.get('/api/admin/subscriptions/fetchSubscription', () => ok({ plan: 'Growth', status: 'active', renewalDate: '2026-10-15', monthlyPrice: 4999, autoRenew: true })),
  http.get('/api/admin/subscriptions/fetchPlans', () => ok(MOCK_ADMIN_PLANS)),
  http.get('/api/admin/subscriptions/fetchInvoices', () => ok([{ id: 'inv1', invoiceNo: 'INV-2026-0901', amount: 4999, status: 'PAID', issuedAt: '2026-09-01' }, { id: 'inv2', invoiceNo: 'INV-2026-0801', amount: 4999, status: 'PAID', issuedAt: '2026-08-01' }])),
  http.get('/api/admin/subscriptions/fetchPaymentMethods', () => ok([{ id: 'pm1', type: 'UPI', label: 'smartgym@upi', isDefault: true } , { id: 'pm2', type: 'Card', label: '**** 4242', isDefault: false }])),
  http.get('/api/admin/subscriptions/fetchKPIs', () => ok({ monthlySpend: 4999, nextBillingAmount: 4999, invoicesCount: 12 })),
  http.post('/api/admin/subscriptions/upgradePlan', () => ok(null, 'Plan upgrade requested')),
  http.post('/api/admin/subscriptions/toggleAutoRenew', () => ok(null, 'Auto-renewal updated')),
  http.post('/api/admin/subscriptions/setDefaultPaymentMethod', () => ok(null, 'Default payment method updated')),
  http.delete('/api/admin/subscriptions/removePaymentMethod', () => ok(null, 'Payment method removed')),
  http.get('/api/admin/adminProfile/fetchProfile', () => ok(MOCK_ADMIN_PROFILE)),
  http.post('/api/admin/adminProfile/updateProfile', () => ok(MOCK_ADMIN_PROFILE, 'Profile updated')),
  http.post('/api/admin/adminProfile/updatePassword', () => ok(null, 'Password updated')),

  // --- Members ---
  http.get('/api/admin/members', () => ok(MOCK_ADMIN_MEMBERS)),
  http.get('/api/admin/members/summary', () => ok(MOCK_ADMIN_MEMBERS_SUMMARY)),
  http.get('/api/admin/members/list', () => ok(MOCK_ADMIN_MEMBERS)),
  http.post('/api/admin/members', () => ok(MOCK_ADMIN_MEMBERS[0])),
  http.patch('/api/admin/members/:id', () => ok(MOCK_ADMIN_MEMBERS[0])),
  http.delete('/api/admin/members/:id', () => ok(null)),
  http.post('/api/admin/members/:id/renew', () => ok(null)),

  // --- Attendance ---
  http.get('/api/admin/attendance', () => ok(MOCK_ADMIN_ATTENDANCE_RECORDS)),
  http.get('/api/admin/attendance/summary', () => ok(MOCK_ADMIN_ATTENDANCE_SUMMARY)),
  http.get('/api/admin/attendance/trend', () => ok(MOCK_ADMIN_ATTENDANCE_TREND)),

  // --- HR ---
  http.get('*/admin/hr/staff', () => ok({ staff: MOCK_ADMIN_STAFF, total: MOCK_ADMIN_STAFF.length })),
  http.get('*/admin/hr/staff/:id', () => ok(MOCK_ADMIN_STAFF[0])),
  http.post('*/admin/hr/staff', () => ok(MOCK_ADMIN_STAFF[0])),
  http.patch('*/admin/hr/staff/:id', () => ok(MOCK_ADMIN_STAFF[0])),
  http.delete('*/admin/hr/staff/:id', () => ok(null)),
  http.post('*/admin/hr/staff/bulk-deactivate', () => ok(null)),
  http.get('*/admin/hr/payrolls', () => ok({ payrolls: MOCK_ADMIN_PAYROLLS, total: MOCK_ADMIN_PAYROLLS.length })),
  http.post('*/admin/hr/payrolls', () => ok(MOCK_ADMIN_PAYROLLS[0])),
  http.patch('*/admin/hr/payrolls/:id', () => ok(MOCK_ADMIN_PAYROLLS[0])),
  http.patch('*/admin/hr/payrolls/:id/status', () => ok(MOCK_ADMIN_PAYROLLS[0])),
  http.get('*/admin/hr/summary', () => ok(MOCK_ADMIN_HR_SUMMARY)),
  http.get('*/admin/hr/staff/:id/ledger', () => ok(MOCK_ADMIN_LEDGER)),
  http.post('*/admin/hr/advances', () => ok(null)),
  http.post('*/admin/hr/dues/pay', () => ok(null)),
  http.get('*/admin/hr/performance', () => ok(MOCK_ADMIN_STAFF_PERFORMANCE)),
];
