// Generated by ts-to-zod
import { z } from "zod";

import { z, z, z, z, z, z, z } from "zod";

export const gymProfileTypeSchema = z.literal(z.infer);

export const notificationsSettingsTypeSchema = z.literal(z.infer);

export const appIntegrationSettingsTypeSchema = z.literal(z.infer);

export const gstTaxSettingsTypeSchema = z.literal(z.infer);

export const paymentGatewaySettingsTypeSchema = z.literal(z.infer);

export const generalSettingsTypeSchema = z.literal(z.infer);

export const adminSettingsResponseSchema = z.literal(z.infer);
