import type { Attendance, AttendanceStatsResponse } from '@/app/manager/attendance/attendance_types/ManagerAttendanceTypes';

export const MOCK_ATTENDANCE_STATS: AttendanceStatsResponse = {
  totalCheckIns: 120,
  memberCheckIns: 105,
  staffCheckIns: 15,
};

export const MOCK_ATTENDANCE_RECORDS: Attendance[] = [
  {
    id: '1',
    memberId: 1,
    date: new Date().toISOString().split('T')[0] || '',
    checkIn: '06:00',
    checkOut: '07:30',
    type: 'MEMBER',
    status: 'Present',
    member: { name: 'Rahul Sharma' },
    checkInMethod: 'Biometric',
    durationMinutes: 90,
  },
  {
    id: '2',
    memberId: 2,
    date: new Date().toISOString().split('T')[0] || '',
    checkIn: '06:15',
    checkOut: '07:45',
    type: 'MEMBER',
    status: 'Present',
    member: { name: 'Priya Singh' },
    checkInMethod: 'QR',
    durationMinutes: 90,
  },
  {
    id: '3',
    staffId: 1,
    date: new Date().toISOString().split('T')[0] || '',
    checkIn: '05:30',
    checkOut: '14:30',
    type: 'STAFF',
    status: 'Present',
    staff: { name: 'Amit Kumar' },
    checkInMethod: 'Biometric',
    durationMinutes: 540,
  },
  {
    id: '4',
    memberId: 3,
    date: new Date().toISOString().split('T')[0] || '',
    checkIn: '07:00',
    type: 'MEMBER',
    status: 'Present',
    member: { name: 'Neha Gupta' },
    checkInMethod: 'Manual',
  },
  {
    id: '5',
    memberId: 4,
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0] || '',
    checkIn: '17:00',
    checkOut: '19:00',
    type: 'MEMBER',
    status: 'Present',
    member: { name: 'Vikram Singh' },
    checkInMethod: 'QR',
    durationMinutes: 120,
  },
];
