// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const recentMemberSchema = z.object({
    id: z.string(),
    name: z.string(),
    plan: z.union([z.string(), z.object({
            name: z.string()
        })]),
    status: z.string(),
    joinDate: z.string(),
    paidAmount: z.number()
});

export const recentPaymentSchema = z.object({
    id: z.string(),
    invoiceNo: z.string(),
    amount: z.number(),
    method: z.string(),
    paidAt: z.string(),
    member: z.object({
        name: z.string()
    })
});

export const pendingPaymentSchema = z.object({
    id: z.string(),
    name: z.string(),
    pendingAmount: z.number(),
    expiryDate: z.string()
});

export const branchPerformanceSchema = z.object({
    id: z.string(),
    name: z.string(),
    revenue: z.number(),
    activeMembers: z.number(),
    trend: z.union([z.literal("up"), z.literal("down"), z.literal("flat")])
});

export const systemAlertSchema = z.object({
    id: z.string(),
    message: z.string(),
    severity: z.union([z.literal("high"), z.literal("medium"), z.literal("low")]),
    date: z.string()
});

export const dashboardStatsSchema = z.object({
    totalMembers: z.number(),
    activeMembers: z.number(),
    newMembersThisMonth: z.number(),
    totalRevenue: z.number(),
    monthlyRevenue: z.number(),
    netProfit: z.number(),
    totalExpenses: z.number(),
    pendingPayments: z.number(),
    totalStaff: z.number(),
    activeStaff: z.number(),
    totalProducts: z.number(),
    lowStockCount: z.number(),
    totalInquiries: z.number(),
    newInquiries: z.number(),
    cancellationRate: z.number(),
    retentionRate: z.number(),
    arpm: z.number(),
    memberGrowth: z.array(z.object({
        month: z.string(),
        count: z.number()
    })),
    revenueTrend: z.array(z.object({
        month: z.string(),
        revenue: z.number(),
        profit: z.number()
    })),
    membersByPlan: z.array(z.object({
        plan: z.string(),
        count: z.number()
    })),
    membersByStatus: z.object({
        active: z.number(),
        pending: z.number(),
        expired: z.number()
    }),
    branchLeaderboard: z.array(branchPerformanceSchema),
    systemAlerts: z.array(systemAlertSchema),
    todayAttendance: z.number().optional(),
    expiringThisWeek: z.number().optional(),
    totalInquiriesOpen: z.number().optional(),
    avgAttendance: z.number().optional(),
    renewalsPending: z.number().optional()
});
