// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const auditSeveritySchema = z.union([z.literal("high"), z.literal("medium"), z.literal("low")]);

export const auditModuleSchema = z.union([z.literal("Finance"), z.literal("Members"), z.literal("HR"), z.literal("Plans"), z.literal("Auth"), z.literal("Settings"), z.literal("Branches"), z.literal("Store"), z.literal("Attendance")]);

export const auditLogSchema = z.object({
    id: z.string(),
    timestamp: z.string(),
    action: z.string(),
    user: z.string(),
    branchId: z.string(),
    details: z.string(),
    severity: auditSeveritySchema,
    ip: z.string(),
    module: auditModuleSchema,
    userAgent: z.string().optional(),
    affectedRecordId: z.string().optional()
});

export const auditKpiDataSchema = z.object({
    totalEvents: z.number(),
    highSeverity: z.number(),
    mediumSeverity: z.number(),
    lowSeverity: z.number(),
    eventsToday: z.number(),
    uniqueUsers: z.number()
});

export const auditFiltersSchema = z.object({
    search: z.string(),
    severity: z.string(),
    module: z.string(),
    branchId: z.string(),
    dateFrom: z.string(),
    dateTo: z.string()
});
