// RESPONSIBILITY: Central registry of runtime event names used for cross-feature decoupling.
// FLOW: Feature service -> EventRegistry constant -> event transport/consumer.
export const EVENT_REGISTRY = {
  SUPERADMIN_GYM_CREATED: 'SUPERADMIN.GYM.CREATED',
  SUPERADMIN_GYM_STATUS_CHANGED: 'SUPERADMIN.GYM.STATUS_CHANGED',
  SUPERADMIN_MESSAGE_SENT: 'SUPERADMIN.MESSAGE.SENT',
  SUPERADMIN_BROADCAST_CREATED: 'SUPERADMIN.BROADCAST.CREATED',
  SUPERADMIN_INVOICE_PAID: 'SUPERADMIN.INVOICE.PAID',
  SUPERADMIN_JOB_FAILED: 'SUPERADMIN.JOB.FAILED',
  SUPERADMIN_TENANT_PROVISIONED: 'SUPERADMIN.TENANT.PROVISIONED',
  SUPERADMIN_EXPORT_COMPLETED: 'SUPERADMIN.EXPORT.COMPLETED',
} as const;
export type EventName = (typeof EVENT_REGISTRY)[keyof typeof EVENT_REGISTRY];
