// Generated by ts-to-zod
import { z } from "zod";

export const adminProfileDataSchema = z.object({
    id: z.string(),
    name: z.string(),
    email: z.string(),
    phone: z.string(),
    role: z.string(),
    branchName: z.string(),
    joinedAt: z.string(),
    avatarInitial: z.string()
});

export const updateAdminProfilePayloadSchema = z.object({
    name: z.string(),
    phone: z.string()
});

export const updateAdminPasswordPayloadSchema = z.object({
    currentPassword: z.string(),
    newPassword: z.string(),
    confirmPassword: z.string()
});


export const profileTabSchema = z.union([z.literal("personal"), z.literal("security")]);
