// RESPONSIBILITY: Stores append-only domain events used to preserve immutable analytics history.
// FLOW: Mutation transaction → CoreImmutableDomainEventRepository → immutable_domain_events table → analytics/event consumers.

import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';


/**
 * Intent: Defines the CoreImmutableDomainEventEntity boundary for the backend core architecture.
 * Edge Cases: Preserve tenant scope, validation, authorization, nullability, transactions, and canonical errors when changing this construct.
 * Side Effects: Preserve the owning construct’s existing persistence, cache, event, and audit behavior without introducing cross-module state changes.
 * AI Note: Keep this construct isolated from unrelated modules and preserve frozen contracts; never bypass repository/domain boundaries.
 */
@Entity('immutable_domain_events')
@Index('IDX_immutable_domain_events_aggregate', ['aggregateType', 'aggregateId'])
@Index('IDX_immutable_domain_events_name_occurred', ['eventName', 'occurredAt'])
export class CoreImmutableDomainEventEntity {
  /** Intent: Identifies one immutable domain event. Edge Cases: Generated by PostgreSQL and never client supplied. Side-Effects: None. AI Note: Treat this identifier as an append-only event identity. */
  @PrimaryGeneratedColumn('uuid', { name: 'id' }) id!: string;

  /** Intent: Stores the canonical DOMAIN.ENTITY.ACTION event name. Edge Cases: Only registry-approved names are accepted. Side-Effects: Drives downstream event routing. AI Note: Never invent alternate event spellings. */
  @Column({ name: 'event_name', type: 'varchar', length: 160 }) eventName!: string;

  /** Intent: Identifies the aggregate class that changed. Edge Cases: Must remain stable for replay. Side-Effects: Used by analytics grouping. AI Note: Do not derive aggregate type from mutable display labels. */
  @Column({ name: 'aggregate_type', type: 'varchar', length: 120 }) aggregateType!: string;

  /** Intent: Identifies the specific aggregate instance that produced the event. Edge Cases: Must be a valid UUID. Side-Effects: Enables deterministic event lookup. AI Note: Never reuse IDs across tenants. */
  @Column({ name: 'aggregate_id', type: 'uuid' }) aggregateId!: string;

  /** Intent: Identifies the actor from the trusted request context. Edge Cases: System actions use the configured system actor or NULL. Side-Effects: Supports audit attribution. AI Note: Never trust actor IDs from request bodies. */
  @Column({ name: 'actor_id', type: 'uuid', nullable: true }) actorId!: string | null;

  /** Intent: Captures the event occurrence time rather than row-insert time. Edge Cases: Must be timezone-aware. Side-Effects: Supports time-series analytics. AI Note: Keep this separate from createdAt. */
  @Column({ name: 'occurred_at', type: 'timestamptz' }) occurredAt!: Date;

  /** Intent: Captures the immutable event payload required for replay/analytics. Edge Cases: Payload must be JSON-serializable and contain no secrets. Side-Effects: Persists history even when current entities later change. AI Note: Prefer stable domain fields over ORM internals. */
  @Column({ type: 'jsonb' }) payload!: Record<string, unknown>;

  /** Intent: Pins the payload schema version. Edge Cases: Increment only for a documented breaking shape change. Side-Effects: Consumers can branch deterministically. AI Note: Never silently repurpose an existing version. */
  @Column({ name: 'event_version', type: 'integer', default: 1 }) eventVersion!: number;

  /** Intent: Records when the immutable event entered the tenant event log. Edge Cases: Database generated. Side-Effects: None. AI Note: This is not the business occurrence timestamp. */
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' }) createdAt!: Date;
}
