// Generated by ts-to-zod
import { z } from "zod";

export const performancePeriodSchema = z.union([z.literal("THIS_MONTH"), z.literal("LAST_MONTH"), z.literal("THIS_QUARTER")]);

export const performanceSortKeySchema = z.union([z.literal("name"), z.literal("role"), z.literal("sessionsTaken"), z.literal("membersAdded"), z.literal("attendancePct"), z.literal("rating")]);

export const performanceSortDirectionSchema = z.union([z.literal("asc"), z.literal("desc")]);

export const staffPerformanceRecordSchema = z.object({
    id: z.string(),
    name: z.string(),
    role: z.string(),
    branchName: z.string(),
    sessionsTaken: z.number(),
    membersAdded: z.number(),
    attendancePct: z.number(),
    rating: z.number(),
    status: z.union([z.literal("EXCELLENT"), z.literal("AVERAGE"), z.literal("POOR")])
});

export const performanceAggregatesSchema = z.object({
    totalSessions: z.number(),
    totalMembersAdded: z.number(),
    avgAttendance: z.number(),
    avgRating: z.number(),
    topPerformersCount: z.number(),
    lowPerformersCount: z.number()
});
