// RESPONSIBILITY: Owns Zod runtime validation schemas for the Admin HR module.
import { z } from 'zod';
// Generated by ts-to-zod

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const staffSchema = z.object({
    id: z.string(),
    employeeId: z.string().optional(),
    name: z.string(),
    email: z.string(),
    phone: z.string(),
    role: z.string(),
    salary: z.number(),
    branch: z.string(),
    gender: z.string(),
    address: z.string().optional(),
    aadhaar: z.string().optional(),
    upiId: z.string().optional(),
    bankAccountNumber: z.string().optional(),
    advanceSalary: z.number().optional(),
    joinDate: z.string(),
    joiningDate: z.string().optional(),
    isActive: z.boolean(),
    salaryType: z.union([z.literal("Monthly"), z.literal("Daily")]).optional(),
    paymentCycle: z.string().optional(),
    currentDue: z.number().optional(),
    assignedBranches: z.array(z.string()).optional(),
    primaryBranchId: z.string().optional(),
    emergencyContactName: z.string().optional(),
    emergencyContactPhone: z.string().optional(),
    department: z.string().optional(),
    certifications: z.array(z.string()).optional(),
    contractType: z.string().optional(),
    terminationDate: z.string().optional()
});

export const payrollSchema = z.object({
    id: z.string(),
    staffId: z.string(),
    month: z.string(),
    amount: z.number(),
    paidAmount: z.number(),
    pendingAmount: z.number(),
    status: z.string(),
    paidAt: z.string().optional(),
    notes: z.string().optional(),
    staff: z.object({
        name: z.string(),
        role: z.string()
    }).optional()
});

export const hrSummarySchema = z.object({
    totalSalaryThisMonth: z.number(),
    totalSalaryPaid: z.number(),
    totalSalaryDue: z.number(),
    totalAdvanceGiven: z.number(),
    pendingPaymentsCount: z.number(),
    totalStaff: z.number(),
    activeStaff: z.number(),
    totalPayrollThisMonth: z.number(),
    paidCount: z.number(),
    pendingCount: z.number()
});

export const ledgerEntrySchema = z.object({
    id: z.string(),
    staffId: z.string(),
    date: z.string(),
    type: z.union([z.literal("Salary Generated"), z.literal("Salary Paid"), z.literal("Advance Given"), z.literal("Due Paid")]),
    credit: z.number(),
    debit: z.number(),
    balance: z.number(),
    notes: z.string().optional(),
    referenceNo: z.string().optional(),
    paymentMode: z.string().optional(),
    openingBalance: z.number().optional()
});

export const hrInitialDataSchema = z.object({
    staff: z.array(staffSchema),
    payrolls: z.array(payrollSchema),
    summary: hrSummarySchema.nullable()
});

export const staffFormSchema = z.object({
  name: z.string().min(2, "Name is required").regex(/^[A-Za-z\s]+$/, "Only alphabets allowed"),
  email: z.string().email("Invalid email address"),
  phone: z.string().regex(/^\d{10}$/, "Phone number must be exactly 10 digits"),
  role: z.string().min(2, "Role is required"),
  salary: z.number().min(0, "Salary must be positive"),
  branch: z.string().min(1, "Branch is required"),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER']),
  address: z.string().optional(),
  joinDate: z.string(),
  temporaryPassword: z.string().optional().refine(val => !val || val.length >= 8, {
    message: "Password must be at least 8 characters",
  }),
  isActive: z.boolean().default(true),
  aadhaar: z.string().regex(/^\d{12}$/, "Aadhaar must be exactly 12 digits").optional().or(z.literal('')),
  upiId: z.string().regex(/^[a-zA-Z0-9.\-_]{2,256}@[a-zA-Z]{2,64}$/, "Invalid UPI ID format").optional().or(z.literal('')),
  advanceSalary: z.number().min(0, "Advance cannot be negative").optional().default(0),
  assignedBranches: z.array(z.string()).optional(),
  primaryBranchId: z.string().optional()
});
