// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const roleTypeSchema = z.union([z.literal("manager"), z.literal("trainer")]);

export const permissionFeatureSchema = z.object({
    key: z.string(),
    label: z.string(),
    group: z.string(),
    description: z.string()
});

export const rolePermissionsSchema = z.object({
    role: roleTypeSchema,
    permissions: z.record(z.string(), z.boolean())
});

export const gymPermissionOverrideSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    role: roleTypeSchema,
    overrides: z.record(z.string(), z.boolean())
});

export const permissionsDataSchema = z.object({
    roleDefaults: z.array(rolePermissionsSchema),
    gymOverrides: z.array(gymPermissionOverrideSchema)
});
