"use client";
// RESPONSIBILITY: Renders the paginated, searchable, sortable Admin plan revenue table.

import { ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsUpDown, FileWarning } from 'lucide-react';
import { REVENUE_TABLE_HEADERS } from '@/app/admin/plans/plans_utils/AdminPlansRevenueConstants';
import type { PlanRevenueRecord, RevenueSortDirection, RevenueSortKey } from '@/app/admin/plans/plans_types/AdminPlansRevenueTypes';
import { formatCurrency, formatPercent1dp } from '@/lib/formatters';
import AdminPagination from '@/app/admin/admin_components/AdminShared/AdminPagination';
import type { ReactNode } from 'react';

interface AdminPlansRevenueTableProps { data: PlanRevenueRecord[]; sortKey: RevenueSortKey; sortDir: RevenueSortDirection; onSort: (key: RevenueSortKey) => void; currentPage: number; totalPages: number; totalItems: number; onPageChange: (page: number) => void; }
function SortIcon({ col, sortKey, sortDir }: { col: RevenueSortKey; sortKey: RevenueSortKey; sortDir: RevenueSortDirection }): ReactNode { if (col !== sortKey) return <ChevronsUpDown size={12} className="text-disabled"/>; return sortDir==='asc'?<ChevronUp size={12} className="text-primary"/>:<ChevronDown size={12} className="text-primary"/>; }
export default function AdminPlansRevenueTable({data,sortKey,sortDir,onSort,currentPage,totalPages,totalItems,onPageChange}:AdminPlansRevenueTableProps){return <div className="bg-card border border-border rounded-xl overflow-hidden flex flex-col"><div className="overflow-x-auto"><table data-admin-responsive-table className="w-full text-left border-collapse"><thead><tr className="bg-primary/5 border-b border-border">{REVENUE_TABLE_HEADERS.map(h=><th role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); event.currentTarget.click(); } }}  key={h.key} onClick={()=>h.sortable&&onSort(h.key as RevenueSortKey)} className={`px-4 py-3 text-xs font-semibold text-secondary uppercase tracking-wider select-none whitespace-nowrap ${h.sortable?'cursor-pointer':''}`} aria-sort={sortKey===h.key?(sortDir==='asc'?'ascending':'descending'):'none'}><div className="flex items-center gap-1.5">{h.label}{h.sortable&&<SortIcon col={h.key as RevenueSortKey} sortKey={sortKey} sortDir={sortDir}/>}</div></th>)}</tr></thead><tbody className="divide-y divide-border">{data.length===0?<tr><td colSpan={6} className="py-16 text-center"><FileWarning size={42} className="mx-auto text-disabled" strokeWidth={1}/><p className="mt-3 text-base font-semibold text-foreground">No revenue data found</p><p className="text-sm text-secondary mt-1">Try adjusting the period or search query.</p></td></tr>:data.map(row=><tr key={row.id} className="hover:bg-input motion-safe:transition-colors"><td className="px-4 py-3.5 text-sm font-semibold text-foreground">{row.planName}</td><td className="px-4 py-3.5"><span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold bg-primary/10 text-primary">{row.tier}</span></td><td className="px-4 py-3.5 text-sm font-medium text-foreground">{row.activeSubscriptions.toLocaleString('en-IN')}</td><td className="px-4 py-3.5 text-sm font-medium text-foreground">{row.newSignups>0?`+${row.newSignups}`:row.newSignups}</td><td className="px-4 py-3.5 text-sm font-medium text-foreground">{formatPercent1dp(row.renewalRate)}%</td><td className="px-4 py-3.5 text-sm font-black text-foreground">{formatCurrency(row.totalRevenue)}</td></tr>)}</tbody></table></div><div className="border-t border-border px-4 py-3"><AdminPagination currentPage={currentPage} totalPages={totalPages} totalItems={totalItems} itemsPerPage={10} onPageChange={onPageChange}/></div></div>}
