// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const blacklistScopeSchema = z.union([z.literal("global"), z.literal("specific")]);

export const blacklistedMemberSchema = z.object({
    id: z.string(),
    memberId: z.string(),
    memberName: z.string(),
    memberPhone: z.string(),
    memberEmail: z.string(),
    reason: z.string(),
    blacklistedBy: z.string(),
    blacklistedAt: z.string(),
    scope: blacklistScopeSchema,
    assignedGyms: z.array(z.string()),
    assignedGymNames: z.array(z.string()),
    isActive: z.boolean(),
    history: z.array(z.object({
        action: z.string(),
        actor: z.string(),
        timestamp: z.string(),
        note: z.string()
    })).optional()
});

export const blacklistFormValuesSchema = z.object({
    memberId: z.string(),
    memberName: z.string(),
    memberPhone: z.string(),
    memberEmail: z.string(),
    reason: z.string(),
    scope: blacklistScopeSchema,
    assignedGyms: z.array(z.string())
});

export const blacklistKpiDataSchema = z.object({
    totalBlacklisted: z.number(),
    globalBans: z.number(),
    gymSpecificBans: z.number(),
    addedThisMonth: z.number()
});
