// RESPONSIBILITY: Renders Superadmin roles and editable alert preferences; mutation orchestration stays inside this feature panel.
'use client';
import { useEffect, useState } from 'react';
import { Bell, Loader2, Save } from 'lucide-react';
import toast from 'react-hot-toast';
import { formatNumber } from '@/lib/formatters';
import SuperadminTeamAlertPreferencesEmptyState from '@/app/superadmin/team/team_components/SuperadminTeamAlertPreferencesEmptyState';
import SuperadminTeamRoleGroupsEmptyState from '@/app/superadmin/team/team_components/SuperadminTeamRoleGroupsEmptyState';
import Panel from '@/components/ui/Panel';
import { useSuperadminTeamAlertPreferences } from '@/app/superadmin/team/team_utils/useSuperadminTeamAlertPreferences';
import type { SuperadminTeamSectionProps } from '@/app/superadmin/team/team_types/SuperadminTeamTypes';
export default function SuperadminTeamRolesAndAlertPreferencesPanel({ data }: SuperadminTeamSectionProps) {
    const { savePreferences: persistPreferences, isSaving: saving, error: saveError } = useSuperadminTeamAlertPreferences(); const [draft,setDraft]=useState<Record<string,boolean>>({});
// EFFECT INTENT: synchronizes this client-side side effect with the dependency list; changes to captured values intentionally re-run it.
    useEffect(()=>setDraft(Object.fromEntries(data.alerts.map(alert=>[alert.name,alert.enabled]))),[data.alerts]);
    const handleSave=async()=>{try{const preferences=data.alerts.map(alert=>({name:alert.name,enabled:draft[alert.name] ?? alert.enabled}));const response=await persistPreferences(preferences);toast.success(response.message,{id:'superadmin-team-alert-preferences-saved'});}catch(error:unknown){toast.error(error instanceof Error?error.message:'Unable to save alert preferences.',{id:'superadmin-team-alert-preferences-error'});}};
    return <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Panel title="Role Groups" description="Keep platform permissions separated by job responsibility."><div className="space-y-3">{data.roles.length===0?<SuperadminTeamRoleGroupsEmptyState/>:data.roles.map(role=><div key={role.name} className="flex items-center justify-between rounded-lg border border-border bg-input p-3"><div><p className="font-medium text-primary">{role.name}</p><p className="text-xs text-secondary">{role.scope}</p></div><span className="text-sm text-primary">{formatNumber(role.permissions)} permissions</span></div>)}</div></Panel><Panel title="My Alert Preferences" description="Choose which platform alerts the current operator receives."><div className="space-y-3">{data.alerts.length===0?<SuperadminTeamAlertPreferencesEmptyState/>:data.alerts.map(alert=><label key={alert.name} className="flex items-center gap-3 rounded-lg border border-border p-3"><input type="checkbox" checked={draft[alert.name] ?? alert.enabled} onChange={(event)=>setDraft(prev=>({...prev,[alert.name]:event.target.checked}))} className="size-4 accent-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"/><Bell size={18} className="text-secondary"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-primary">{alert.name}</span><span className="block truncate text-xs text-secondary">{alert.channel} · {alert.threshold}</span></span></label>)}</div><button type="button" disabled={saving} onClick={handleSave} className="mt-4 inline-flex min-w-36 items-center justify-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-on-primary disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Save size={18}/>{saving?<><Loader2 size={18} className="motion-safe:animate-spin"/>Saving...</>:'Save Preferences'}</button></Panel></div>;
}
