// RESPONSIBILITY: Persists master-database authentication security-audit records generated by identity flows.
// FLOW: Security service → master audit repository → CoreMasterTransactionContext → core_auth_audit_logs.

import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import type { Repository } from 'typeorm';
import { CoreAuthAuditLogEntity } from '@/backend_trainer/backend_core/core_database/core-auth-audit-log.entity';
import type { CoreMasterTransactionContext } from '@/backend_trainer/backend_core/core_database/core-master-transaction.context';


/**
 * Intent: Defines the CoreAuthAuditRepository boundary for the backend core architecture.
 * Edge Cases: Preserve tenant scope, validation, authorization, nullability, transactions, and canonical errors when changing this construct.
 * Side Effects: Preserve the owning construct’s existing persistence, cache, event, and audit behavior without introducing cross-module state changes.
 * AI Note: Keep this construct isolated from unrelated modules and preserve frozen contracts; never bypass repository/domain boundaries.
 */
@Injectable()
export class CoreAuthAuditRepository {
  constructor(@InjectRepository(CoreAuthAuditLogEntity) private readonly repository: Repository<CoreAuthAuditLogEntity>) {}

  /** Records the security event raised when repeated login failures trigger lockout. */
  /**
 * @description Executes createLoginLockAudit inside the owning backend service/repository boundary without exposing ORM details.
 * @param userId - Input for createLoginLockAudit.
 * @param identifierHash - Input for createLoginLockAudit.
 * @returns {Promise<void>} The typed result defined by the owning contract.
 * @throws Infrastructure or canonical application exceptions propagated by the owning boundary.
 * @remarks Preserve tenant isolation, frozen API semantics, transaction behavior, and mapper/repository boundaries.
 * AI Note: Do not move ORM access into services, introduce sibling business imports, or silently change response fields.
 */
async createLoginLockAudit(userId: string | null, identifierHash: string): Promise<void> {
    const entity = this.repository.create({ userId, action: 'LOGIN_LOCKED', identifierHash, createdAt: new Date() });
    await this.repository.insert(entity);
  }

  /** Records a password-change security event on the master transaction when one is active. */
  /**
 * @description Executes createPasswordChangeAudit inside the owning backend service/repository boundary without exposing ORM details.
 * @param userId - Input for createPasswordChangeAudit.
 * @param context - Input for createPasswordChangeAudit.
 * @returns {Promise<void>} The typed result defined by the owning contract.
 * @throws Infrastructure or canonical application exceptions propagated by the owning boundary.
 * @remarks Preserve tenant isolation, frozen API semantics, transaction behavior, and mapper/repository boundaries.
 * AI Note: Do not move ORM access into services, introduce sibling business imports, or silently change response fields.
 */
async createPasswordChangeAudit(userId: string, context?: CoreMasterTransactionContext): Promise<void> {
    const repository = context?.getRepository(CoreAuthAuditLogEntity) ?? this.repository;
    const entity = repository.create({ userId, action: 'PASSWORD_CHANGED', identifierHash: null, createdAt: new Date() });
    await repository.insert(entity);
  }
}
