import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783787008185 implements MigrationInterface {
    name = 'InitialSchema1783787008185'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantName" character varying NOT NULL, "subject" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'OPEN', "priority" character varying NOT NULL DEFAULT 'MEDIUM', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" character varying, "actorRole" character varying, "action" character varying NOT NULL, "entityType" character varying NOT NULL, "entityId" character varying, "oldValue" jsonb, "newValue" jsonb, "ipAddress" character varying, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "ownerName" character varying NOT NULL, "adminEmail" character varying NOT NULL, "phone" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'TRIAL', "plan" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "memberCount" integer NOT NULL DEFAULT '0', "monthlyRevenue" numeric(10,2) NOT NULL DEFAULT '0', "databaseVersion" character varying NOT NULL DEFAULT '1.0.0', "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_de8b77d2de64099beb80a7f78db" UNIQUE ("adminEmail"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" character varying NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "date" TIMESTAMP NOT NULL, "isPublished" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6b1e6b6f88da9888fde62379945" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantName" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "status" character varying NOT NULL DEFAULT 'PENDING', "date" TIMESTAMP NOT NULL, "planName" character varying NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "queueName" character varying NOT NULL, "jobName" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "attempts" integer NOT NULL DEFAULT '0', "error" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."superadmin_infrastructure_type_enum" AS ENUM('VPS', 'DATABASE', 'REDIS', 'CDN', 'LOAD_BALANCER', 'STORAGE')`);
        await queryRunner.query(`CREATE TYPE "public"."superadmin_infrastructure_status_enum" AS ENUM('RUNNING', 'STOPPED', 'WARNING', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "superadmin_infrastructure" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "type" "public"."superadmin_infrastructure_type_enum" NOT NULL, "status" "public"."superadmin_infrastructure_status_enum" NOT NULL DEFAULT 'RUNNING', "provider" character varying(100), "region" character varying(100), "host_address" character varying(255), "cpu_percent" numeric(5,2), "memory_percent" numeric(5,2), "disk_percent" numeric(5,2), "uptime_seconds" bigint, "last_checked_at" TIMESTAMP, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ec49e85ae4296bd67c929a22f05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e99f02d5320d87a7212085b756" ON "superadmin_infrastructure" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_94478e90bfbf0cf90def3d00fb" ON "superadmin_infrastructure" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfa7f9510934a023fecbbf7530" ON "superadmin_infrastructure" ("status") `);
        await queryRunner.query(`CREATE TABLE "migrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "appliedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'PENDING', "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_2d4874d85cd312e39b375e45dd8" UNIQUE ("name"), CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gyms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "ownerName" character varying NOT NULL, "adminEmail" character varying NOT NULL, "phone" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'TRIAL', "plan" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "memberCount" integer NOT NULL DEFAULT '0', "monthlyRevenue" numeric(10,2) NOT NULL DEFAULT '0', "databaseVersion" character varying NOT NULL DEFAULT '1.0.0', "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_d31df12e9d799ef70178465766c" UNIQUE ("adminEmail"), CONSTRAINT "PK_fe765086496cf3c8475652cddcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "isGlobalEnabled" boolean NOT NULL DEFAULT false, "enabledTenantIds" jsonb NOT NULL DEFAULT '[]', "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_bcc3a344ae156a9fba128e1cb4d" UNIQUE ("name"), CONSTRAINT "PK_5c1e336df2f4a7051e5bf08a941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "superadmin_release_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" character varying(50) NOT NULL, "title" character varying(500) NOT NULL, "content" text NOT NULL, "date" TIMESTAMP, "is_published" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a0383118c5539c0b89fb4e33e1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b341806522588548a991d3dae9" ON "superadmin_release_notes" ("version") `);
        await queryRunner.query(`CREATE INDEX "IDX_33331dfc09e204f9907dabf1f3" ON "superadmin_release_notes" ("is_published") `);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "discountPercentage" double precision NOT NULL, "maxUses" integer NOT NULL, "currentUses" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'ACTIVE', "expiryDate" TIMESTAMP NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "superadmin_feature_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text NOT NULL, "is_global_enabled" boolean NOT NULL DEFAULT false, "enabled_tenant_ids" text, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_074b876111afaf6cdd42c241b9a" UNIQUE ("name"), CONSTRAINT "PK_160fa65d9d97a27f5c814d6d47a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_074b876111afaf6cdd42c241b9" ON "superadmin_feature_flags" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_34fcbad74f308916bf4a5c5bcb" ON "superadmin_feature_flags" ("is_global_enabled") `);
        await queryRunner.query(`CREATE TABLE "broadcasts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "content" text NOT NULL, "status" character varying NOT NULL DEFAULT 'DRAFT', "audience" character varying NOT NULL, "scheduledDate" TIMESTAMP, "sentDate" TIMESTAMP, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b0586900034d0726bbdcb1b21b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "backups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantName" character varying NOT NULL, "databaseName" character varying NOT NULL, "sizeMB" double precision NOT NULL, "status" character varying NOT NULL DEFAULT 'IN_PROGRESS', "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ca30ff369eddfc7dac3b35d0d3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit-logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorName" character varying NOT NULL, "actorRole" character varying NOT NULL, "action" character varying NOT NULL, "targetResource" character varying NOT NULL, "ipAddress" character varying, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_04aec56387683ba0551d04686d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."superadmin_global_audit_logs_actor_role_enum" AS ENUM('SUPERADMIN', 'SUPPORT_AGENT', 'BILLING_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "superadmin_global_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor_name" character varying(255) NOT NULL, "actor_role" "public"."superadmin_global_audit_logs_actor_role_enum" NOT NULL, "action" character varying(200) NOT NULL, "target_resource" character varying(500), "ip_address" character varying(45), "old_value" json, "new_value" json, "timestamp" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a90e22e767dee07dbed21392c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cdef19f8de5affbd883e120dc" ON "superadmin_global_audit_logs" ("actor_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0e11c67160ea3f4afc7243937" ON "superadmin_global_audit_logs" ("actor_role") `);
        await queryRunner.query(`CREATE INDEX "IDX_57def47008bfb07c3605c8fbb9" ON "superadmin_global_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f6a6889d30e0951955214358b" ON "superadmin_global_audit_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "affiliates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "referralCode" character varying NOT NULL, "totalReferred" integer NOT NULL DEFAULT '0', "commissionEarned" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'ACTIVE', "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_24ffa7680861d79b2d728b9d55e" UNIQUE ("email"), CONSTRAINT "UQ_04b6458c3a05ec95b31a0cc9218" UNIQUE ("referralCode"), CONSTRAINT "PK_5458bf988fb83086da3a14b9ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workouts" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "level" character varying NOT NULL, "days" integer NOT NULL, "exercises" integer NOT NULL, "focus" character varying NOT NULL, "duration" character varying NOT NULL, "tags" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_5b2319bf64a674d40237dbb1697" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "member_id" character varying NOT NULL, "plan_id" character varying, "amount" numeric(10,2) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'PENDING', "payment_method" character varying, "transaction_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "gstNumber"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "gymName"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "ownerName"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "UQ_8f72a20c98ab97e783c5e87ea2a"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "tier"`);
        await queryRunner.query(`DROP TYPE "public"."plans_tier_enum"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price1Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price3Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price6Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price12Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "tier" "public"."plans_tier_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "UQ_8f72a20c98ab97e783c5e87ea2a" UNIQUE ("tier")`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price1Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price3Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price6Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price12Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "value" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "group" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "priceMonthly" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "priceAnnual" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "maxMembers" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "maxStaff" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "activeTenants" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "gymName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "ownerName" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "gstNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "PK_0669fe20e252eb692bf4d344975"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "UQ_253d25dae4c94ee913bc5ec4850" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "features"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "features" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "PK_0669fe20e252eb692bf4d344975"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "PK_0669fe20e252eb692bf4d344975"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "features"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "features" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "UQ_253d25dae4c94ee913bc5ec4850"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "PK_0669fe20e252eb692bf4d344975"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "gstNumber"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "ownerName"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "gymName"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "activeTenants"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "maxStaff"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "maxMembers"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "priceAnnual"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "priceMonthly"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "group"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "UQ_c8639b7626fa94ba8265628f214"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "key"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price12Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price6Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price3Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "price1Month"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "UQ_8f72a20c98ab97e783c5e87ea2a"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "tier"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price12Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price6Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price3Month" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "price1Month" double precision NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."plans_tier_enum" AS ENUM('BASIC', 'GOLD', 'PREMIUM')`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "tier" "public"."plans_tier_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "UQ_8f72a20c98ab97e783c5e87ea2a" UNIQUE ("tier")`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "ownerName" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "gymName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "gstNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "workouts"`);
        await queryRunner.query(`DROP TABLE "affiliates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f6a6889d30e0951955214358b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57def47008bfb07c3605c8fbb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0e11c67160ea3f4afc7243937"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cdef19f8de5affbd883e120dc"`);
        await queryRunner.query(`DROP TABLE "superadmin_global_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."superadmin_global_audit_logs_actor_role_enum"`);
        await queryRunner.query(`DROP TABLE "audit-logs"`);
        await queryRunner.query(`DROP TABLE "backups"`);
        await queryRunner.query(`DROP TABLE "broadcasts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34fcbad74f308916bf4a5c5bcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_074b876111afaf6cdd42c241b9"`);
        await queryRunner.query(`DROP TABLE "superadmin_feature_flags"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33331dfc09e204f9907dabf1f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b341806522588548a991d3dae9"`);
        await queryRunner.query(`DROP TABLE "superadmin_release_notes"`);
        await queryRunner.query(`DROP TABLE "features"`);
        await queryRunner.query(`DROP TABLE "gyms"`);
        await queryRunner.query(`DROP TABLE "migrations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfa7f9510934a023fecbbf7530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94478e90bfbf0cf90def3d00fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e99f02d5320d87a7212085b756"`);
        await queryRunner.query(`DROP TABLE "superadmin_infrastructure"`);
        await queryRunner.query(`DROP TYPE "public"."superadmin_infrastructure_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."superadmin_infrastructure_type_enum"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TABLE "system"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
    }

}
