export const SuperadminUrlConfig = {
  PAGES: {
    DASHBOARD: "/superadmin/dashboard",
    BRANCHES: "/superadmin/branches",
    FRANCHISES: "/superadmin/franchises",
    SETTINGS: "/superadmin/settings",
    USAGE_METERS: "/superadmin/usage-meters",
    GLOBAL_AUDIT: "/superadmin/global-audit",
    ANALYTICS: "/superadmin/analytics",
    COUPONS: "/superadmin/coupons",
    AFFILIATES: "/superadmin/affiliates",
    GYMS_LIST: "/superadmin/gyms",
    INVOICES: "/superadmin/invoices",
    TICKETS: "/superadmin/tickets",
    BROADCASTS: "/superadmin/broadcasts",
    FEATURES: "/superadmin/features",
    INFRASTRUCTURE: "/superadmin/infrastructure",
    MIGRATIONS: "/superadmin/migrations",
    JOBS: "/superadmin/jobs",
    BACKUPS: "/superadmin/backups",
    SYSTEM_HEALTH: "/superadmin/system",
    PLANS: "/superadmin/plans",
    GYM_ADD: "/superadmin/gyms/add",
    ONBOARDING: "/superadmin/onboarding",
    MESSAGING: "/superadmin/messaging",
    REPORTS: "/superadmin/reports",
    TENANT_PREVIEW: "/superadmin/tenant-preview", // removed — kept for type safety, route deleted
    CHURN_ALERTS: "/superadmin/churn-alerts",
    PROFILE: "/superadmin/profile",
  },
  BACKEND_API: {}
};
