// Generated by ts-to-zod
import { z } from "zod";

export const adminSidebarPropsSchema = z.object({
    isCollapsed: z.boolean(),
    setIsCollapsed: z.function({ input: [z.boolean()], output: z.void() })
});

export const adminHeaderPropsSchema = z.object({
    title: z.string(),
    subtitle: z.string().optional()
});
