import { IsNull } from 'typeorm';
// RESPONSIBILITY: Owns notification list/read/preference queries and updates for the Trainer module.
// FLOW: Notification services → NotificationsRepository → tenant TypeORM repository.

import { CoreBaseRepository } from '@/backend_trainer/core/database/core-base.repository';
import { Injectable } from '@nestjs/common'; import { CoreTenantDataSourceResolver } from '@/backend_trainer/core/database/core-tenant-datasource.resolver'; import { NotificationsNotificationEntity } from '@/backend_trainer/modules/backend_trainer/notifications/notifications-notification.entity'; import { NotificationsNotificationPreferenceEntity } from '@/backend_trainer/modules/backend_trainer/notifications/notifications-notification-preference.entity';
@Injectable() export class NotificationsRepository extends CoreBaseRepository { constructor(private readonly resolver:CoreTenantDataSourceResolver){super();}
  /** Lists notifications with unread filtering and pagination. */ async findMany(trainerId:string,query:{page:number;limit:number;unreadOnly?:boolean;search?:string;sortBy:'createdAt'|'title';sortDirection:'asc'|'desc'|'ASC'|'DESC'}):Promise<{rows:NotificationsNotificationEntity[];total:number;unreadCount:number}>{const repo=await this.resolver.getRepository(NotificationsNotificationEntity); const qb=repo.createQueryBuilder('n').where('n.trainer_id=:trainerId AND n.deleted_at IS NULL',{trainerId}); if(query.unreadOnly) qb.andWhere('n.is_read=false'); if(query.search) qb.andWhere('(n.title ILIKE :search OR n.message ILIKE :search)',{search:`%${query.search}%`}); const total=await qb.getCount(); const unreadCount=await repo.countBy({trainerId,isRead:false}); const sortColumn=query.sortBy==='title'?'n.title':'n.created_at'; const direction=query.sortDirection.toUpperCase()==='ASC'?'ASC':'DESC'; const rows=await qb.orderBy(sortColumn,direction).skip((query.page-1)*query.limit).take(query.limit).getMany(); return {rows,total,unreadCount};}
  /** Marks one trainer notification as read. */ async markRead(id:string,trainerId:string):Promise<NotificationsNotificationEntity|null>{const repo=await this.resolver.getRepository(NotificationsNotificationEntity); await repo.update({id,trainerId,deletedAt: IsNull()},{isRead:true}); return repo.findOneBy({id,trainerId,deletedAt: IsNull()});}
  /** Marks all trainer notifications as read. */ async markAllRead(trainerId:string):Promise<number>{const result=await (await this.resolver.getRepository(NotificationsNotificationEntity)).update({trainerId,isRead:false,deletedAt: IsNull()},{isRead:true}); return result.affected ?? 0;}
  /** Finds or creates notification preferences for one trainer. */ async getPreferences(trainerId:string):Promise<NotificationsNotificationPreferenceEntity>{const repo=await this.resolver.getRepository(NotificationsNotificationPreferenceEntity); const existing=await repo.findOneBy({trainerId,deletedAt: IsNull()}); if(existing) return existing; return repo.save(repo.create({trainerId}));}
  /** Updates the preference fields supplied by the trainer. */ async updatePreferences(trainerId:string,input:Partial<NotificationsNotificationPreferenceEntity>):Promise<NotificationsNotificationPreferenceEntity>{const repo=await this.resolver.getRepository(NotificationsNotificationPreferenceEntity); await this.getPreferences(trainerId); await repo.update({trainerId,deletedAt: IsNull()},input); return repo.findOneByOrFail({trainerId,deletedAt: IsNull()});}
}
