// RESPONSIBILITY: The single routing, anchor, API, external-destination, and asset contract owned by PublicLanding.
export const PublicLandingUrlConfig = {
  PAGES: {
    LANDING: '/landing',
    ERP_LOGIN: '/frontend_auth/auth/login',
    SAAS_LOGIN: '/frontend_auth/auth/login',
  },
  ANCHORS: {
    HOME: '#home',
    ABOUT: '#about',
    BMI: '#bmi',
    SERVICES: '#services',
    PLANS: '#plans',
    SCHEDULE: '#schedule',
    TRAINERS: '#trainers',
    GALLERY: '#gallery',
    TESTIMONIALS: '#testimonials',
    CONTACT: '#contact',
    BOOKING: '#booking',
    TRANSFORMATIONS: '#transformations',
    SERVICE_BODYBUILDING: '#service-bodybuilding',
    SERVICE_WEIGHT_LOSS: '#service-weight-loss',
    SERVICE_WEIGHT_GAIN: '#service-weight-gain',
    SERVICE_CARDIO: '#service-cardio',
    SERVICE_CROSSFIT: '#service-crossfit',
    SERVICE_YOGA: '#service-yoga',
    SERVICE_ZUMBA: '#service-zumba',
    SERVICE_PERSONAL_TRAINING: '#service-personal-training',
    SERVICE_DIET_PLAN: '#service-diet-plan',
  },
  BACKEND_API: {
    BOOKING: '/landing/bookings',
    CONTACT: '/landing/contact',
  },
  EXTERNAL: {
    FACEBOOK: 'https://www.facebook.com/',
    INSTAGRAM: 'https://www.instagram.com/',
    X: 'https://x.com/',
    YOUTUBE: 'https://www.youtube.com/',
    PHONE: 'tel:+919876543210',
    EMAIL: 'mailto:hello@gymsmart.com',
  },
  ASSETS: {
    LOGO: '/logo.png',
    HERO: '/gym_hero.png',
    GALLERY_CARDIO: '/gym_gallery_cardio.png',
    GALLERY_WEIGHTS: '/gym_gallery_weights.png',
    GALLERY_STUDIO: '/gym_gallery_studio.png',
  },
} as const;
