// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const payoutTabSchema = z.union([z.literal("summary"), z.literal("pnl")]);

export const gymPayoutSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    month: z.string(),
    grossRevenue: z.number(),
    staffPayroll: z.number(),
    operationalExpenses: z.number(),
    platformFee: z.number(),
    netProfit: z.number(),
    payoutStatus: z.union([z.literal("paid"), z.literal("pending"), z.literal("processing")]),
    paidOn: z.string().optional(),
    approvedBy: z.string().optional(),
    approvedAt: z.string().optional(),
    rejectionReason: z.string().optional()
});

export const pnLEntrySchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    month: z.string(),
    revenue: z.number(),
    cogs: z.number(),
    grossProfit: z.number(),
    staffCost: z.number(),
    rentUtilities: z.number(),
    marketing: z.number(),
    miscExpenses: z.number(),
    ebitda: z.number(),
    tax: z.number(),
    netProfit: z.number()
});

export const payoutsKpiDataSchema = z.object({
    totalNetProfit: z.number(),
    totalGrossRevenue: z.number(),
    totalExpenses: z.number(),
    pendingPayouts: z.number()
});
