// RESPONSIBILITY: Renders/orchestrates SuperadminSettingsMain within its owning Superadmin feature module; no direct backend implementation.
'use client';
/**
 * RESPONSIBILITY: React component SuperadminSettingsMain owned by the superadmin_settings feature boundary.
 * INTENT: Keep this file’s presentation, logic, and state responsibility isolated from unrelated business modules.
 * STATE DEPENDENCIES: No React/client state primitive detected.
 * MODULE DEPENDENCIES: lucide-react, @/components/ui/SearchableDropdown, @/app/frontend_superadmin/superadmin_settings/superadmin_settings_hooks/useSuperadminSettingsMain
 * EDGE CASES: Preserve implemented loading, empty, error, disabled, cancellation, retry, and repeated-action behavior.
 * REPAIR CONSTRAINT: Cross-feature business dependencies require explicit documentation; do not move business logic into global UI infrastructure.
 */
// RESPONSIBILITY: Renders platform settings from useSuperadminSettingsMain. Draft/state and save orchestration stay in the adjacent hook.
import { Settings, Save, FileText } from 'lucide-react';
import { useTranslations } from 'next-intl';

import { SearchableDropdown } from '@/components/ui/SearchableDropdown';

import { useSuperadminSettingsMain } from '@/app/frontend_superadmin/superadmin_settings/superadmin_settings_hooks/useSuperadminSettingsMain';



/**
 * @description Renders platform settings from useSuperadminSettingsMain. Draft/state and save orchestration stay in the adjacent hook.
 * @dependencies Delegates domain behavior to the feature-local dependencies imported by this file.
 * @state Keeps server state in TanStack Query and module UI state in the owning feature state layer where applicable.
 * @edge-cases Preserves documented loading, empty, error, disabled, cancellation, retry, and repeated-action behavior.
 */
export default function SuperadminSettingsMain() {
  const t = useTranslations('superadmin_settings');
  const { query, isUpdating, variables, groupedSettings, editedValues, setEditedValues, handleSave } = useSuperadminSettingsMain();
  if (query.isPending) return (<div className="space-y-6" aria-busy="true" aria-label={t('ui.loading_platform_settings_056ed69b')} data-testid="superadmin_settings-superadmin-settings-main-page"><div><div className="h-8 w-48 rounded bg-skeleton-base motion-safe:animate-pulse"/><div className="mt-2 h-4 w-96 max-w-full rounded bg-skeleton-base motion-safe:animate-pulse"/></div><div className="max-w-4xl space-y-6">{[1,2].map((item) => <div key={`settings-skeleton-${item}`} className="h-48 rounded-xl border border-border bg-skeleton-base p-6 motion-safe:animate-pulse"/>)}</div></div>);
  if (query.isError) return (<div className="flex min-h-80 flex-col items-center justify-center gap-3 rounded-xl border border-border bg-danger-bg p-6 text-center" role="alert" data-testid="superadmin_settings-main-error-state"><p className="font-medium text-danger">{t('ui.platform_settings_could_not_be_loaded_00f9abd2')}</p><button type="button" onClick={() => void query.refetch()} className="min-h-11 rounded-md border border-border px-4 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary motion-safe:transition-all motion-safe:duration-base motion-safe:active:scale-95" data-testid="superadmin_settings-superadmin-settings-main-superadmin-settings-main-retry">{t('ui.retry_6327b4e5')}</button></div>);
  return (<div className="space-y-6"><div><h1 className="text-2xl font-bold text-primary">{t('ui.platform_settings_bc7aef6e')}</h1><p className="mt-1 text-secondary">{t('ui.configure_global_saas_limits_master_credenti_246230e0')}</p></div><div className="max-w-4xl space-y-6">
    {Object.entries(groupedSettings).map(([category, items]) => <section key={category} className="rounded-xl border border-border bg-card p-6"><div className="mb-4 flex items-center gap-2 border-b border-border pb-4"><Settings size={18} strokeWidth={2} className="text-primary" aria-hidden="true"/><h2 className="text-lg font-bold uppercase text-primary">{category}</h2></div><div className="space-y-4 text-sm">{items.map((setting) => { const hasChanges = editedValues[setting.id] !== undefined && editedValues[setting.id] !== setting.value; const currentValue = editedValues[setting.id] ?? setting.value; const isSavingThis = isUpdating && variables?.id === setting.id; return (<div key={setting.id} className="flex flex-col justify-between gap-4 border-b border-border py-2 last:border-0 md:flex-row md:items-center"><div className="min-w-0 flex-1"><h3 className="truncate font-medium text-primary" title={setting.key}>{setting.key}</h3><p className="mt-1 text-xs text-secondary">{setting.description}</p></div><div className="flex flex-wrap items-center gap-2">{setting.dataType === 'boolean' ? <SearchableDropdown data-testid={`superadmin_settings-superadmin-settings-main-${setting.id}-value`} value={String(currentValue)} onChange={(value) => setEditedValues((previous) => ({ ...previous, [setting.id]: String(value) }))} className="w-32" options={[{ label: 'Enabled', value: 'true' }, { label: 'Disabled', value: 'false' }].map((option) => ({ label: option.label, value: option.value }))}/> : <input aria-label={setting.key} type={setting.dataType === 'number' ? 'number' : 'text'} value={currentValue} onChange={(event) => setEditedValues((previous) => ({ ...previous, [setting.id]: event.target.value }))} className="rounded-lg border border-border bg-input px-3 py-1.5 text-primary focus:border-focus focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" data-testid="superadmin_settings-superadmin-settings-main-superadmin-settings-main-input"/>}{hasChanges ? <button type="button" onClick={() => void handleSave(setting.id)} disabled={isSavingThis} aria-label={t('ui.save_setting_aria', { key: setting.key })} className="min-h-11 min-w-11 rounded-lg bg-primary-subtle p-2 text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:cursor-not-allowed disabled:opacity-60 motion-safe:transition-all motion-safe:duration-base motion-safe:active:scale-95" data-testid="superadmin_settings-superadmin-settings-main-superadmin-settings-main-button"><Save size={18} strokeWidth={2} aria-hidden="true"/></button> : null}</div></div>); })}</div></section>)}
    <section className="rounded-xl border border-border bg-card p-6"><div className="mb-4 flex items-center gap-2 border-b border-border pb-4"><FileText size={18} strokeWidth={2} className="text-primary" aria-hidden="true"/><h2 className="text-lg font-bold uppercase text-primary">{t('ui.changelog_c49182dc')}</h2></div><div className="space-y-6 text-sm"><div className="relative border-l-2 border-border pb-2 pl-6"><div className="absolute -left-2 top-1 h-3 w-3 rounded-full bg-primary text-on-primary"/><h3 className="mb-1 text-base font-semibold text-primary">{t('ui.v2_4_1_current_6b444d2d')}</h3><p className="mb-2 text-xs text-secondary">{t('ui.released_on_sept_09_2026_bb49ecfc')}</p><ul className="list-disc space-y-1 pl-4 text-secondary"><li>{t('ui.added_support_for_trialgyms_count_in_dashboa_66b93a0a')}</li><li>{t('ui.fixed_overdue_invoices_kpi_aggregation_bug_ba59f236')}</li><li>{t('ui.added_quot_revenue_by_plan_tier_quot_donut_c_a5d1f407')}</li></ul></div><div className="relative border-l-2 border-border pb-2 pl-6"><div className="absolute -left-2 top-1 h-3 w-3 rounded-full bg-surface-highlight"/><h3 className="mb-1 text-base font-semibold text-primary">{t('ui.v2_4_0_fd7b4c8a')}</h3><p className="mb-2 text-xs text-secondary">{t('ui.released_on_aug_21_2026_113677d0')}</p><ul className="list-disc space-y-1 pl-4 text-secondary"><li>{t('ui.introduced_superadmin_module_a7ce793b')}</li><li>{t('ui.added_global_audit_logs_7b2a40b5')}</li><li>{t('ui.basic_gym_management_and_uptime_tracker_d3d15603')}</li></ul></div></div></section>
  </div></div>);
}
