// RESPONSIBILITY: Renders ManagerInquiriesConvertLeadModal's feature UI and orchestrates presentation through module-owned state/hooks; it does not own API transport or business rules.
'use client';
import { X, Save } from 'lucide-react';
import { useTranslations } from 'next-intl';
import ManagerInquiriesConvertLeadForm from '@/app/frontend_manager/manager_inquiries/manager_inquiries_components/manager_inquiries_convert_lead_modal/ManagerInquiriesConvertLeadForm';
import ManagerInquiriesConvertLeadSuccess from '@/app/frontend_manager/manager_inquiries/manager_inquiries_components/manager_inquiries_convert_lead_modal/ManagerInquiriesConvertLeadSuccess';
import { useManagerInquiriesConvertLeadForm } from '@/app/frontend_manager/manager_inquiries/manager_inquiries_hooks/useManagerInquiriesConvertLeadForm';

/** @description Renders the ManagerInquiriesConvertLeadModal component for its owning Manager frontend boundary. @dependencies Local dependencies are owned by this feature module (3 documented module/import dependencies).. @edge-case Preserves loading state, modal lifecycle. */
export default function ManagerInquiriesConvertLeadModal() {
  const t = useTranslations('MANAGER_INQUIRIES');

  const { activeLead, plans, plansLoading, form, planId, billingCycle, customDays, saving, successData, submit, handleClose, closeConvert } = useManagerInquiriesConvertLeadForm();
  if (!activeLead) return null;
  return <div className="fixed inset-0 z-40 flex items-center justify-center p-4 bg-overlay-backdrop"><div className="bg-overlay rounded-2xl shadow-dialog w-full max-w-xl overflow-visible border border-border max-h-full flex flex-col" role="dialog" aria-modal="true" aria-labelledby="managerinquiriesconvertleadmodal-dialog-title"><div className="sticky top-0 bg-overlay px-6 py-4 border-b border-border flex items-center justify-between z-20 rounded-t-2xl"><div><h3 className="text-lg font-bold text-primary" id="managerinquiriesconvertleadmodal-dialog-title">{t("COPY_CONVERT_MEMBER_1")}</h3><p className="text-xs text-secondary mt-0.5">{t("COPY_COMPLETE_ADMISSION")}{activeLead.name}</p></div><button data-testid="manager_inquiries-convert-lead-modal-close-1" type="button" onClick={handleClose} aria-label={t("COPY_CLOSE_CONVERSION_FORM")} className="p-2 rounded-full hover:bg-primary-subtle text-secondary motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"><X size={18} strokeWidth={2}/></button></div>{(() => { if (successData) { return <ManagerInquiriesConvertLeadSuccess successData={successData} closeConvert={closeConvert} />; } return <form data-testid="manager_inquiries-managerinquiriesconvertleadmodal-form-1" onSubmit={submit} className="overflow-y-auto flex-1 custom-scrollbar p-4 flex flex-col gap-4">{plansLoading ? <div className="h-64 rounded-xl bg-skeleton-base motion-safe:animate-pulse" aria-label={t("COPY_LOADING_MEMBERSHIP_PLANS")} /> : <ManagerInquiriesConvertLeadForm useFormReturn={form} plans={plans} watchPlanId={planId} watchBillingCycle={billingCycle} watchCustomDays={customDays} /> }<div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-border mt-2"><button data-testid="manager_inquiries-convert-lead-modal-close-2" type="button" onClick={handleClose} className="flex-1 py-2.5 border border-border rounded-xl text-sm font-medium text-primary motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{t("COPY_CANCEL_2")}</button><button data-testid="manager_inquiries-convert-lead-modal-button-submit" type="submit" disabled={form.formState.isSubmitting || plansLoading} className="min-w-40 flex-1 py-2.5 rounded-xl text-sm font-bold bg-primary text-on-primary flex items-center justify-center gap-2 disabled:opacity-70 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{form.formState.isSubmitting ? t('COPY_SAVING') : <><Save size={18} strokeWidth={2}/>{t("COPY_CONVERT_INQUIRY")}</>}</button></div></form>; })()}</div></div>;
}
