// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const reportTabSchema = z.union([z.literal("revenue"), z.literal("membership"), z.literal("attendance"), z.literal("payroll"), z.literal("pnl")]);

export const reportDateRangeSchema = z.union([z.literal("this_month"), z.literal("last_month"), z.literal("last_3_months"), z.literal("last_6_months"), z.literal("this_year"), z.literal("custom")]);

export const revenueByGymSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    revenue: z.number(),
    expenses: z.number(),
    profit: z.number(),
    trend: z.union([z.literal("up"), z.literal("down"), z.literal("flat")]),
    trendPercent: z.number()
});

export const revenueByMethodSchema = z.object({
    method: z.string(),
    amount: z.number(),
    count: z.number()
});

export const revenueByPlanSchema = z.object({
    planName: z.string(),
    amount: z.number(),
    count: z.number()
});

export const monthlyRevenueSchema = z.object({
    month: z.string(),
    revenue: z.number(),
    expenses: z.number(),
    profit: z.number()
});

export const membershipGrowthRowSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    newMembers: z.number(),
    renewals: z.number(),
    exits: z.number(),
    netGrowth: z.number(),
    activeMembers: z.number()
});

export const attendanceHeatmapCellSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    day: z.string(),
    count: z.number(),
    rate: z.number()
});

export const attendanceSummaryRowSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    avgDailyAttendance: z.number(),
    peakDay: z.string(),
    attendanceRate: z.number(),
    totalCheckIns: z.number()
});

export const payrollSummaryRowSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    totalStaff: z.number(),
    totalPayroll: z.number(),
    paid: z.number(),
    pending: z.number(),
    advances: z.number()
});

export const pnLRowSchema = z.object({
    gymId: z.string(),
    gymName: z.string(),
    revenue: z.number(),
    membershipRevenue: z.number(),
    storeRevenue: z.number(),
    totalExpenses: z.number(),
    staffCost: z.number(),
    operationalCost: z.number(),
    netProfit: z.number(),
    profitMargin: z.number()
});

export const reportDataSchema = z.object({
    revenueByGym: z.array(revenueByGymSchema),
    revenueByMethod: z.array(revenueByMethodSchema),
    revenueByPlan: z.array(revenueByPlanSchema),
    monthlyRevenue: z.array(monthlyRevenueSchema),
    membershipGrowth: z.array(membershipGrowthRowSchema),
    attendanceSummary: z.array(attendanceSummaryRowSchema),
    attendanceHeatmap: z.array(attendanceHeatmapCellSchema),
    payrollSummary: z.array(payrollSummaryRowSchema),
    pnlSummary: z.array(pnLRowSchema),
    kpis: z.object({
        totalRevenue: z.number(),
        totalExpenses: z.number(),
        netProfit: z.number(),
        totalMembers: z.number(),
        newMembers: z.number(),
        avgAttendanceRate: z.number(),
        totalPayroll: z.number()
    })
});

export const reportsContextTypeSchema = z.object({
    activeTab: reportTabSchema,
    setActiveTab: z.function({ input: [reportTabSchema], output: z.void() }),
    dateRange: reportDateRangeSchema,
    setDateRange: z.function({ input: [reportDateRangeSchema], output: z.void() }),
    startDate: z.string(),
    endDate: z.string(),
    setCustomDateRange: z.function({ input: [z.string(), z.string()], output: z.void() }),
    selectedGymId: z.string(),
    setSelectedGymId: z.function({ input: [z.string()], output: z.void() }),
    reportData: reportDataSchema.nullable(),
    status: statusSchema
});
