// RESPONSIBILITY: Renders or orchestrates the owning Manager feature UI; API transport and business rules remain in module-owned hooks/services.
'use client';
import { Loader2, X, Save } from 'lucide-react';
import { useTranslations, useLocale } from 'next-intl';
import { Controller } from 'react-hook-form';
import ManagerSearchableDropdown from '@/components/ui/manager_searchable_dropdown/ManagerSearchableDropdown';
import { ManagerEnvConfig } from '@/app/frontend_manager/manager_infrastructure/ManagerEnvConfig';
import { BILLING_CYCLE_CUSTOM } from '@/app/frontend_manager/manager_members/manager_members_constants/ManagerMembersSharedConstants';
import { MANAGER_MEMBER_MAX_CUSTOM_DAYS, MANAGER_MEMBER_MAX_AMOUNT_MAJOR_UNITS } from '@/app/frontend_manager/manager_members/manager_members_constants/ManagerMembersSharedConstants';
import { useManagerMembersRenewForm } from '@/app/frontend_manager/manager_members/manager_members_hooks/useManagerMembersRenewForm';
import { ManagerMembersFormatCurrency } from '@/app/frontend_manager/manager_members/manager_members_utils/ManagerMembersFormatters';


/** @description Renders the ManagerMembersRenewModal component for its owning Manager frontend boundary. @dependencies Local dependencies are owned by this feature module (5 documented module/import dependencies).. @edge-case Preserves error state, modal lifecycle. */
export default function ManagerMembersRenewModal() {
  const t = useTranslations('MANAGER_MEMBERS');
  const locale = useLocale();

  const { showRenewModal, setShowRenewModal, selectedMember, plans, form, actionType, planId, billingCycle, customDays, selectedPlan, calculatedPrice, paymentMethods, cycleLabels, submit, handleClose } = useManagerMembersRenewForm();
  const { register, control, formState: { errors, isSubmitting } } = form;
  if (!showRenewModal || !selectedMember) return null;
  return <div className="fixed inset-0 bg-overlay-backdrop z-40 flex items-center justify-center p-4">
    <div className="bg-overlay rounded-2xl shadow-dialog w-full max-w-xl max-h-full overflow-y-auto border-2 border-primary" role="dialog" aria-modal="true" aria-labelledby="managermembersrenewmodal-dialog-title">
      <div className="sticky top-0 px-8 py-5 border-b border-border bg-overlay flex items-center justify-between z-20">
        <div><h3 className="text-xl font-bold text-primary" id="managermembersrenewmodal-dialog-title">{t("COPY_RENEW_UPGRADE_PLAN")}</h3><p className="text-sm text-secondary mt-1">{t("COPY_TEXT")}{selectedMember.name}</p></div>
        <button data-testid="manager_members-manager-renew-modal-close-1" type="button" onClick={handleClose} aria-label={t("COPY_CLOSE_RENEWAL_FORM")} className="p-2 rounded-full hover:bg-primary-subtle motion-safe:transition-all text-secondary hover:text-primary motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"><X size={18} strokeWidth={2}/></button>
      </div>
      <form data-testid="manager_members-managermembersrenewmodal-form-1" onSubmit={submit} className="p-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          <fieldset className="sm:col-span-2 flex gap-4 p-1.5 bg-input rounded-xl border border-border w-fit">
            <legend className="sr-only">{t("COPY_MEMBERSHIP_ACTION")}</legend>
            <label data-testid="manager_members-manager-renew-modal-label-field-1" className={[`flex-1 flex text-center cursor-pointer px-4 py-1.5 rounded-lg text-sm font-semibold motion-safe:transition-all ${actionType === 'renew' ? 'bg-primary-subtle text-primary shadow-card' : 'text-secondary hover:text-primary'}`, "motion-safe:duration-base ease-in-out"].filter(Boolean).join(' ')}><input data-testid="manager_members-manager-renew-modal-input-radio-select-1" type="radio" value="renew" {...register('actionType')} className="sr-only focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" />{t("COPY_RENEW_PLAN_2")}</label>
            <label data-testid="manager_members-manager-renew-modal-label-field-2" className={[`flex-1 flex text-center cursor-pointer px-4 py-1.5 rounded-lg text-sm font-semibold motion-safe:transition-all ${actionType === 'upgrade' ? 'bg-primary-subtle text-primary shadow-card' : 'text-secondary hover:text-primary'}`, "motion-safe:duration-base ease-in-out"].filter(Boolean).join(' ')}><input data-testid="manager_members-manager-renew-modal-input-radio-select-2" type="radio" value="upgrade" {...register('actionType')} className="sr-only focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" />{t("COPY_UPGRADE_PLAN")}</label>
          </fieldset>
          <div><label className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_PLAN_2")}</label><Controller name="planId" control={control} render={({ field }) => <ManagerSearchableDropdown ariaLabel={t("COPY_PLAN_2")} ariaInvalid={Boolean(errors.planId)} ariaDescribedBy={errors.planId ? 'managermembersrenewmodal-planId-error' : undefined} dataTestId="manager_members-managermembersrenewmodal-managersearchabledropdown-1" options={plans.map((plan) => ({ value: String(plan.id), label: plan.name }))} value={field.value} onChange={field.onChange} placeholder={t("COPY_SELECT_PLAN_1")}  data-testid="manager_members-managermembersrenewmodal-searchable-dropdown-1"/>} />{errors.planId && <p id="managermembersrenewmodal-planId-error" className="text-danger text-xs mt-1">{errors.planId.message}</p>}</div>
          <div><label className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_BILLING_CYCLE_1")}</label><Controller name="billingCycle" control={control} render={({ field }) => <ManagerSearchableDropdown ariaLabel={t("COPY_BILLING_CYCLE_1")} ariaInvalid={Boolean(errors.billingCycle)} ariaDescribedBy={errors.billingCycle ? 'managermembersrenewmodal-billingCycle-error' : undefined} dataTestId="manager_members-managermembersrenewmodal-managersearchabledropdown-2" value={field.value} onChange={field.onChange} options={Object.entries(cycleLabels).map(([value, label]) => ({ value, label: label as string }))}  data-testid="manager_members-managermembersrenewmodal-searchable-dropdown-2"/>} />{errors.billingCycle && <p id="managermembersrenewmodal-billingCycle-error" className="text-danger text-xs mt-1">{errors.billingCycle.message}</p>}</div>
          {billingCycle === BILLING_CYCLE_CUSTOM && <div className="sm:col-span-2"><label htmlFor="manager-renew-custom-days" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_CUSTOM_DAYS_2")}</label><input data-testid="manager_members-manager-renew-modal-manager-renew-custom-days" id="manager-renew-custom-days" type="number" min="1" max={MANAGER_MEMBER_MAX_CUSTOM_DAYS} step="1" {...register('customDays', { valueAsNumber: true })} className="w-full border rounded-xl px-4 py-3 text-sm bg-input text-primary border-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" aria-invalid={errors.customDays ? 'true' : undefined} aria-describedby={errors.customDays ? 'managermembersrenewmodal-customDays-error' : undefined} />{errors.customDays && <p id="managermembersrenewmodal-customDays-error" className="text-danger text-xs mt-1">{errors.customDays.message}</p>}</div>}
          {planId && <div className="sm:col-span-2 bg-primary-subtle rounded-xl p-4 text-sm border border-focus flex justify-between items-center"><span className="font-semibold text-primary">{actionType === 'renew' ? t('TEXT_RENEWAL_LABEL') : t('TEXT_UPGRADE_LABEL')}{t("COPY_PRICE")}</span><span className="text-primary font-bold">{ManagerMembersFormatCurrency(calculatedPrice, ManagerEnvConfig.currencyCode, locale)}</span>{!selectedPlan && <span className="sr-only">{t("COPY_SELECTED_PLAN_DETAILS_UNAVAILABLE")}</span>}</div>}
          <div><label htmlFor="manager-renew-paid" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_AMOUNT_PAID_1")}</label><input data-testid="manager_members-manager-renew-modal-manager-renew-paid" id="manager-renew-paid" type="number" min="0" max={MANAGER_MEMBER_MAX_AMOUNT_MAJOR_UNITS} step="0.01" {...register('paidAmount', { valueAsNumber: true })} className="w-full border rounded-xl px-4 py-3 text-sm bg-input text-primary border-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" aria-invalid={errors.paidAmount ? 'true' : undefined} aria-describedby={errors.paidAmount ? 'managermembersrenewmodal-paidAmount-error' : undefined} />{errors.paidAmount && <p id="managermembersrenewmodal-paidAmount-error" className="text-danger text-xs mt-1">{errors.paidAmount.message}</p>}</div>
          <div><label className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_PAYMENT_METHOD_2")}</label><Controller name="paymentMethod" control={control} render={({ field }) => <ManagerSearchableDropdown ariaLabel={t("COPY_PAYMENT_METHOD_2")} ariaInvalid={Boolean(errors.paymentMethod)} ariaDescribedBy={errors.paymentMethod ? 'managermembersrenewmodal-paymentMethod-error' : undefined} dataTestId="manager_members-managermembersrenewmodal-managersearchabledropdown-3" value={field.value} onChange={field.onChange} options={[...paymentMethods]}  data-testid="manager_members-managermembersrenewmodal-searchable-dropdown-3"/>} />{errors.paymentMethod && <p id="managermembersrenewmodal-paymentMethod-error" className="text-danger text-xs mt-1">{errors.paymentMethod.message}</p>}</div>
          <div className="sm:col-span-2 pt-4 border-t border-border"><label htmlFor="manager-renew-expiry" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_NEW_EXPIRY_DATE")}</label><input data-testid="manager_members-manager-renew-modal-manager-renew-expiry" id="manager-renew-expiry" type="date" {...register('newExpiryDate')} disabled className="w-full border rounded-xl px-4 py-3 text-sm font-bold bg-success-bg text-success border-success opacity-50 cursor-not-allowed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /><p className="text-xs text-secondary mt-1">{t("COPY_CALCULATED_SELECTED_PLAN_BILLING_CYCLE")}</p></div>
        </div>
        <div className="flex flex-col sm:flex-row justify-end gap-3 mt-8 pt-6 border-t border-border"><button data-testid="manager_members-manager-renew-modal-close-2" type="button" onClick={handleClose} className="px-6 py-2.5 text-sm font-semibold rounded-xl border border-border text-secondary hover:bg-primary-subtle hover:text-primary motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{t("COPY_CANCEL_5")}</button><button data-testid="manager_members-manager-renew-modal-button-submit" type="submit" disabled={isSubmitting} className="min-w-40 px-8 py-2.5 rounded-xl text-sm font-bold text-primary flex items-center justify-center gap-2 disabled:opacity-70 bg-primary-subtle motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{isSubmitting ? <Loader2 size={18} strokeWidth={2} className="text-primary motion-safe:animate-spin" /> : <Save size={18} strokeWidth={2}/>} {(() => { if (isSubmitting) return t('TEXT_PROCESSING'); return (() => { if (actionType === 'renew') return t('TEXT_CONFIRM_RENEWAL'); return t('TEXT_CONFIRM_UPGRADE'); })(); })()}</button></div>
      </form>
    </div>
  </div>;
}
