// RESPONSIBILITY: Owns backend core database schema migration.
// FLOW: Migration runner → ordered schema change → reversible database state transition.
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class ManagerQueryIndexes1711000000400 implements MigrationInterface {
  name = 'ManagerQueryIndexes1711000000400';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_attendances_payload_status\" ON \"manager_attendances\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_attendances_payload_date\" ON \"manager_attendances\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_attendances_payload_userId\" ON \"manager_attendances\" ((payload ->> 'userId'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_attendances_payload_type\" ON \"manager_attendances\" ((payload ->> 'type'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_attendances_payload_month\" ON \"manager_attendances\" ((payload ->> 'month'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_communications_payload_status\" ON \"manager_communications\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_communications_payload_date\" ON \"manager_communications\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_communications_payload_channel\" ON \"manager_communications\" ((payload ->> 'channel'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_communications_payload_segment\" ON \"manager_communications\" ((payload ->> 'segment'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_dashboards_payload_status\" ON \"manager_dashboards\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_dashboards_payload_date\" ON \"manager_dashboards\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_expenses_payload_status\" ON \"manager_expenses\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_expenses_payload_date\" ON \"manager_expenses\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_expenses_payload_category\" ON \"manager_expenses\" ((payload ->> 'category'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_finances_payload_status\" ON \"manager_finances\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_finances_payload_date\" ON \"manager_finances\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_finances_payload_memberId\" ON \"manager_finances\" ((payload ->> 'memberId'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_finances_payload_paidAt\" ON \"manager_finances\" ((payload ->> 'paidAt'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_grievances_payload_status\" ON \"manager_grievances\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_grievances_payload_date\" ON \"manager_grievances\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_hrs_payload_status\" ON \"manager_hrs\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_hrs_payload_date\" ON \"manager_hrs\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_hrs_payload_staffId\" ON \"manager_hrs\" ((payload ->> 'staffId'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_hrs_payload_role\" ON \"manager_hrs\" ((payload ->> 'role'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_hrs_payload_month\" ON \"manager_hrs\" ((payload ->> 'month'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_inquiries_payload_status\" ON \"manager_inquiries\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_inquiries_payload_date\" ON \"manager_inquiries\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_libraries_payload_status\" ON \"manager_libraries\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_libraries_payload_date\" ON \"manager_libraries\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_libraries_payload_category\" ON \"manager_libraries\" ((payload ->> 'category'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_libraries_payload_difficulty\" ON \"manager_libraries\" ((payload ->> 'difficulty'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_libraries_payload_goal\" ON \"manager_libraries\" ((payload ->> 'goal'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_maintenances_payload_status\" ON \"manager_maintenances\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_maintenances_payload_date\" ON \"manager_maintenances\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_members_payload_status\" ON \"manager_members\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_members_payload_date\" ON \"manager_members\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_members_payload_gender\" ON \"manager_members\" ((payload ->> 'gender'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_members_payload_plan\" ON \"manager_members\" ((payload ->> 'plan'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_members_payload_expiryDate\" ON \"manager_members\" ((payload ->> 'expiryDate'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_notifications_payload_status\" ON \"manager_notifications\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_notifications_payload_date\" ON \"manager_notifications\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_notifications_payload_priority\" ON \"manager_notifications\" ((payload ->> 'priority'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_notifications_payload_type\" ON \"manager_notifications\" ((payload ->> 'type'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_plans_payload_status\" ON \"manager_plans\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_plans_payload_date\" ON \"manager_plans\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_profiles_payload_status\" ON \"manager_profiles\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_profiles_payload_date\" ON \"manager_profiles\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_pts_payload_status\" ON \"manager_pts\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_pts_payload_date\" ON \"manager_pts\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_pts_payload_trainerId\" ON \"manager_pts\" ((payload ->> 'trainerId'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_referrals_payload_status\" ON \"manager_referrals\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_referrals_payload_date\" ON \"manager_referrals\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_reports_payload_status\" ON \"manager_reports\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_reports_payload_date\" ON \"manager_reports\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_sales_payload_status\" ON \"manager_sales\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_sales_payload_date\" ON \"manager_sales\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_schedules_payload_status\" ON \"manager_schedules\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_schedules_payload_date\" ON \"manager_schedules\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_schedules_payload_day\" ON \"manager_schedules\" ((payload ->> 'day'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_settings_payload_status\" ON \"manager_settings\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_settings_payload_date\" ON \"manager_settings\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_stores_payload_status\" ON \"manager_stores\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_stores_payload_date\" ON \"manager_stores\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_stores_payload_category\" ON \"manager_stores\" ((payload ->> 'category'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_stores_payload_stock\" ON \"manager_stores\" ((payload ->> 'stock'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_workouts_payload_status\" ON \"manager_workouts\" ((payload ->> 'status'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_workouts_payload_date\" ON \"manager_workouts\" ((payload ->> 'date'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_workouts_payload_level\" ON \"manager_workouts\" ((payload ->> 'level'))");
    await queryRunner.query("CREATE INDEX IF NOT EXISTS \"IDX_manager_workouts_payload_difficulty\" ON \"manager_workouts\" ((payload ->> 'difficulty'))");
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_attendances_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_attendances_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_attendances_payload_userId\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_attendances_payload_type\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_attendances_payload_month\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_communications_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_communications_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_communications_payload_channel\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_communications_payload_segment\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_dashboards_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_dashboards_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_expenses_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_expenses_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_expenses_payload_category\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_finances_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_finances_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_finances_payload_memberId\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_finances_payload_paidAt\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_grievances_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_grievances_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_hrs_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_hrs_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_hrs_payload_staffId\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_hrs_payload_role\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_hrs_payload_month\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_inquiries_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_inquiries_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_libraries_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_libraries_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_libraries_payload_category\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_libraries_payload_difficulty\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_libraries_payload_goal\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_maintenances_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_maintenances_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_members_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_members_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_members_payload_gender\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_members_payload_plan\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_members_payload_expiryDate\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_notifications_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_notifications_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_notifications_payload_priority\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_notifications_payload_type\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_plans_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_plans_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_profiles_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_profiles_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_pts_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_pts_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_pts_payload_trainerId\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_referrals_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_referrals_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_reports_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_reports_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_sales_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_sales_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_schedules_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_schedules_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_schedules_payload_day\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_settings_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_settings_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_stores_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_stores_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_stores_payload_category\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_stores_payload_stock\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_workouts_payload_status\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_workouts_payload_date\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_workouts_payload_level\"');
    await queryRunner.query('DROP INDEX IF EXISTS \"IDX_manager_workouts_payload_difficulty\"');
  }
}
