// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const adminUsageHistoryPointSchema = z.object({
    date: z.string(),
    membersUsed: z.number(),
    storageUsedGb: z.number(),
    smsUsed: z.number()
});

export const adminUsageDataSchema = z.object({
    tenantId: z.string(),
    planName: z.string(),
    planTier: z.union([z.literal("Starter"), z.literal("Growth"), z.literal("Pro"), z.literal("Enterprise")]),
    billingCycleEnd: z.string(),
    monthlyPrice: z.number(),
    smsSent: z.number(),
    smsLimit: z.number(),
    databaseGb: z.number(),
    mediaGb: z.number(),
    storageLimitGb: z.number(),
    activeMembers: z.number(),
    memberLimit: z.number(),
    staffCount: z.number(),
    staffLimit: z.number(),
    branchCount: z.number(),
    branchLimit: z.number(),
    apiCallsToday: z.number(),
    apiCallsLimit: z.number(),
    usageHistory: z.array(adminUsageHistoryPointSchema)
});

export const adminUsageMetricSchema = z.object({
    label: z.string(),
    used: z.number(),
    limit: z.number(),
    unit: z.string(),
    warningThreshold: z.number(),
    criticalThreshold: z.number()
});
