// Generated by ts-to-zod
import { z } from "zod";

export const branchExpenseItemSchema = z.object({
    id: z.string(),
    label: z.string(),
    amount: z.number(),
    category: z.string(),
    date: z.string()
});

export const branchRevenueItemSchema = z.object({
    id: z.string(),
    label: z.string(),
    amount: z.number(),
    method: z.string(),
    date: z.string()
});

export const branchStaffMemberSchema = z.object({
    id: z.string(),
    name: z.string(),
    role: z.string(),
    shift: z.string(),
    status: z.union([z.literal("active"), z.literal("on-leave")])
});

export const branchStudentSchema = z.object({
    id: z.string(),
    name: z.string(),
    plan: z.string(),
    status: z.union([z.literal("active"), z.literal("expired")]),
    joinDate: z.string()
});

export const branchSchema = z.object({
    id: z.string(),
    name: z.string(),
    branchCode: z.string().optional(),
    gstNumber: z.string().optional(),
    address: z.string().optional(),
    location: z.string(),
    contactPhone: z.string().optional(),
    contactEmail: z.string().optional(),
    openingTime: z.string().optional(),
    closingTime: z.string().optional(),
    maxCapacity: z.number().optional(),
    currentOccupancy: z.number().optional(),
    equipmentCount: z.number().optional(),
    status: z.union([z.literal("active"), z.literal("inactive")]),
    revenue: z.number(),
    expenses: z.number(),
    studentsCount: z.number(),
    staffCount: z.number(),
    expenseItems: z.array(branchExpenseItemSchema).optional(),
    revenueItems: z.array(branchRevenueItemSchema).optional(),
    staffList: z.array(branchStaffMemberSchema).optional(),
    studentList: z.array(branchStudentSchema).optional()
});
