// RESPONSIBILITY: Renders the printable 80mm thermal receipt layout. Triggered by window.print() — hidden except on @media print.
import React from 'react';

export interface ManagerReceiptData {
 gymName: string;
 gymPhone: string;
 receiptNo: string;
 date: string;
 customerName: string;
 items: { name: string; qty?: number; price: number; amount: number }[];
 total: number;
 paymentMethod: string;
}

export default function ManagerThermalReceipt({ data }: { data: ManagerReceiptData | null }) {
 if (!data) return null;

 return (
 <div id="thermal-receipt" className="hidden print:block absolute top-0 left-0 w-full p-2 bg-white text-black font-mono text-xs leading-tight z-50 break-words" style={{ maxWidth: '76mm' }}>
 <div className="text-center border-black pb-2 mb-2" style={{ borderBottomWidth: '1.5px' }}>
 <h2 className="font-bold text-lg uppercase tracking-wider">{data.gymName}</h2>
 <p className="text-xs">Ph: {data.gymPhone}</p>
 <p className="font-bold mt-1 text-sm">PAYMENT RECEIPT</p>
 </div>
 
 <div className="mb-3 space-y-0.5 text-xs">
 <p><span className="font-bold">Receipt No:</span> {data.receiptNo}</p>
 <p><span className="font-bold">Date:</span> {data.date}</p>
 <p><span className="font-bold">Member:</span> {data.customerName}</p>
 </div>
 
 <table className="w-full mb-2 text-xs">
 <thead className="border-black" style={{ borderTopWidth: '1.5px', borderBottomWidth: '1.5px' }}>
 <tr>
 <th className="text-left font-bold py-1.5">Description</th>
 <th className="text-right font-bold py-1.5">Amt(Rs)</th>
 </tr>
 </thead>
 <tbody className="border-black" style={{ borderBottomWidth: '1.5px' }}>
 {data.items.map((item, i) => (
 <tr key={i}>
 <td className="py-1.5 pr-1">
 {item.name}
 {item.qty && item.qty > 1 && (
 <span className="block text-gray-800 mt-0.5" style={{ fontSize: '10px' }}>
 {item.qty} x {item.price.toLocaleString()}
 </span>
 )}
 </td>
 <td className="text-right py-1.5 align-top">{item.amount.toLocaleString()}</td>
 </tr>
 ))}
 </tbody>
 </table>
 
 <div className="flex justify-between font-bold text-base mb-2">
 <span>TOTAL:</span>
 <span>Rs. {data.total.toLocaleString()}</span>
 </div>
 
 <div className="mb-4 text-xs">
 <p><span className="font-bold">Paid via:</span> {data.paymentMethod}</p>
 </div>
 
 <div className="text-center border-black pt-2 mt-3" style={{ borderTopWidth: '1.5px' }}>
 <p className="font-bold uppercase mb-0.5 text-sm">Thank You!</p>
 <p style={{ fontSize: '10px' }}>No Refund / No Exchange</p>
 <p className="mt-0.5" style={{ fontSize: '10px' }}>Generated by GymSmart MANAGER</p>
 </div>
 </div>
 );
}
