// DATA FLOW: Manager feature UI/state → owning custom hook → approved API/query/mutation layer → observable UI state.
// RESPONSIBILITY: Notifications feature facade. URL owns filters, TanStack Query owns server state, and mutations invalidate notification queries.
"use client";
/** Coordinates the Manager / feature. */
import { useCallback, useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useConfirm } from "@/app/manager/manager_components/ManagerFeedback/ManagerConfirmProvider";
import { useManagerDebounce } from "@/app/manager/manager_infrastructure/ManagerDebounce";
import { MANAGER_GENERIC_ERROR_MESSAGE } from '@/app/manager/manager_infrastructure/ManagerErrorMessage';
import { createManagerIdempotencyKey } from '@/app/manager/manager_infrastructure/ManagerIdempotency';
import { showManagerErrorToast, showManagerSuccessToast } from "@/app/manager/manager_infrastructure/ManagerToastService";
import { notificationsApi } from "@/app/manager/notifications/notifications_api/ManagerNotificationsApi";
import type { ManagerNotificationsViewModel } from '@/app/manager/notifications/notifications_types/ManagerNotificationsViewModelTypes';

/** Orchestrates the owning Manager feature behavior while preserving its documented state boundary. */
export function useManagerNotificationsLogic(): ManagerNotificationsViewModel {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const queryClient = useQueryClient(); const { confirm } = useConfirm(); const search = searchParams.get("search") || ""; const typeFilter = searchParams.get("type") || "ALL"; const priorityFilter = searchParams.get("priority") || "ALL"; const statusFilter = searchParams.get("status") || "ALL"; const debouncedSearch = useManagerDebounce(search, 300);
  const setUrlParam = useCallback((key: string, value: string) => { const params = new URLSearchParams(searchParams.toString()); if (!value || (key !== "search" && value === "ALL")) params.delete(key); else params.set(key, value); router.replace(params.size ? `${pathname}?${params.toString()}` : pathname, { scroll: false }); }, [pathname, router, searchParams]);
  const queryParams = useMemo(() => ({ search: debouncedSearch, type: typeFilter, priority: priorityFilter, status: statusFilter }), [debouncedSearch, priorityFilter, statusFilter, typeFilter]); const listQuery = useQuery({ queryKey: ["manager", "notifications", "list", queryParams], queryFn: async () => (await notificationsApi.fetchManagerNotifications(queryParams)).data ?? { notifications: [], total: 0 } }); const kpiQuery = useQuery({ queryKey: ["manager", "notifications", "kpis"], queryFn: async () => (await notificationsApi.fetchNotificationKPIs()).data ?? null }); const invalidate = () => queryClient.invalidateQueries({ queryKey: ["manager", "notifications"] });
  const readMutation = useMutation({ mutationFn: (id: string) => notificationsApi.markNotificationRead(id), onSuccess: (response, id) => { showManagerSuccessToast(response.message, `manager-notifications-mark-read-${id}`); void invalidate(); }, onError: (error, id) => { showManagerErrorToast(error, `manager-notifications-mark-read-${id}`); } }); const readAllMutation = useMutation({ mutationFn: () => notificationsApi.markAllNotificationsRead(), onSuccess: (response) => { showManagerSuccessToast(response.message, "manager-notifications-mark-all-read"); void invalidate(); }, onError: (error) => { showManagerErrorToast(error, "manager-notifications-mark-all-read"); } }); const deleteMutation = useMutation({ mutationFn: ({ id, idempotencyKey }: { id: string; idempotencyKey: string }) => notificationsApi.deleteNotification(id, idempotencyKey), onSuccess: (response, id) => { showManagerSuccessToast(response.message, `manager-notifications-delete-${id}`); void invalidate(); }, onError: (error, id) => { showManagerErrorToast(error, `manager-notifications-delete-${id}`); } });
  const handleDelete = useCallback(async (id: string) => { const confirmed = await confirm({ title: "Delete Notification", message: "Delete this notification? This action cannot be undone.", confirmText: "Delete", cancelText: "Keep Notification", type: "danger" }); if (confirmed) await deleteMutation.mutateAsync({ id, idempotencyKey: createManagerIdempotencyKey() }); }, [confirm, deleteMutation]);
  const errorMessage = listQuery.error instanceof Error ? listQuery.error.message : kpiQuery.error instanceof Error ? kpiQuery.error.message : MANAGER_GENERIC_ERROR_MESSAGE;
  const handleMarkRead = useCallback(async (id: string) => { await readMutation.mutateAsync(id); }, [readMutation]);
  const handleMarkAllRead = useCallback(async () => { await readAllMutation.mutateAsync(); }, [readAllMutation]);
  return { notifications: listQuery.data?.notifications ?? [], kpis: kpiQuery.data ?? null, isPending: listQuery.isPending || kpiQuery.isPending, isError: listQuery.isError || kpiQuery.isError, errorMessage, saving: readMutation.isPending || readAllMutation.isPending || deleteMutation.isPending, search, setSearch: (value) => setUrlParam("search", value), typeFilter, setTypeFilter: (value) => setUrlParam("type", value), priorityFilter, setPriorityFilter: (value) => setUrlParam("priority", value), statusFilter, setStatusFilter: (value) => setUrlParam("status", value), handleMarkRead, handleMarkAllRead, handleDelete, reload: async () => { await Promise.all([listQuery.refetch(), kpiQuery.refetch()]); } };
}
