// RESPONSIBILITY: Renders ManagerLibraryExerciseModal's feature UI and orchestrates presentation through module-owned state/hooks; it does not own API transport or business rules.
'use client';
import { useRef } from 'react';
import { useManagerDialogFocusTrap } from '@/app/frontend_manager/manager_infrastructure/useManagerDialogFocusTrap';
import { Dumbbell, Loader2, Save, X } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { Controller } from 'react-hook-form';
import ManagerSearchableDropdown from '@/components/ui/manager_searchable_dropdown/ManagerSearchableDropdown';
import { MANAGER_LIBRARY_EXERCISE_CATEGORIES, MANAGER_LIBRARY_EXERCISE_DIFFICULTIES } from '@/app/frontend_manager/manager_library/manager_library_constants/ManagerLibraryExerciseConstants';
import { useManagerLibraryExerciseForm } from '@/app/frontend_manager/manager_library/manager_library_hooks/useManagerLibraryExerciseForm';


/** @description Renders the ManagerLibraryExerciseModal component for its owning Manager frontend boundary. @dependencies Local dependencies are owned by this feature module (3 documented module/import dependencies).. @edge-case Preserves error state, modal lifecycle. */
export default function ManagerLibraryExerciseModal() {
  const t = useTranslations('MANAGER_LIBRARY');

  const { form, showExerciseModal, editExerciseId, handleClose, submit } = useManagerLibraryExerciseForm();
  const { register, control, formState: { errors, isSubmitting } } = form;
  const dialogRef = useRef<HTMLDivElement>(null);
  useManagerDialogFocusTrap({ dialogRef, isOpen: showExerciseModal, onClose: handleClose });

  if (!showExerciseModal) return null;

  return (
    <div data-testid="manager_library-managerlibraryexercisemodal-presentation" className="fixed inset-0 z-40 flex items-center justify-center bg-overlay-backdrop p-4"role="presentation">
      <div data-testid="manager_library-managerlibraryexercisemodal-dialog" ref={dialogRef} className="flex max-h-screen w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-border bg-overlay shadow-dialog"role="dialog" aria-modal="true" aria-labelledby="manager-library-exercise-title">
        <div className="flex items-center justify-between border-b border-border bg-overlay px-6 py-4"><div className="flex items-center gap-2"><Dumbbell size={18} strokeWidth={2} className="text-primary" aria-hidden="true" /><h3 id="manager-library-exercise-title" className="text-lg font-bold text-primary">{editExerciseId ? t('COPY_EDIT_EXERCISE') : t('COPY_ADD_EXERCISE')}</h3></div><button data-testid="manager_library-manager-library-exercise-modal-close-1" type="button" aria-label={t("COPY_CLOSE_EXERCISE_FORM")} onClick={handleClose} className="min-h-11 min-w-11 rounded-lg text-secondary hover:bg-surface-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 hover:brightness-110"><X size={18} strokeWidth={2} className="mx-auto" aria-hidden="true"/></button></div>
        <form data-testid="manager_library-managerlibraryexercisemodal-form-1" onSubmit={submit} className="flex-1 space-y-4 overflow-y-auto p-6">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div><label htmlFor="manager-library-exercise-name" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_EXERCISE_NAME")}</label><input data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-name" id="manager-library-exercise-name" {...register('name')} aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? 'manager-library-exercise-name-error' : undefined} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" />{errors.name && <p data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-name-error" id="manager-library-exercise-name-error" role="alert" className="mt-1 text-xs text-danger">{errors.name.message}</p>}</div>
            <div><label htmlFor="manager-library-exercise-category" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_CATEGORY")}</label><select data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-category" id="manager-library-exercise-category" {...register('category')} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" aria-invalid={errors.category ? 'true' : undefined} aria-describedby={errors.category ? 'managerlibraryexercisemodal-category-error' : undefined}><option value="" data-testid="manager_library-managerlibraryexercisemodal-section-exercise">{t("COPY_SELECT_CATEGORY")}</option>{MANAGER_LIBRARY_EXERCISE_CATEGORIES.map((category) => <option key={category} value={category} data-testid="manager_library-managerlibraryexercisemodal-section-media">{category}</option>)}</select>{errors.category && <p id="managerlibraryexercisemodal-category-error" data-testid="manager_library-manager-library-exercise-modal-status-1" role="alert" className="mt-1 text-xs text-danger">{errors.category.message}</p>}</div>
            <div><label htmlFor="manager-library-exercise-muscle" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_MUSCLE_GROUPS")}</label><input data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-muscle" id="manager-library-exercise-muscle" {...register('muscleGroup')} placeholder={t("COPY_CHEST_TRICEPS")} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /><p className="mt-1 text-xs text-secondary">{t("COPY_SEPARATE_MULTIPLE_GROUPS_COMMAS")}</p></div>
            <Controller name="difficulty" control={control} render={({ field }) => <div><label htmlFor="manager-library-exercise-difficulty" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_DIFFICULTY")}</label><ManagerSearchableDropdown dataTestId="manager_library-managerlibraryexercisemodal-managersearchabledropdown-1" value={field.value} onChange={field.onChange} options={MANAGER_LIBRARY_EXERCISE_DIFFICULTIES.map((value) => ({ value, label: value }))} placeholder={t("COPY_SELECT_DIFFICULTY")}  data-testid="manager_library-managerlibraryexercisemodal-searchable-dropdown-1"/></div>} />
            <div><label htmlFor="manager-library-exercise-sets" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_SETS")}</label><input data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-sets" id="manager-library-exercise-sets" type="number" min="0" max="100" step="1" {...register('sets', { valueAsNumber: true })} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /></div>
            <div><label htmlFor="manager-library-exercise-reps" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_REPS")}</label><input data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-reps" id="manager-library-exercise-reps" type="number" min="0" max="1000" step="1" {...register('reps', { valueAsNumber: true })} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /></div>
            <div><label htmlFor="manager-library-exercise-duration" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_DURATION_MINUTES")}</label><input data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-duration" id="manager-library-exercise-duration" type="number" min="0" max="1440" step="1" {...register('duration', { valueAsNumber: true })} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /></div>
            <div><label htmlFor="manager-library-exercise-video" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_VIDEO_URL")}</label><input data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-video" id="manager-library-exercise-video" type="url" {...register('videoUrl')} className="w-full rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" aria-invalid={errors.videoUrl ? 'true' : undefined} aria-describedby={errors.videoUrl ? 'managerlibraryexercisemodal-videoUrl-error' : undefined} />{errors.videoUrl && <p id="managerlibraryexercisemodal-videoUrl-error" data-testid="manager_library-manager-library-exercise-modal-status-2" role="alert" className="mt-1 text-xs text-danger">{errors.videoUrl.message}</p>}</div>
          </div>
          <div><label htmlFor="manager-library-exercise-description" className="mb-1 block text-sm font-medium text-secondary">{t("COPY_DESCRIPTION_1")}</label><textarea data-testid="manager_library-manager-library-exercise-modal-manager-library-exercise-description" id="manager-library-exercise-description" rows={4} {...register('description')} className="w-full resize-none rounded-xl border border-border bg-input px-4 py-2.5 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" /></div>
          <Controller name="isActive" control={control} render={({ field }) => <label className="flex min-h-11 items-center gap-3 rounded-xl border border-border bg-input p-3 text-sm text-primary"><input data-testid="manager_library-manager-library-exercise-modal-input-checkbox-toggle" type="checkbox" checked={field.value} onChange={field.onChange} className="h-4 w-4 rounded border-border text-primary focus-visible:ring-primary" />{t("COPY_EXERCISE_ACTIVE")}</label>} />
          <div className="flex flex-col-reverse gap-3 border-t border-border pt-4 sm:flex-row sm:justify-end"><button data-testid="manager_library-manager-library-exercise-modal-close-2" type="button" onClick={handleClose} className="min-h-11 rounded-xl border border-border px-5 text-sm font-medium text-primary hover:bg-surface-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 hover:brightness-110">{t("COPY_CANCEL_2")}</button><button data-testid="manager_library-manager-library-exercise-modal-button-submit" type="submit" disabled={isSubmitting} className="flex min-h-11 min-w-32 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-on-primary shadow-card motion-safe:transition-all disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page motion-safe:duration-base ease-in-out motion-safe:active:scale-95 hover:brightness-110">{isSubmitting ? <Loader2 size={18} strokeWidth={2} className="motion-safe:animate-spin" aria-hidden="true"/> : <Save size={18} strokeWidth={2} aria-hidden="true"/>}{(() => { if (isSubmitting) return t('COPY_SAVING'); return (() => { if (editExerciseId) return t('COPY_UPDATE_EXERCISE'); return t('COPY_ADD_EXERCISE'); })(); })()}</button></div>
        </form>
      </div>
    </div>
  );
}
