// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const paymentSchema = z.object({
    id: z.string(),
    memberId: z.string(),
    amount: z.number(),
    method: z.string(),
    paymentMode: z.union([z.literal("CASH"), z.literal("UPI"), z.literal("CARD"), z.literal("ONLINE")]).optional(),
    gstAmount: z.number().optional(),
    taxRate: z.number().optional(),
    invoiceNumber: z.string().optional(),
    hsn_code: z.string().optional(),
    planId: z.string().optional(),
    type: z.union([z.literal("PAYMENT"), z.literal("REFUND"), z.literal("ADJUSTMENT")]).optional(),
    status: z.string(),
    notes: z.string().optional(),
    invoiceNo: z.string(),
    paidAt: z.string(),
    member: z.object({
        name: z.string(),
        email: z.string(),
        phone: z.string(),
        plan: z.object({
            name: z.string()
        }).optional()
    }).optional(),
    refundReason: z.string().optional(),
    receiptNumber: z.string().optional(),
    discountApplied: z.number().optional(),
    couponCode: z.string().optional()
});

export const financeSummarySchema = z.object({
    totalRevenue: z.number(),
    monthlyRevenue: z.number(),
    pendingAmount: z.number(),
    totalPayments: z.number(),
    totalExpenses: z.number(),
    netProfit: z.number(),
    revenueByMethod: z.object({
        UPI: z.number(),
        Cash: z.number(),
        Card: z.number(),
        NetBanking: z.number()
    }),
    monthlyData: z.array(z.object({
        month: z.string(),
        revenue: z.number()
    }))
});

export const expenseSchema = z.object({
    id: z.string(),
    amount: z.number(),
    category: z.string(),
    branchId: z.string(),
    date: z.string(),
    notes: z.string().optional(),
    recordedBy: z.string(),
    vendor: z.string().optional(),
    billNumber: z.string().optional(),
    approvedBy: z.string().optional(),
    receiptUrl: z.string().optional()
});

export const pnlPeriodSchema = z.union([z.literal("THIS_MONTH"), z.literal("LAST_MONTH"), z.literal("Q1"), z.literal("Q2"), z.literal("Q3"), z.literal("Q4"), z.literal("THIS_YEAR")]);

export const pnlStatusFilterSchema = z.union([z.literal("ALL"), z.literal("PROFITABLE"), z.literal("BREAKEVEN"), z.literal("LOSS")]);

export const pnlSortKeySchema = z.union([z.literal("branchName"), z.literal("revenue"), z.literal("expenses"), z.literal("netProfit"), z.literal("marginPct")]);

export const pnlSortDirectionSchema = z.union([z.literal("asc"), z.literal("desc")]);

export const branchPnlStatusSchema = z.union([z.literal("PROFITABLE"), z.literal("BREAKEVEN"), z.literal("LOSS")]);

export const branchRevenueBreakdownSchema = z.object({
    memberships: z.number(),
    ptSessions: z.number(),
    products: z.number(),
    other: z.number()
});

export const branchExpenseBreakdownSchema = z.object({
    rent: z.number(),
    salaries: z.number(),
    utilities: z.number(),
    maintenance: z.number(),
    marketing: z.number()
});

export const branchPnlRecordSchema = z.object({
    branchId: z.string(),
    branchName: z.string(),
    location: z.string(),
    revenue: z.number(),
    expenses: z.number(),
    netProfit: z.number(),
    marginPct: z.number(),
    status: branchPnlStatusSchema,
    momDelta: z.number(),
    revenueBreakdown: branchRevenueBreakdownSchema,
    expenseBreakdown: branchExpenseBreakdownSchema
});

export const branchPnlAggregatesSchema = z.object({
    totalRevenue: z.number(),
    totalExpenses: z.number(),
    totalNetProfit: z.number(),
    overallMarginPct: z.number(),
    profitableBranches: z.number(),
    lossMakingBranches: z.number()
});

const toastTypeSchema = z.unknown();

export const financeInitialDataSchema = z.object({
    payments: z.array(paymentSchema),
    totalPayments: z.number(),
    summary: financeSummarySchema.nullable()
});
