import {
  IsString,
  IsEmail,
  IsEnum,
  IsNumber,
  IsOptional,
  IsPositive,
  MinLength,
  MaxLength,
  Min,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { TenantStatus, SaaSPlanTier } from '../entities/gyms.entity';

export class CreateGymDto {
  @ApiProperty({ description: 'Gym / tenant business name', example: 'Iron Forge Fitness' })
  @IsString()
  @MinLength(2)
  @MaxLength(255)
  name: string;

  @ApiProperty({ description: 'Full name of the gym owner', example: 'John Carter' })
  @IsString()
  @MinLength(2)
  @MaxLength(255)
  ownerName: string;

  @ApiProperty({ description: 'Admin login email', example: 'john@ironforge.com' })
  @IsEmail()
  adminEmail: string;

  @ApiProperty({ description: 'Contact phone number', example: '+1 555-0101' })
  @IsString()
  @MinLength(5)
  @MaxLength(50)
  phone: string;

  @ApiPropertyOptional({ enum: TenantStatus, default: TenantStatus.TRIAL })
  @IsOptional()
  @IsEnum(TenantStatus)
  status?: TenantStatus;

  @ApiPropertyOptional({ enum: SaaSPlanTier, default: SaaSPlanTier.BASIC })
  @IsOptional()
  @IsEnum(SaaSPlanTier)
  plan?: SaaSPlanTier;

  @ApiPropertyOptional({ description: 'Total member count for this gym', example: 845 })
  @IsOptional()
  @IsNumber()
  @Min(0)
  memberCount?: number;

  @ApiPropertyOptional({ description: 'Monthly SaaS revenue generated by this gym in USD', example: 12500 })
  @IsOptional()
  @IsNumber()
  @Min(0)
  monthlyRevenue?: number;

  @ApiPropertyOptional({ description: 'Current ERP database schema version', example: 'v2.4.1' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  databaseVersion?: string;
}
