// RESPONSIBILITY: Registers declared runtime events so feature dependencies cannot be implicit.
// FLOW: Feature mutation â†’ CoreEventBusService.emit â†’ registry-approved event contract.

export const CORE_EVENT_REGISTRY = {
  ADMIN_ANNOUNCEMENT_CREATED: 'ADMIN.ANNOUNCEMENT.CREATED',
  ADMIN_ANNOUNCEMENT_UPDATED: 'ADMIN.ANNOUNCEMENT.UPDATED',
  ADMIN_BLACKLIST_UPDATED: 'ADMIN.BLACKLIST.UPDATED',
  ADMIN_COUPON_UPDATED: 'ADMIN.COUPON.UPDATED',
  ADMIN_MEMBER_UPDATED: 'ADMIN.MEMBER.UPDATED',
  ADMIN_STAFF_UPDATED: 'ADMIN.STAFF.UPDATED',
  ADMIN_PAYROLL_UPDATED: 'ADMIN.PAYROLL.UPDATED',
  ADMIN_SETTINGS_UPDATED: 'ADMIN.SETTINGS.UPDATED',
  ADMIN_SUBSCRIPTION_UPDATED: 'ADMIN.SUBSCRIPTION.UPDATED',
  ADMIN_EXPORT_CREATED: 'ADMIN.EXPORT.CREATED',
  ADMIN_HEALTH_ALERT_UPDATED: 'ADMIN.HEALTH_ALERT.UPDATED',
} as const;
