// RESPONSIBILITY: Renders ManagerPlansTabs's feature UI and orchestrates presentation through module-owned state/hooks; it does not own API transport or business rules.
'use client';
import { Controller } from 'react-hook-form';
import { useTranslations } from 'next-intl';
import ManagerSearchableDropdown from '@/components/ui/manager_searchable_dropdown/ManagerSearchableDropdown';
import ManagerPlansGrid from '@/app/frontend_manager/manager_plans/manager_plans_components/manager_plans_grid/ManagerPlansGrid';
import ManagerPlansToolbar from '@/app/frontend_manager/manager_plans/manager_plans_components/manager_plans_toolbar/ManagerPlansToolbar';
import { MANAGER_PLANS_TAB_IDS, MANAGER_PLANS_TAB_LABEL_KEYS } from '@/app/frontend_manager/manager_plans/manager_plans_constants/ManagerPlansTabConstants';
import { useManagerPlansMembershipForms } from '@/app/frontend_manager/manager_plans/manager_plans_hooks/useManagerPlansMembershipForms';
import { ManagerPlansMaskSensitiveData } from '@/app/frontend_manager/manager_plans/manager_plans_utils/ManagerPlansFormatters';


// DATA FLOW: TanStack Query → ManagerPlansMembershipApi → React Hook Form → mutation → Query invalidation




/** @description Renders the ManagerPlansTabs component for its owning Manager frontend boundary. @dependencies Data flow: TanStack Query → ManagerPlansMembershipApi → React Hook Form → mutation → Query invalidation. @edge-case Preserves error state. */
export default function ManagerPlansTabs() {
  const t = useTranslations('MANAGER_PLANS');

  const { plans, activeTab, handleTabChange, overview, isPending, isError, error, activateForm, renewForm, freezeForm, memberOptions, planOptions, freezeMemberOptions, formatExpiry, submitActivate, submitRenew, submitFreeze, activateMutation, renewMutation, freezeMutation } = useManagerPlansMembershipForms();

  return (
    <>
      <div className="flex flex-wrap gap-2 mb-4 bg-card border border-border p-1 rounded-xl w-fit motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1">
        {MANAGER_PLANS_TAB_IDS.map((tab, __testIdIndex0) => (
          <button className={ ["focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page", (`px-4 py-2 text-sm font-semibold rounded-lg motion-safe:transition-all ${activeTab === tab ? 'bg-primary-subtle text-primary shadow-card' : 'text-secondary hover:text-primary hover:bg-primary-subtle'} motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110`)].filter((value) => Boolean(value)).join(' ') } data-testid={`manager_plans-plans-managerplanstabs-button-activate-new-membership-${__testIdIndex0}`} key={tab} type="button" onClick={() => handleTabChange(tab)} >{t(MANAGER_PLANS_TAB_LABEL_KEYS[tab])}</button>
        ))}
      </div>

      {activeTab === 'MEMBERSHIP_ACTIVATE' && (
        <form data-testid="manager_plans-managerplanstabs-form-1" onSubmit={submitActivate} className="bg-card border border-border rounded-xl p-6">
          <h3 className="text-lg font-bold text-primary mb-4">{t("COPY_ACTIVATE_NEW_MEMBERSHIP")}</h3>
          <div className="space-y-4 max-w-md">
            <div><label htmlFor="manager-managerplanstabs-field-1" className="block text-sm font-medium mb-1">{t("COPY_SELECT_MEMBER_1")}</label><Controller control={activateForm.control} name="memberId" render={({ field }) => <ManagerSearchableDropdown ariaLabel={t("COPY_SELECT_MEMBER_1")} dataTestId="manager_plans-managerplanstabs-managersearchabledropdown-1" options={memberOptions} value={String(field.value ?? '')} onChange={(value) => field.onChange(String(value))} placeholder={t("COPY_SELECT_MEMBER_2")}  data-testid="manager_plans-managerplanstabs-searchable-dropdown-1"/>} /></div>
            <div><label htmlFor="manager-managerplanstabs-field-2" className="block text-sm font-medium mb-1">{t("COPY_SELECT_PLAN_2")}</label><Controller control={activateForm.control} name="planId" render={({ field }) => <ManagerSearchableDropdown ariaLabel={t("COPY_SELECT_PLAN_2")} dataTestId="manager_plans-managerplanstabs-managersearchabledropdown-2" options={planOptions} value={String(field.value ?? '')} onChange={(value) => field.onChange(String(value))} placeholder={t("COPY_SELECT_PLAN_1")}  data-testid="manager_plans-managerplanstabs-searchable-dropdown-2"/>} /></div>
            <div><label htmlFor="manager-plan-start-date" className="block text-sm font-medium mb-1">{t("COPY_START_DATE")}</label><input data-testid="manager_plans-manager-plans-main-manager-plan-start-date" id="manager-plan-start-date" type="date" {...activateForm.register('startDate')} className="w-full bg-input border border-border rounded-lg px-3 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div>
            <button data-testid="manager_plans-manager-plans-main-button-submit-1" type="submit" disabled={activateForm.formState.isSubmitting} className="min-w-32 w-full py-2 bg-primary-subtle text-primary font-semibold rounded-lg disabled:opacity-60 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{activateForm.formState.isSubmitting ? t('COPY_ACTIVATING') : t('CONFIRM_MEMBERSHIP_ACTIVATE')}</button>
          </div>
        </form>
      )}

      {activeTab === 'MEMBERSHIP_RENEW' && (
        <div className="bg-card border border-border rounded-xl p-6 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1">
          <h3 className="text-lg font-bold text-primary mb-4">{t("COPY_RENEW_MEMBERSHIPS")}</h3>
          {(() => { if (isPending) { return <div className="h-24 motion-safe:animate-pulse bg-input rounded-xl" aria-label={t("COPY_LOADING_RENEWALS")} />; } return (() => { if (isError) { return <p className="text-sm text-danger">{error instanceof Error ? error.message : t("TEXT_GENERIC_ERROR")}</p>; } return (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_MEMBER_NAME_1")}</th><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_CURRENT_PLAN")}</th><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_EXPIRY_DATE")}</th><th className="py-3 px-4 text-sm font-medium text-secondary text-right">{t("COPY_ACTION")}</th></tr></thead>
                <tbody className="divide-y divide-border">{(overview?.renewalCandidates ?? []).map((member, mapIndex) => <tr key={member.id}><td className="py-3 px-4 text-sm text-primary">{member.name}</td><td className="py-3 px-4 text-sm text-secondary">{member.planName}</td><td className="py-3 px-4 text-sm text-danger font-medium">{formatExpiry(member.expiryDate)}</td><td className="py-3 px-4 text-right"><button className={ ["focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page", "px-3 py-1.5 text-xs font-semibold bg-primary-subtle text-primary rounded-lg motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"].filter((value) => Boolean(value)).join(' ') } data-testid={`manager_plans-plans-managerplanstabs-button-member-name-${mapIndex}`} type="button" onClick={() => renewForm.setValue('memberId', member.id)} >{t("COPY_RENEW_NOW")}</button></td></tr>)}</tbody></table>
              <form data-testid="manager_plans-managerplanstabs-form-2" onSubmit={submitRenew} className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-4 max-w-xl"><Controller control={renewForm.control} name="memberId" render={({ field }) => <ManagerSearchableDropdown dataTestId="manager_plans-managerplanstabs-managersearchabledropdown-3" options={memberOptions} value={String(field.value ?? '')} onChange={(value) => field.onChange(String(value))} placeholder={t("COPY_MEMBER")}  data-testid="manager_plans-managerplanstabs-searchable-dropdown-3"/>} /><Controller control={renewForm.control} name="planId" render={({ field }) => <ManagerSearchableDropdown dataTestId="manager_plans-managerplanstabs-managersearchabledropdown-4" options={planOptions} value={String(field.value ?? '')} onChange={(value) => field.onChange(String(value))} placeholder={t("COPY_PLAN_1")}  data-testid="manager_plans-managerplanstabs-searchable-dropdown-4"/>} /><input data-testid="manager_plans-manager-plans-main-input-date-1" type="date" aria-label={t("COPY_NEW_EXPIRY_DATE")} {...renewForm.register('newExpiryDate')} className="bg-input border border-border rounded-lg px-3 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /><button data-testid="manager_plans-manager-plans-main-button-submit-2" type="submit" disabled={renewForm.formState.isSubmitting} className="min-w-32 bg-primary-subtle text-primary rounded-lg px-3 py-2 text-sm font-semibold disabled:opacity-60 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{renewForm.formState.isSubmitting ? t('COPY_RENEWING') : t('COPY_SUBMIT_RENEWAL')}</button></form>
            </div>
          ); })(); })()}
        </div>
      )}

      {activeTab === 'MEMBERSHIP_FREEZE' && (
        <form data-testid="manager_plans-managerplanstabs-form-3" onSubmit={submitFreeze} className="bg-card border border-border rounded-xl p-6"><h3 className="text-lg font-bold text-primary mb-4">{t("COPY_FREEZE_MEMBERSHIP")}</h3><div className="space-y-4 max-w-md"><Controller control={freezeForm.control} name="memberId" render={({ field }) => <ManagerSearchableDropdown dataTestId="manager_plans-managerplanstabs-managersearchabledropdown-5" options={freezeMemberOptions} value={String(field.value ?? '')} onChange={(value) => field.onChange(String(value))} placeholder={t("COPY_SELECT_ACTIVE_MEMBER")}  data-testid="manager_plans-managerplanstabs-searchable-dropdown-5"/>} /><div className="flex gap-4"><input data-testid="manager_plans-manager-plans-main-input-date-2" aria-label={t("COPY_FREEZE")} type="date" {...freezeForm.register('freezeFrom')} className="flex-1 bg-input border border-border rounded-lg px-3 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /><input data-testid="manager_plans-manager-plans-main-input-date-3" aria-label={t("COPY_FREEZE_UNTIL")} type="date" {...freezeForm.register('freezeUntil')} className="flex-1 bg-input border border-border rounded-lg px-3 py-2 text-sm text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div><button data-testid="manager_plans-manager-plans-main-button-submit-3" type="submit" disabled={freezeForm.formState.isSubmitting} className="min-w-32 w-full py-2 bg-info text-on-info font-semibold rounded-lg disabled:opacity-60 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{freezeForm.formState.isSubmitting ? t('COPY_APPLYING') : t('CONFIRM_MEMBERSHIP_FREEZE')}</button></div></form>
      )}

      {activeTab === 'EXPIRY_CHECK' && (
        <div className="bg-card border border-border rounded-xl p-6 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1"><h3 className="text-lg font-bold text-primary mb-4">{t("COPY_EXPIRING_MEMBERSHIPS")}</h3>{(() => { if (isPending) { return <div className="h-24 motion-safe:animate-pulse bg-input rounded-xl" aria-label={t("COPY_LOADING_EXPIRY_DATA")} />; } return (() => { if (isError) { return <p className="text-sm text-danger">{error instanceof Error ? error.message : t("TEXT_GENERIC_ERROR")}</p>; } return <div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_MEMBER_NAME_2")}</th><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_PHONE")}</th><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_PLAN_2")}</th><th className="py-3 px-4 text-sm font-medium text-secondary">{t("COPY_EXPIRES")}</th></tr></thead><tbody className="divide-y divide-border">{(overview?.memberOptions ?? []).map(member => <tr key={member.id}><td className="py-3 px-4 text-sm text-primary">{member.name}</td><td className="py-3 px-4 text-sm text-secondary">{ManagerPlansMaskSensitiveData(member.phone, 'phone')}</td><td className="py-3 px-4 text-sm text-secondary">{member.planName}</td><td className="py-3 px-4 text-sm text-danger font-medium">{formatExpiry(member.expiryDate)}</td></tr>)}</tbody></table></div>; })(); })()}</div>
      )}

      {activeTab === 'VIEW_PLANS' && (<><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">{[{ label: t("COPY_TOTAL_PLANS"), value: plans.length, colorClass: 'text-primary' }, { label: t("COPY_ACTIVE_PLANS"), value: plans.filter((p) => p.isActive).length, colorClass: 'text-success' }, { label: t("COPY_INACTIVE_PLANS"), value: plans.filter((p) => !p.isActive).length, colorClass: 'text-danger' }].map((stat) => <div key={stat.label} className="bg-card border border-border rounded-xl p-4 flex items-center gap-4 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1"><p className="text-sm text-secondary">{stat.label}</p><p className={`text-kpi font-bold ml-auto ${stat.colorClass}`}>{stat.value}</p></div>)}</div><ManagerPlansToolbar /><ManagerPlansGrid /></>)}
    </>
  );
}
