// RESPONSIBILITY: Persists master authentication security-audit records generated by the auth flow.
// FLOW: Auth service → auth audit repository → master TypeORM repository → CoreAuthAuditLogEntity.

import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import type { Repository } from 'typeorm';
import { CoreAuthAuditLogEntity } from '@/backend_trainer/core/database/core-auth-audit-log.entity';

@Injectable()
export class CoreAuthAuditRepository {
  constructor(@InjectRepository(CoreAuthAuditLogEntity, 'master') private readonly repository: Repository<CoreAuthAuditLogEntity>) {}

  /** Records the security event raised when repeated login failures trigger lockout. */
  async createLoginLockAudit(userId: string | null, identifierHash: string): Promise<void> {
    const entity = this.repository.create({ userId, action: 'LOGIN_LOCKED', identifierHash, createdAt: new Date() });
    await this.repository.insert(entity);
  }
}
