// RESPONSIBILITY: Creates the versioned tenant PostgreSQL schema with explicit names, constraints, indexes, and soft deletes.
// FLOW: Tenant provisioning → CoreTenantSchemaMigration → tables/enums/indexes/foreign keys.

import { MigrationInterface, QueryRunner } from 'typeorm';

export class CoreTenantSchemaMigration implements MigrationInterface {
  name = 'CoreTenantSchemaMigration_2026_09_22';

  /** Creates all Trainer tenant tables and database-level invariants. */
  async up(q: QueryRunner): Promise<void> {
    const statements = [
      `CREATE EXTENSION IF NOT EXISTS pgcrypto`,
      `DO $$ BEGIN CREATE TYPE member_status_enum AS ENUM ('ACTIVE','INACTIVE','EXPIRED','PENDING'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE member_gender_enum AS ENUM ('MALE','FEMALE','OTHER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE member_billing_cycle_enum AS ENUM ('Monthly','Quarterly','Yearly'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE member_progress_status_enum AS ENUM ('Good','Average','Needs Attention'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE diet_goal_enum AS ENUM ('Weight Loss','Maintenance','Muscle Gain'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE trainer_profile_role_enum AS ENUM ('TRAINER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE attendance_record_type_enum AS ENUM ('MEMBER','STAFF'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE attendance_check_in_method_enum AS ENUM ('MANUAL','QR','SELF'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE schedule_day_enum AS ENUM ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE leave_type_enum AS ENUM ('Sick Leave','Casual Leave','Emergency','Personal','Other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE leave_status_enum AS ENUM ('PENDING','APPROVED','REJECTED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE session_type_enum AS ENUM ('PT','Group'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE session_status_enum AS ENUM ('Upcoming','Completed','No Show'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE session_recurrence_enum AS ENUM ('none','weekly','biweekly'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE notification_type_enum AS ENUM ('MEMBER','WORKOUT','ATTENDANCE','SYSTEM'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE earnings_history_type_enum AS ENUM ('Session','Bonus','Commission'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE earnings_status_enum AS ENUM ('pending','processing','settled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE workout_level_enum AS ENUM ('Beginner','Intermediate','Advanced'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `DO $$ BEGIN CREATE TYPE exercise_difficulty_enum AS ENUM ('Beginner','Intermediate','Advanced'); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `CREATE TABLE IF NOT EXISTS trainer_profiles (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_profiles PRIMARY KEY(id), user_id uuid NOT NULL, name varchar(160) NOT NULL, email varchar(320) NOT NULL, phone varchar(32) NOT NULL, role trainer_profile_role_enum NOT NULL, specialization jsonb NOT NULL DEFAULT '[]', joined_at date NOT NULL, avatar_initial varchar(4) NOT NULL, certifications jsonb, specialties jsonb, emergency_contact jsonb, bio text, experience_years int, profile_photo_url text, languages_spoken jsonb, commission_rate numeric(5,2) NOT NULL DEFAULT 0, commission_tier varchar(64) NOT NULL DEFAULT 'Standard', bank_account_masked varchar(32), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT UQ_trainer_profiles_user_id UNIQUE(user_id))`,
      `CREATE TABLE IF NOT EXISTS trainer_members (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_members PRIMARY KEY(id), name varchar(160) NOT NULL, email varchar(320) NOT NULL, phone varchar(32) NOT NULL, gender member_gender_enum NOT NULL, address text, branch varchar(160) NOT NULL, plan_id uuid NOT NULL, plan_name varchar(160), plan_tier varchar(64), billing_cycle member_billing_cycle_enum NOT NULL, status member_status_enum NOT NULL, join_date timestamptz NOT NULL, expiry_date timestamptz NOT NULL, photo text, age int, height_cm numeric(7,2), weight_kg numeric(7,2), last_workout timestamptz, progress_status member_progress_status_enum, assigned_trainer_id uuid, assigned_trainer_name varchar(160), is_pt boolean, assigned_diet_id uuid, assigned_workout_id uuid, assigned_diet_snapshot jsonb, assigned_workout_snapshot jsonb, fitness_level varchar(64), target_weight_kg numeric(7,2), bmi numeric(7,2), medical_restrictions text, fitness_goal varchar(160), days_since_last_check_in int, emergency_contact text, blood_group varchar(8), medical_history text, membership_number varchar(120), assessment jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_members_status CHECK (status IN ('ACTIVE','INACTIVE','EXPIRED','PENDING')), CONSTRAINT CHK_trainer_members_progress_status CHECK (progress_status IS NULL OR progress_status IN ('Good','Average','Needs Attention')))` ,
      `CREATE TABLE IF NOT EXISTS trainer_member_notes (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_member_notes PRIMARY KEY(id), member_id uuid NOT NULL, text text NOT NULL, author_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_diet_plans (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_diet_plans PRIMARY KEY(id), name varchar(160) NOT NULL, goal diet_goal_enum NOT NULL, calories int, protein numeric(7,2), carbs numeric(7,2), fats numeric(7,2), description text, meals jsonb NOT NULL DEFAULT '[]', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_diet_plan_assignments (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_diet_plan_assignments PRIMARY KEY(id), member_id uuid NOT NULL, diet_plan_id uuid NOT NULL, assigned_by uuid NOT NULL, assigned_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_workouts (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_workouts PRIMARY KEY(id), trainer_id uuid, name varchar(160) NOT NULL, level workout_level_enum NOT NULL, days int NOT NULL, exercises_count int NOT NULL, focus varchar(160) NOT NULL, duration varchar(64) NOT NULL, tags jsonb NOT NULL DEFAULT '[]', goal varchar(160), start_date date, end_date date, instructions text, assigned_member_id uuid, is_active boolean NOT NULL DEFAULT true, workout_exercises jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_workouts_days_positive CHECK (days>0), CONSTRAINT CHK_trainer_workouts_exercises_count_positive CHECK (exercises_count>0))`,
      `CREATE TABLE IF NOT EXISTS trainer_exercises (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_exercises PRIMARY KEY(id), trainer_id uuid, name varchar(160) NOT NULL, category varchar(120), muscle_group jsonb, equipment varchar(120), difficulty exercise_difficulty_enum NOT NULL, instructions text, video_url text, image_url text, is_active boolean NOT NULL DEFAULT true, sets int, reps varchar(64), duration varchar(64), description text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_attendance_records (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_attendance_records PRIMARY KEY(id), type attendance_record_type_enum NOT NULL, date date NOT NULL, check_in timestamptz, check_out timestamptz, duration_minutes int, check_in_method attendance_check_in_method_enum, notes text, staff_id uuid, member_id uuid, created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_attendance_records_duration CHECK (duration_minutes IS NULL OR duration_minutes>=0))`,
      `CREATE TABLE IF NOT EXISTS trainer_progress_entries (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_progress_entries PRIMARY KEY(id), member_id uuid NOT NULL, date date NOT NULL, weight_kg numeric(7,2) NOT NULL, height_cm numeric(7,2) NOT NULL, bmi numeric(7,2) NOT NULL, body_fat_percent numeric(7,2), muscle_mass_kg numeric(7,2), chest_cm numeric(7,2), waist_cm numeric(7,2), hip_cm numeric(7,2), notes text, recorded_by varchar(160) NOT NULL, blood_pressure varchar(32), resting_heart_rate int, vo2_max numeric(7,2), progress_photos jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_weekly_availability (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_weekly_availability PRIMARY KEY(id), trainer_id uuid NOT NULL, day schedule_day_enum NOT NULL, is_available boolean NOT NULL, start_time time NOT NULL, end_time time NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_weekly_availability_day CHECK (day IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')), )`,
      `CREATE TABLE IF NOT EXISTS trainer_leave_requests (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_leave_requests PRIMARY KEY(id), trainer_id uuid NOT NULL, start_date date NOT NULL, end_date date NOT NULL, reason text NOT NULL, leave_type leave_type_enum NOT NULL, status leave_status_enum NOT NULL, manager_notes text, total_days int, attachment_url text, approved_by uuid, rejected_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_leave_requests_dates CHECK (end_date>=start_date))`,
      `CREATE TABLE IF NOT EXISTS trainer_sessions (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_sessions PRIMARY KEY(id), trainer_id uuid NOT NULL, title varchar(180) NOT NULL, type session_type_enum NOT NULL, time varchar(64) NOT NULL, session_date date NOT NULL, duration varchar(64) NOT NULL, status session_status_enum NOT NULL, attendees int NOT NULL DEFAULT 0, max_attendees int, member_id uuid, is_online boolean NOT NULL DEFAULT false, enrolled_members jsonb, session_notes text, location text, room text, trainer_notes text, member_rating numeric(4,2), cancellation_reason text, recurrence_rule session_recurrence_enum, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_notifications (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_notifications PRIMARY KEY(id), trainer_id uuid NOT NULL, title varchar(180) NOT NULL, message text NOT NULL, is_read boolean NOT NULL DEFAULT false, type notification_type_enum, action_url text, related_entity_id uuid, related_entity_type varchar(64), metadata jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
      `CREATE TABLE IF NOT EXISTS trainer_notification_preferences (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_notification_preferences PRIMARY KEY(id), trainer_id uuid NOT NULL, email boolean NOT NULL DEFAULT true, push boolean NOT NULL DEFAULT true, sms boolean NOT NULL DEFAULT false, session_reminders boolean NOT NULL DEFAULT true, member_updates boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT UQ_trainer_notification_preferences_trainer_id UNIQUE(trainer_id))`,
      `CREATE TABLE IF NOT EXISTS trainer_earnings_payouts (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_earnings_payouts PRIMARY KEY(id), trainer_id uuid NOT NULL, period varchar(120) NOT NULL, amount_minor bigint NOT NULL, status earnings_status_enum NOT NULL, due_date date NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_earnings_payouts_amount CHECK(amount_minor>=0))`,
      `CREATE TABLE IF NOT EXISTS trainer_earnings_history (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_trainer_earnings_history PRIMARY KEY(id), trainer_id uuid NOT NULL, external_reference varchar(120) NOT NULL, event_date date NOT NULL, type earnings_history_type_enum NOT NULL, description text NOT NULL, amount_minor bigint NOT NULL, status earnings_status_enum NOT NULL, session_id uuid, tds_deducted_minor bigint, net_payout_minor bigint, invoice_number varchar(120), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, CONSTRAINT CHK_trainer_earnings_history_amount CHECK(amount_minor>=0), CONSTRAINT CHK_trainer_earnings_history_tds_nonnegative CHECK(tds_deducted_minor IS NULL OR tds_deducted_minor>=0), CONSTRAINT CHK_trainer_earnings_history_net_nonnegative CHECK(net_payout_minor IS NULL OR net_payout_minor>=0))`,
      `CREATE TABLE IF NOT EXISTS audit_logs (id uuid NOT NULL DEFAULT gen_random_uuid(), CONSTRAINT PK_audit_logs PRIMARY KEY(id), actor_id uuid NOT NULL, actor_role varchar(32) NOT NULL, action varchar(120) NOT NULL, entity_type varchar(120) NOT NULL, entity_id varchar(120) NOT NULL, old_value jsonb, new_value jsonb, ip_address varchar(64), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz)`,
    ];
    for (const sql of statements) await q.query(sql);

    const indexes = [
      `CREATE INDEX IF NOT EXISTS IDX_trainer_members_assigned_trainer_id ON trainer_members(assigned_trainer_id)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_members_status ON trainer_members(status)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_members_join_date ON trainer_members(join_date)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_members_expiry_date ON trainer_members(expiry_date)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_members_plan_id ON trainer_members(plan_id)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_members_assigned_diet_id ON trainer_members(assigned_diet_id)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_members_assigned_workout_id ON trainer_members(assigned_workout_id)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_member_notes_member_id_created_at ON trainer_member_notes(member_id,created_at)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_diet_plan_assignments_member_id ON trainer_diet_plan_assignments(member_id)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_diet_plan_assignments_diet_plan_id ON trainer_diet_plan_assignments(diet_plan_id)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_workouts_trainer_id ON trainer_workouts(trainer_id)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_workouts_assigned_member_id ON trainer_workouts(assigned_member_id)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_exercises_trainer_id ON trainer_exercises(trainer_id)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_exercises_difficulty ON trainer_exercises(difficulty)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_attendance_records_staff_id_date ON trainer_attendance_records(staff_id,date)`, `CREATE UNIQUE INDEX IF NOT EXISTS UQ_trainer_attendance_open_staff ON trainer_attendance_records(staff_id) WHERE type='STAFF' AND check_out IS NULL AND deleted_at IS NULL`, `CREATE INDEX IF NOT EXISTS IDX_trainer_attendance_records_member_id_date ON trainer_attendance_records(member_id,date)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_attendance_records_created_by_date ON trainer_attendance_records(created_by,date)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_progress_entries_member_id_date ON trainer_progress_entries(member_id,date)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_weekly_availability_trainer_id ON trainer_weekly_availability(trainer_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS UQ_trainer_weekly_availability_active_trainer_day ON trainer_weekly_availability(trainer_id,day) WHERE deleted_at IS NULL`, `CREATE INDEX IF NOT EXISTS IDX_trainer_leave_requests_trainer_id_start_date ON trainer_leave_requests(trainer_id,start_date)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_leave_requests_status_start_date ON trainer_leave_requests(status,start_date)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_sessions_trainer_id_session_date ON trainer_sessions(trainer_id,session_date)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_sessions_status_date ON trainer_sessions(status,session_date)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_notifications_trainer_id_is_read ON trainer_notifications(trainer_id,is_read)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_notifications_trainer_id_created_at ON trainer_notifications(trainer_id,created_at)`,
      `CREATE INDEX IF NOT EXISTS IDX_trainer_earnings_history_trainer_id_event_date ON trainer_earnings_history(trainer_id,event_date)`, `CREATE INDEX IF NOT EXISTS IDX_trainer_earnings_payouts_trainer_id_due_date ON trainer_earnings_payouts(trainer_id,due_date)`, `CREATE INDEX IF NOT EXISTS IDX_audit_logs_actor_id_created_at ON audit_logs(actor_id,created_at)`,
    ];
    for (const sql of indexes) await q.query(sql);

    const fks = [
      `ALTER TABLE trainer_member_notes ADD CONSTRAINT FK_trainer_member_notes_trainer_members_member_id FOREIGN KEY(member_id) REFERENCES trainer_members(id)`,
      `ALTER TABLE trainer_attendance_records ADD CONSTRAINT FK_trainer_attendance_records_trainer_members_member_id FOREIGN KEY(member_id) REFERENCES trainer_members(id)`,
      `ALTER TABLE trainer_diet_plan_assignments ADD CONSTRAINT FK_trainer_diet_plan_assignments_trainer_members_member_id FOREIGN KEY(member_id) REFERENCES trainer_members(id)`,
      `ALTER TABLE trainer_diet_plan_assignments ADD CONSTRAINT FK_trainer_diet_plan_assignments_trainer_diet_plans_diet_plan_id FOREIGN KEY(diet_plan_id) REFERENCES trainer_diet_plans(id)`,
      `ALTER TABLE trainer_progress_entries ADD CONSTRAINT FK_trainer_progress_entries_trainer_members_member_id FOREIGN KEY(member_id) REFERENCES trainer_members(id)`,
      `ALTER TABLE trainer_sessions ADD CONSTRAINT FK_trainer_sessions_trainer_members_member_id FOREIGN KEY(member_id) REFERENCES trainer_members(id)`,
      `ALTER TABLE trainer_earnings_history ADD CONSTRAINT FK_trainer_earnings_history_trainer_sessions_session_id FOREIGN KEY(session_id) REFERENCES trainer_sessions(id)`,
      `ALTER TABLE trainer_members ADD CONSTRAINT FK_trainer_members_trainer_diet_plans_assigned_diet_id FOREIGN KEY(assigned_diet_id) REFERENCES trainer_diet_plans(id)`,
      `ALTER TABLE trainer_members ADD CONSTRAINT FK_trainer_members_trainer_workouts_assigned_workout_id FOREIGN KEY(assigned_workout_id) REFERENCES trainer_workouts(id)`,
    ];
    for (const sql of fks) {
      const exists = await q.query(`SELECT 1 FROM pg_constraint WHERE conname = $1`, [sql.match(/CONSTRAINT\s+(\S+)/i)?.[1]]);
      if (!exists.length) await q.query(sql);
    }
  }

  /** Drops tenant feature tables during an explicit rollback or isolated test teardown. */
  async down(q: QueryRunner): Promise<void> {
    for (const table of ['audit_logs','trainer_earnings_history','trainer_earnings_payouts','trainer_notification_preferences','trainer_notifications','trainer_sessions','trainer_leave_requests','trainer_weekly_availability','trainer_progress_entries','trainer_attendance_records','trainer_exercises','trainer_workouts','trainer_diet_plan_assignments','trainer_diet_plans','trainer_member_notes','trainer_members','trainer_profiles']) await q.query(`DROP TABLE IF EXISTS ${table} CASCADE`);
  }
}
