// RESPONSIBILITY: Resolves tenant-specific TypeORM DataSources with bounded pooling and one-time schema migration readiness.
// FLOW: Trusted tenant context → master tenant record → tenant DataSource → repository.

import { Injectable } from '@nestjs/common'; import { DataSource, type EntityTarget, type ObjectLiteral, Repository, IsNull } from 'typeorm';
import { InjectDataSource } from '@nestjs/typeorm'; import { CoreNotFoundException } from '@/backend_trainer/core/errors/core-not-found.exception';
import { CoreRequestContext } from '@/backend_trainer/core/context/core-request-context'; import { CoreConfigService } from '@/backend_trainer/core/config/core-config.service'; import { CoreTenantEntity } from '@/backend_trainer/core/database/core-tenant.entity'; import { CORE_TIMEOUTS } from '@/backend_trainer/core/config/core-timeout.config'; import * as entities from '@/backend_trainer/core/database/core-tenant-entities';
import { CoreTenantSchemaMigration } from '@/backend_trainer/core/database/core-tenant-schema.migration';
import { CoreTenantSchemaRepair20260922Migration } from '@/backend_trainer/core/database/core-tenant-schema-repair-2026-09-22.migration';
import { CoreDomainException } from '@/backend_trainer/core/errors/core-domain.exception';
@Injectable() export class CoreTenantDataSourceResolver { private readonly cache=new Map<string,DataSource>(); private readonly pending=new Map<string,Promise<DataSource>>(); constructor(private readonly config:CoreConfigService,@InjectDataSource('master') private readonly master:DataSource) {} /** Returns an authorized tenant DataSource, initializing it once per tenant ID. */ async getDataSource():Promise<DataSource>{ const tenantId=CoreRequestContext.getTenantIdOrThrow(); const cached=this.cache.get(tenantId); if(cached) return cached; const pending=this.pending.get(tenantId); if(pending) return pending; const configuredPoolMax = this.config.getTenantPoolMax();
    const totalBudget = this.config.getTenantTotalPoolMax();
    const reserved = (this.cache.size + this.pending.size) * configuredPoolMax;
    if (reserved + configuredPoolMax > totalBudget) throw new CoreDomainException('CORE.TENANT.POOL_BUDGET_EXCEEDED', 'Tenant connection pool budget exceeded.', 503);
    const initialization=this.initializeTenantDataSource(tenantId); this.pending.set(tenantId,initialization); try{return await initialization;} finally{this.pending.delete(tenantId);} }
  /** Initializes one tenant DataSource after master authorization and validation. */
  private async initializeTenantDataSource(tenantId:string):Promise<DataSource>{ const tenant=await this.master.getRepository(CoreTenantEntity).findOneBy({id:tenantId,isActive:true,deletedAt: IsNull()}); if(!tenant) throw new CoreNotFoundException('CORE.TENANT', tenantId); const ds=new DataSource({type:'postgres',...this.config.getTenantDatabase(),database:tenant.databaseName,entities:Object.values(entities),synchronize:false,migrations:[CoreTenantSchemaMigration,CoreTenantSchemaRepair20260922Migration],extra:{max:this.config.getTenantPoolMax(),connectionTimeoutMillis:30000,idleTimeoutMillis:10000,statement_timeout:CORE_TIMEOUTS.databaseMs}});
    try { await ds.initialize(); await ds.runMigrations(); this.cache.set(tenantId,ds); return ds; } catch (error) { await ds.destroy().catch(() => undefined); throw error; } } /** Resolves a tenant repository after auth and tenant authorization. */ async getRepository<T extends ObjectLiteral>(target:EntityTarget<T>):Promise<Repository<T>>{ return (await this.getDataSource()).getRepository(target); } /** Destroys all tenant pools for graceful application shutdown. */ async closeAll():Promise<void>{ await Promise.all([...this.cache.values()].map((ds)=>ds.destroy().catch(()=>undefined))); this.cache.clear(); } }
