// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const memberStatusSchema = z.union([z.literal("active"), z.literal("expired"), z.literal("pending"), z.literal("frozen")]);

export const adminMemberSchema = z.object({
    id: z.string(),
    name: z.string(),
    email: z.string(),
    phone: z.string(),
    branchId: z.string(),
    branchName: z.string(),
    planName: z.string(),
    status: memberStatusSchema,
    joinDate: z.string(),
    expiryDate: z.string(),
    pendingAmount: z.number(),
    gender: z.union([z.literal("Male"), z.literal("Female"), z.literal("Other")]),
    referralSource: z.string().optional(),
    photo: z.string().optional(),
    lastCheckIn: z.string().optional(),
    totalVisits: z.number().optional(),
    dateOfBirth: z.string().optional(),
    address: z.string().optional()
});

export const adminMembersSummarySchema = z.object({
    totalMembers: z.number(),
    activeMembers: z.number(),
    expiredMembers: z.number(),
    pendingMembers: z.number(),
    expiringThisWeek: z.number(),
    expiringThisMonth: z.number(),
    totalOutstanding: z.number(),
    newThisMonth: z.number()
});

export const adminMembersContextTypeSchema = z.object({
    members: z.array(adminMemberSchema),
    summary: adminMembersSummarySchema.nullable(),
    status: statusSchema,
    error: z.string(),
    search: z.string(),
    setSearch: z.function({ input: [z.string()], output: z.void() }),
    statusFilter: z.union([memberStatusSchema, z.literal("all")]),
    setStatusFilter: z.function({ input: [z.union([memberStatusSchema, z.literal("all")])], output: z.void() }),
    branchFilter: z.string(),
    setBranchFilter: z.function({ input: [z.string()], output: z.void() }),
    expiryFilter: z.union([z.literal("all"), z.literal("this_week"), z.literal("this_month")]),
    setExpiryFilter: z.function({ input: [z.union([z.literal("all"), z.literal("this_week"), z.literal("this_month")])], output: z.void() }),
    currentPage: z.number(),
    setCurrentPage: z.function({ input: [z.number()], output: z.void() }),
    selectedMember: adminMemberSchema.nullable(),
    setSelectedMember: z.function({ input: [adminMemberSchema.nullable()], output: z.void() }),
    loadAll: z.function({ input: [], output: z.custom<Promise<void>>(() => z.promise(z.void())) })
});
