// RESPONSIBILITY: Renders the Superadmin offboarding queue and provides a working CSV export for visible records.
'use client';
import { Download } from 'lucide-react';
import { displayValue } from '@/lib/formatters';
import SuperadminOffboardingQueueEmptyState from '@/app/superadmin/offboarding/offboarding_components/SuperadminOffboardingQueueEmptyState';
import SuperadminTooltip from '@/app/superadmin/superadmin_components/SuperadminShared/SuperadminTooltip';
import SuperadminPanel from '@/app/superadmin/superadmin_components/SuperadminShared/SuperadminPanel';
import { getSuperadminOffboardingStatusBadgeClasses } from '@/app/superadmin/offboarding/offboarding_utils/SuperadminOffboardingStatusBadgeConfig';
import type { SuperadminOffboardingSectionProps } from '@/app/superadmin/offboarding/offboarding_types/SuperadminOffboardingTypes';
export default function SuperadminOffboardingQueuePanel({ data }: SuperadminOffboardingSectionProps) { const handleExport=()=>{const csv=['Tenant,Owner,Stage,Cancelled,Grace Ends,Export Size',...data.queue.map(q=>[q.tenant,q.owner,q.status,q.cancelledAt,q.graceEndsAt,q.exportSize].map(v=>`"${String(v??'')}"`).join(','))].join('\n');const href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=href;link.download='superadmin-offboarding-queue.csv';link.click();URL.revokeObjectURL(href);}; return <SuperadminPanel title="Offboarding Queue" description="Each record shows its current data lifecycle stage.">{data.queue.length===0?<SuperadminOffboardingQueueEmptyState/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase text-secondary"><th className="px-3 py-3">Tenant</th><th className="px-3 py-3">Stage</th><th className="px-3 py-3">Cancelled</th><th className="px-3 py-3">Grace Ends</th><th className="px-3 py-3">Export Size</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{data.queue.map(q=><tr key={q.id} className="border-b border-border"><td className="px-3 py-3"><SuperadminTooltip content={q.tenant}><p className="max-w-52 truncate font-medium text-primary">{q.tenant}</p></SuperadminTooltip><SuperadminTooltip content={displayValue(q.owner,'—')}><p className="max-w-52 truncate text-xs text-secondary">{displayValue(q.owner,'—')}</p></SuperadminTooltip></td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${getSuperadminOffboardingStatusBadgeClasses(q.status)}`}>{q.status.replaceAll('_',' ')}</span></td><td className="px-3 py-3 text-secondary">{displayValue(q.cancelledAt,'—')}</td><td className="px-3 py-3 text-secondary">{displayValue(q.graceEndsAt,'—')}</td><td className="px-3 py-3 text-primary">{displayValue(q.exportSize,'—')}</td><td className="px-3 py-3"><button type="button" onClick={handleExport} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-xs font-medium text-primary"><Download size={18}/>Export</button></td></tr>)}</tbody></table></div>}</SuperadminPanel>; }
