import { z } from 'zod';
// Generated by ts-to-zod


export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const planSchema = z.object({
    id: z.string(),
    name: z.string(),
    tier: z.string(),
    price1Month: z.number(),
    price3Month: z.number(),
    price6Month: z.number(),
    price12Month: z.number(),
    features: z.array(z.string()),
    isActive: z.boolean(),
    freezeAllowed: z.boolean().optional(),
    joiningFee: z.number().optional(),
    ptSessionsIncluded: z.number().optional(),
    taxRate: z.number().optional()
});

const toastTypeSchema = z.unknown();

const planFormValuesSchema = z.unknown();

export const plansInitialDataSchema = z.object({
    plans: z.array(planSchema)
});

export const plansContextTypeSchema = z.object({
    plans: z.array(planSchema),
    totalItems: z.number(),
    totalPages: z.number(),
    status: statusSchema,
    saving: z.boolean(),
    toast: z.object({
        message: z.string(),
        type: toastTypeSchema
    }).nullable(),
    search: z.string(),
    setSearch: z.function(z.tuple([z.string()]), z.void()),
    tierFilter: z.string(),
    setTierFilter: z.function(z.tuple([z.string()]), z.void()),
    currentPage: z.number(),
    setCurrentPage: z.function(z.tuple([z.number()]), z.void()),
    showModal: z.boolean(),
    setShowModal: z.function(z.tuple([z.boolean()]), z.void()),
    editId: z.string().nullable(),
    form: planFormValuesSchema,
    setForm: z.function(z.tuple([planFormValuesSchema]), z.void()),
    showToast: z.function(z.tuple([z.string(), toastTypeSchema]), z.void()),
    loadPlans: z.function(z.tuple([]), z.custom<Promise<void>>(() => z.promise(z.void()))),
    openAdd: z.function(z.tuple([]), z.void()),
    openEdit: z.function(z.tuple([planSchema]), z.void()),
    savePlan: z.function(z.tuple([planFormValuesSchema]), z.custom<Promise<void>>(() => z.promise(z.void()))),
    deletePlan: z.function(z.tuple([z.string()]), z.custom<Promise<void>>(() => z.promise(z.void())))
});

export const planFormSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  tier: z.string(),
  price1Month:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, 'Valid price required'),
  price3Month:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, 'Valid price required'),
  price6Month:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, 'Valid price required'),
  price12Month: z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, 'Valid price required'),
  priceCustom:  z.string().refine(val => !isNaN(Number(val)) && Number(val) >= 0, 'Valid price required'),
  features: z.string().min(2, 'Features are required')
});

