// Generated by ts-to-zod
import { z } from "zod";

export const revenuePeriodSchema = z.union([z.literal("THIS_MONTH"), z.literal("LAST_MONTH"), z.literal("THIS_QUARTER"), z.literal("THIS_YEAR")]);

export const planRevenueRecordSchema = z.object({
    id: z.string(),
    planName: z.string(),
    tier: z.string(),
    totalRevenue: z.number(),
    activeSubscriptions: z.number(),
    newSignups: z.number(),
    renewalRate: z.number()
});

export const revenueSortKeySchema = z.any();

export const revenueSortDirectionSchema = z.union([z.literal("asc"), z.literal("desc")]);

export const revenueAggregatesSchema = z.object({
    totalRevenue: z.number(),
    totalSubscriptions: z.number(),
    avgRenewalRate: z.number(),
    topPerformingPlanName: z.string()
});
