// Generated by ts-to-zod
import { z } from "zod";

export const fetchStateSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const planSchema = z.object({
    id: z.string(),
    name: z.string(),
    tier: z.string(),
    price1Month: z.number(),
    price3Month: z.number(),
    price6Month: z.number(),
    price12Month: z.number(),
    features: z.array(z.string()),
    isActive: z.boolean(),
    freezeAllowed: z.boolean().optional(),
    joiningFee: z.number().optional(),
    ptSessionsIncluded: z.number().optional(),
    taxRate: z.number().optional()
});

const toastTypeSchema = z.any();

const planFormValuesSchema = z.any();

export const plansInitialDataSchema = z.object({
    plans: z.array(planSchema)
});

export const plansContextTypeSchema = z.object({
    plans: z.array(planSchema),
    fetchState: fetchStateSchema,
    saving: z.boolean(),
    toast: z.object({
        message: z.string(),
        type: toastTypeSchema
    }).nullable(),
    search: z.string(),
    setSearch: z.function({ input: [z.string()], output: z.void() }),
    tierFilter: z.string(),
    setTierFilter: z.function({ input: [z.string()], output: z.void() }),
    currentPage: z.number(),
    setCurrentPage: z.function({ input: [z.number()], output: z.void() }),
    showModal: z.boolean(),
    setShowModal: z.function({ input: [z.boolean()], output: z.void() }),
    editId: z.string().nullable(),
    form: planFormValuesSchema,
    setForm: z.function({ input: [planFormValuesSchema], output: z.void() }),
    showToast: z.function({ input: [z.string(), toastTypeSchema], output: z.void() }),
    hideToast: z.function({ input: [], output: z.void() }),
    loadPlans: z.function({ input: [], output: z.custom<Promise<void>>(() => z.promise(z.void())) }),
    openAdd: z.function({ input: [], output: z.void() }),
    openEdit: z.function({ input: [planSchema], output: z.void() }),
    savePlan: z.function({ input: [planFormValuesSchema], output: z.custom<Promise<void>>(() => z.promise(z.void())) }),
    deletePlan: z.function({ input: [z.string()], output: z.custom<Promise<void>>(() => z.promise(z.void())) })
});
