// RESPONSIBILITY: Renders ManagerProfileMain's feature UI and orchestrates presentation through module-owned state/hooks; it does not own API transport or business rules.
'use client';
import { useState } from 'react';
import { Lock, Save, Loader2, Eye, EyeOff } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { getManagerErrorMessage } from '@/app/frontend_manager/manager_infrastructure/ManagerErrorMessage';
import { MANAGER_PROFILE_TABS } from '@/app/frontend_manager/manager_profile/manager_profile_constants/ManagerProfileTabConstants';
import { useManagerProfileForms } from '@/app/frontend_manager/manager_profile/manager_profile_hooks/useManagerProfileForms';
import type { ManagerPasswordFormValues } from '@/app/frontend_manager/manager_profile/manager_profile_types/ManagerProfileFormTypes';




/** @description Renders the ManagerProfileMain component for its owning Manager frontend boundary. @dependencies Local dependencies are owned by this feature module (4 documented module/import dependencies).. @edge-case Preserves error state. */
export default function ManagerProfileMain() {
  const t = useTranslations('MANAGER_PROFILE');

  const { activeTab, handleTabChange, user, displayInitial, profileQuery, profileMutation, passwordMutation, profileForm, passwordForm, submitProfile, submitPassword } = useManagerProfileForms();
  const [showCurrent, setShowCurrent] = useState(false);
  const [showNew, setShowNew] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);

  return <div className="max-w-3xl mx-auto space-y-6 p-6">
    <div><h1 className="text-2xl font-bold text-primary">{t("COPY_MY_PROFILE")}</h1><p className="text-secondary mt-1 text-sm">{t("COPY_MANAGE_ACCOUNT_DETAILS_PASSWORD")}</p></div>
    {(() => { if (profileQuery.isPending) { return <div className="h-28 bg-card rounded-xl motion-safe:animate-pulse border border-border motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1" aria-label={t("COPY_LOADING_PROFILE")} />; } return (() => { if (profileQuery.isError) { return <div data-testid="manager_profile-manager-profile-main-status" role="alert" className="bg-danger text-on-danger border border-border rounded-xl p-4">{getManagerErrorMessage(profileQuery.error)}</div>; } return <>
      <div className="bg-card border border-border rounded-xl p-6 flex items-center gap-5 shadow-card motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:hover:-translate-y-1">
        <div className="w-16 h-16 rounded-full bg-primary flex items-center justify-center text-2xl font-bold text-on-primary shrink-0">{displayInitial}</div>
        <div><p className="text-lg font-bold text-primary">{user?.name}</p><p className="text-sm text-secondary">{user?.email}</p><span className="mt-1.5 inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-success text-on-success text-xs font-semibold" data-testid="manager_profile-managerprofilemain-status-badge-1">{t("COPY_ACTIVE")}</span></div>
      </div>
      <div className="flex gap-1 bg-input border border-border rounded-xl p-1 w-fit">{MANAGER_PROFILE_TABS.map(({ id, label, icon: Icon }, mapIndex) => <button className={ ["focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page", (`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium ${activeTab === id ? 'bg-card text-primary shadow-card' : 'text-secondary hover:text-primary'} motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110`)].filter((value) => Boolean(value)).join(' ') } data-testid={`manager_profile-profile-managerprofilemain-button-active-${mapIndex}`} key={id} type="button" onClick={() => handleTabChange(id)} ><Icon size={18} />{label}</button>)}</div>
      {activeTab === 'personal' && <form data-testid="manager_profile-managerprofilemain-form-1" onSubmit={submitProfile} className="bg-card border border-border rounded-xl p-6 shadow-card space-y-5">
        <div><label htmlFor="manager-profile-name" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_FULL_NAME")}</label><input data-testid="manager_profile-manager-profile-main-manager-profile-name" id="manager-profile-name" {...profileForm.register('name')} className="w-full px-4 py-2.5 bg-input border border-border rounded-lg text-primary text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" aria-invalid={profileForm.formState.errors.name ? 'true' : undefined} aria-describedby={profileForm.formState.errors.name ? 'managerprofilemain-name-error' : undefined} />{profileForm.formState.errors.name && <p id="managerprofilemain-name-error" className="text-xs text-danger mt-1">{profileForm.formState.errors.name.message}</p>}</div>
        <div><label htmlFor="manager-profile-email" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_EMAIL_ADDRESS")}</label><input data-testid="manager_profile-manager-profile-main-manager-profile-email" id="manager-profile-email" type="email" value={user?.email ?? ''} readOnly className="w-full px-4 py-2.5 bg-input border border-dashed border-border rounded-lg text-secondary text-sm focus-visible:outline-none cursor-default" /></div>
        <div><label htmlFor="manager-profile-phone" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_PHONE_NUMBER")}</label><input data-testid="manager_profile-manager-profile-main-manager-profile-phone" id="manager-profile-phone" {...profileForm.register('phone')} className="w-full px-4 py-2.5 bg-input border border-border rounded-lg text-primary text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" aria-invalid={profileForm.formState.errors.phone ? 'true' : undefined} aria-describedby={profileForm.formState.errors.phone ? 'managerprofilemain-phone-error' : undefined} />{profileForm.formState.errors.phone && <p id="managerprofilemain-phone-error" className="text-xs text-danger mt-1">{profileForm.formState.errors.phone.message}</p>}</div>
        <div><label htmlFor="manager-profile-role" className="block text-sm font-medium text-secondary mb-1.5">{t("COPY_ROLE")}</label><input data-testid="manager_profile-manager-profile-main-manager-profile-role" id="manager-profile-role" value={user?.role ?? ''} readOnly className="w-full px-4 py-2.5 bg-input border border-dashed border-border rounded-lg text-secondary text-sm focus-visible:outline-none cursor-default" /></div>
        <div className="flex justify-end"><button data-testid="manager_profile-manager-profile-main-button-submit-1" type="submit" disabled={profileForm.formState.isSubmitting} className="min-w-32 flex items-center gap-2 px-5 py-2.5 bg-primary text-on-primary font-semibold rounded-lg text-sm disabled:opacity-60 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{profileForm.formState.isSubmitting ? <Loader2 size={18} strokeWidth={2} className="motion-safe:animate-spin"/> : <Save size={18} strokeWidth={2}/>}{t("COPY_SAVE_CHANGES")}</button></div>
      </form>}
      {activeTab === 'security' && <form data-testid="manager_profile-managerprofilemain-form-2" onSubmit={submitPassword} className="bg-card border border-border rounded-xl p-6 shadow-card space-y-5">
        <h2 className="text-base font-semibold text-primary">{t("COPY_CHANGE_PASSWORD")}</h2>
        {[['currentPassword',t('COPY_CURRENT_PASSWORD'),showCurrent,setShowCurrent],['newPassword',t('COPY_NEW_PASSWORD'),showNew,setShowNew],['confirmPassword',t('COPY_CONFIRM_NEW_PASSWORD'),showConfirm,setShowConfirm]].map(([field,label,show,setShow], mapIndex) => { const fieldName = field as keyof ManagerPasswordFormValues; const error = passwordForm.formState.errors[fieldName]; return <div key={field as string} className="space-y-1"><label htmlFor={`manager-profile-${field as string}`} className="block text-sm font-medium text-secondary">{label as string} *</label><div className="relative"><input data-testid={`manager_profile-profile-managerprofilemain-input-change-password-${mapIndex}`} id={`manager-profile-${field as string}`} type={show ? 'text' : 'password'} {...passwordForm.register(fieldName)} className="w-full px-4 py-2.5 pr-10 bg-input border border-border rounded-lg text-primary text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /><button className={ ["focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page", "absolute right-3 top-1/2 -translate-y-1/2 text-secondary motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"].filter((value) => Boolean(value)).join(' ') } data-testid={`manager_profile-profile-managerprofilemain-button-change-password-${mapIndex}`} type="button" onClick={() => (setShow as (value: boolean) => void)(!(show as boolean))} aria-label={(show as boolean) ? t('COPY_HIDE_PASSWORD') : t('COPY_SHOW_PASSWORD')} >{show ? <EyeOff size={18} strokeWidth={2}/> : <Eye size={18} strokeWidth={2}/>}</button></div>{error && <p className="text-xs text-danger">{String(error.message ?? '')}</p>}</div>; })}
        <div className="flex justify-end"><button data-testid="manager_profile-manager-profile-main-button-submit-2" type="submit" disabled={passwordForm.formState.isSubmitting} className="min-w-32 flex items-center gap-2 px-5 py-2.5 bg-primary text-on-primary font-semibold rounded-lg text-sm disabled:opacity-60 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{passwordForm.formState.isSubmitting ? <Loader2 size={18} strokeWidth={2} className="motion-safe:animate-spin"/> : <Lock size={18} strokeWidth={2}/>}{t("COPY_UPDATE_PASSWORD")}</button></div>
      </form>}
    </>; })(); })()}
  </div>;
}
