// RESPONSIBILITY: Creates the master PostgreSQL schema with explicit, human-readable constraint/index names.
// FLOW: TypeORM migration runner -> master DB DDL -> all Superadmin feature tables.
import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSuperadminSchema1700000000000 implements MigrationInterface {
  name = 'InitialSuperadminSchema1700000000000';

  /** Applies the master schema in a production-safe, explicit DDL sequence. */
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS affiliates (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, name varchar(500) NOT NULL, email varchar(500) NOT NULL, phone varchar(500) NOT NULL, referral_code varchar(500) NOT NULL, total_referred integer NOT NULL, commission_earned integer NOT NULL, commission_rate integer NOT NULL, pending_payout integer NOT NULL, bank_details jsonb NOT NULL, status varchar(500) NOT NULL, joined_at timestamptz NOT NULL, referral_count integer NOT NULL, conversion_rate numeric(7,3) NOT NULL, CONSTRAINT PK_affiliates PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS broadcasts (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, title varchar(500) NOT NULL, content varchar(500) NOT NULL, status varchar(500) NOT NULL, target_gym_ids jsonb NOT NULL, scheduled_date timestamptz NULL, sent_date timestamptz NULL, total_recipients integer NOT NULL, delivered_count integer NOT NULL, failed_count integer NOT NULL, audience varchar(500) NOT NULL, CONSTRAINT PK_broadcasts PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS tenants (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, name varchar(500) NOT NULL, owner_name varchar(500) NOT NULL, admin_email varchar(500) NOT NULL, phone varchar(500) NOT NULL, status varchar(500) NOT NULL, plan varchar(500) NOT NULL, member_count integer NOT NULL, monthly_revenue integer NOT NULL, database_version varchar(500) NOT NULL, city varchar(500) NOT NULL, state varchar(500) NOT NULL, country varchar(500) NOT NULL, gstin varchar(500) NOT NULL, trial_ends_at timestamptz NULL, last_login_at timestamptz NULL, last_active_at timestamptz NULL, staff_count integer NOT NULL, database_name varchar(500) NOT NULL, aadhar_number_encrypted varchar(500) NULL, subscription_history jsonb NOT NULL, usage_stats jsonb NOT NULL, CONSTRAINT PK_tenants PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS support_tickets (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, tenant_id varchar(500) NOT NULL, tenant_name varchar(500) NOT NULL, reporter_email varchar(500) NOT NULL, subject varchar(500) NOT NULL, description varchar(500) NOT NULL, status varchar(500) NOT NULL, priority varchar(500) NOT NULL, assigned_to varchar(500) NULL, attachments jsonb NOT NULL, sla_deadline timestamptz NULL, first_response_at timestamptz NULL, resolution_time integer NOT NULL, messages jsonb NOT NULL, last_updated timestamptz NOT NULL, CONSTRAINT PK_support_tickets PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS platform_settings (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, key varchar(500) NOT NULL, value varchar(500) NOT NULL, description varchar(500) NOT NULL, category varchar(500) NOT NULL, data_type varchar(500) NOT NULL, CONSTRAINT PK_platform_settings PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS tenant_messages (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, tenant_id varchar(500) NOT NULL, tenant_name varchar(500) NOT NULL, channel varchar(500) NOT NULL, subject varchar(500) NOT NULL, body varchar(500) NOT NULL, status varchar(500) NOT NULL, sent_at timestamptz NULL, scheduled_at timestamptz NULL, CONSTRAINT PK_tenant_messages PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS subscription_plans (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, name varchar(500) NOT NULL, price_monthly integer NOT NULL, price_annual integer NOT NULL, max_members integer NOT NULL, max_staff integer NOT NULL, db_limit_gb integer NOT NULL, binary_limit_gb integer NOT NULL, features jsonb NOT NULL, active_tenants integer NOT NULL, is_public boolean NOT NULL, trial_days integer NOT NULL, setup_fee integer NOT NULL, currency varchar(500) NOT NULL, is_archived boolean NOT NULL, CONSTRAINT PK_subscription_plans PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS coupons (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, code varchar(500) NOT NULL, discount_type varchar(500) NOT NULL, discount_value integer NOT NULL, max_uses integer NOT NULL, current_uses integer NOT NULL, redemptions jsonb NOT NULL DEFAULT '[]'::jsonb, status varchar(500) NOT NULL, expiry_date timestamptz NOT NULL, CONSTRAINT PK_coupons PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS saas_invoices (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, tenant_id varchar(500) NOT NULL, tenant_name varchar(500) NOT NULL, amount integer NOT NULL, currency varchar(500) NOT NULL, status varchar(500) NOT NULL, issued_at timestamptz NOT NULL, due_date timestamptz NOT NULL, paid_at timestamptz NULL, payment_method varchar(500) NOT NULL, invoice_type varchar(500) NOT NULL, plan_name varchar(500) NOT NULL, tax_id varchar(500) NOT NULL, CONSTRAINT PK_saas_invoices PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS usage_meters (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, tenant_id varchar(500) NOT NULL, tenant_name varchar(500) NOT NULL, sms_sent integer NOT NULL, sms_limit integer NOT NULL, whatsapp_messages_sent integer NOT NULL, whatsapp_limit integer NOT NULL, emails_sent integer NOT NULL, email_limit integer NOT NULL, api_calls_count integer NOT NULL, api_calls_limit integer NOT NULL, database_gb numeric(12,3) NOT NULL, media_gb numeric(12,3) NOT NULL, storage_limit_gb numeric(12,3) NOT NULL, active_members integer NOT NULL, total_members integer NOT NULL, member_limit integer NOT NULL, staff_count integer NOT NULL, staff_limit integer NOT NULL, billing_cycle_end timestamptz NOT NULL, CONSTRAINT PK_usage_meters PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS white_label_domains (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, gym_id varchar(500) NOT NULL, gym_name varchar(500) NOT NULL, domain varchar(500) NOT NULL, status varchar(500) NOT NULL, ssl_status varchar(500) NOT NULL, logo_url varchar(500) NULL, primary_color varchar(500) NULL, CONSTRAINT PK_white_label_domains PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS background_jobs (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, queue_name varchar(500) NOT NULL, job_name varchar(500) NOT NULL, status varchar(500) NOT NULL, attempts integer NOT NULL, error varchar(500) NULL, tenant_id varchar(500) NULL, CONSTRAINT PK_background_jobs PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS migration_logs (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, version varchar(500) NOT NULL, description varchar(500) NOT NULL, applied_at timestamptz NULL, status varchar(500) NOT NULL, target_tenants jsonb NOT NULL, duration_ms integer NOT NULL, error_log varchar(500) NULL, executed_at timestamptz NULL, executed_by varchar(500) NOT NULL, error_details varchar(500) NULL, CONSTRAINT PK_migration_logs PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS backup_records (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, tenant_name varchar(500) NOT NULL, database_name varchar(500) NOT NULL, size_m_b integer NOT NULL, status varchar(500) NOT NULL, timestamp timestamptz NOT NULL, CONSTRAINT PK_backup_records PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS infrastructure_nodes (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, name varchar(500) NOT NULL, region varchar(500) NOT NULL, status varchar(500) NOT NULL, cpu_percent integer NOT NULL, memory_percent integer NOT NULL, disk_percent integer NOT NULL, uptime varchar(500) NOT NULL, last_checked timestamptz NOT NULL, CONSTRAINT PK_infrastructure_nodes PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS superadmin_profiles (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, name varchar(500) NOT NULL, email varchar(500) NOT NULL, phone varchar(100) NOT NULL DEFAULT '', timezone varchar(100) NOT NULL DEFAULT 'Asia/Kolkata', language varchar(20) NOT NULL DEFAULT 'en', role varchar(500) NOT NULL, avatar_url varchar(500) NULL, last_login_at timestamptz NULL, two_factor_enabled boolean NOT NULL DEFAULT false, password_hash varchar(500) NOT NULL, CONSTRAINT PK_superadmin_profiles PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS feature_flags (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, name varchar(500) NOT NULL, description varchar(500) NOT NULL, is_global_enabled boolean NOT NULL, enabled_tenant_ids jsonb NOT NULL, notes jsonb NOT NULL, history jsonb NOT NULL, CONSTRAINT PK_feature_flags PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS integration_keys (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, tenant_id varchar(500) NOT NULL, label varchar(500) NOT NULL, status varchar(500) NOT NULL, last_used timestamptz NULL, rate_limit integer NOT NULL, secret_hash varchar(500) NOT NULL, CONSTRAINT PK_integration_keys PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS superadmin_team_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_superadmin_team_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS dashboard_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_dashboard_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS analytics_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_analytics_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS compliance_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_compliance_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS report_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_report_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS system_ops_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_system_ops_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS audit_logs (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, actor_id varchar(500) NOT NULL, actor_role varchar(500) NOT NULL, action varchar(500) NOT NULL, entity_type varchar(500) NOT NULL, entity_id varchar(500) NOT NULL, old_value jsonb NOT NULL, new_value jsonb NOT NULL, ip_address varchar(500) NOT NULL, tenant_id varchar(500) NULL, CONSTRAINT PK_audit_logs PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_tenants_admin_email ON tenants(admin_email);`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_saas_invoices_tenant_id ON saas_invoices(tenant_id);`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_usage_meters_tenant_id ON usage_meters(tenant_id);`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_support_tickets_tenant_id ON support_tickets(tenant_id);`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS UQ_superadmin_profiles_email ON superadmin_profiles(email);`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS UQ_subscription_plans_name ON subscription_plans(name);`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS UQ_coupons_code ON coupons(code);`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS UQ_white_label_domains_domain ON white_label_domains(domain);`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS UQ_integration_keys_secret_hash ON integration_keys(secret_hash);`);
    await queryRunner.query(`ALTER TABLE tenants DROP CONSTRAINT IF EXISTS CHK_tenants_member_count_non_negative; ALTER TABLE tenants ADD CONSTRAINT CHK_tenants_member_count_non_negative CHECK (member_count >= 0);`);
    await queryRunner.query(`ALTER TABLE subscription_plans DROP CONSTRAINT IF EXISTS CHK_subscription_plans_price_monthly_non_negative; ALTER TABLE subscription_plans ADD CONSTRAINT CHK_subscription_plans_price_monthly_non_negative CHECK (price_monthly >= 0);`);
    await queryRunner.query(`ALTER TABLE saas_invoices DROP CONSTRAINT IF EXISTS CHK_saas_invoices_amount_non_negative; ALTER TABLE saas_invoices ADD CONSTRAINT CHK_saas_invoices_amount_non_negative CHECK (amount >= 0);`);
    await queryRunner.query(`ALTER TABLE coupons DROP CONSTRAINT IF EXISTS CHK_coupons_discount_value_non_negative; ALTER TABLE coupons ADD CONSTRAINT CHK_coupons_discount_value_non_negative CHECK (discount_value >= 0);`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS superadmin_tenant_memberships (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, actor_id varchar(64) NOT NULL, tenant_id varchar(64) NOT NULL, role varchar(100) NOT NULL, CONSTRAINT PK_superadmin_tenant_memberships PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS UQ_superadmin_tenant_memberships_actor_tenant ON superadmin_tenant_memberships(actor_id, tenant_id);`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_superadmin_tenant_memberships_tenant_id ON superadmin_tenant_memberships(tenant_id);`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS broadcasts_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_broadcasts_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS settings_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_settings_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS features_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_features_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS global_audit_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_global_audit_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS messaging_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_messaging_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS integrations_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_integrations_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS tickets_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_tickets_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS plans_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_plans_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS invoices_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_invoices_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS backups_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_backups_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS infrastructure_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_infrastructure_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS jobs_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_jobs_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS backup_schedule_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_backup_schedule_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS gym_detail_contract_snapshots (id varchar(64) NOT NULL DEFAULT substring(md5(random()::text || clock_timestamp()::text),1,32), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at timestamptz NULL, kind varchar(500) NOT NULL, payload jsonb NOT NULL, CONSTRAINT PK_gym_detail_contract_snapshots PRIMARY KEY (id));`);
    await queryRunner.query(`ALTER TABLE usage_meters ALTER COLUMN database_gb TYPE numeric(12,3) USING database_gb::numeric`);
    await queryRunner.query(`ALTER TABLE usage_meters ALTER COLUMN media_gb TYPE numeric(12,3) USING media_gb::numeric`);
    await queryRunner.query(`ALTER TABLE usage_meters ALTER COLUMN storage_limit_gb TYPE numeric(12,3) USING storage_limit_gb::numeric`);

    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_system_ops_snapshots_kind ON system_ops_snapshots(kind)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_system_ops_snapshots_updated_at ON system_ops_snapshots(updated_at)`);

    for (const table of ['broadcasts_contract_snapshots','settings_contract_snapshots','features_contract_snapshots','global_audit_contract_snapshots','messaging_contract_snapshots','integrations_contract_snapshots','tickets_contract_snapshots','plans_contract_snapshots','invoices_contract_snapshots','backups_contract_snapshots','infrastructure_contract_snapshots','jobs_contract_snapshots','gym_detail_contract_snapshots']) {
      await queryRunner.query(`CREATE INDEX IF NOT EXISTS IDX_${table}_kind ON ${table}(kind);`);
    }
    await queryRunner.query(`ALTER TABLE superadmin_tenant_memberships ADD CONSTRAINT FK_superadmin_tenant_memberships_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;`);
  }

  /** Rolls back only objects created by this migration. */
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS backup_schedule_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS gym_detail_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS jobs_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS infrastructure_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS backups_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS invoices_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS plans_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS tickets_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS integrations_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS messaging_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS global_audit_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS features_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS settings_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS broadcasts_contract_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS superadmin_tenant_memberships');
    await queryRunner.query('DROP TABLE IF EXISTS audit_logs');
    await queryRunner.query('DROP TABLE IF EXISTS system_ops_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS report_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS compliance_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS analytics_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS dashboard_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS superadmin_team_snapshots');
    await queryRunner.query('DROP TABLE IF EXISTS integration_keys');
    await queryRunner.query('DROP TABLE IF EXISTS feature_flags');
    await queryRunner.query('DROP TABLE IF EXISTS superadmin_profiles');
    await queryRunner.query('DROP TABLE IF EXISTS infrastructure_nodes');
    await queryRunner.query('DROP TABLE IF EXISTS backup_records');
    await queryRunner.query('DROP TABLE IF EXISTS migration_logs');
    await queryRunner.query('DROP TABLE IF EXISTS background_jobs');
    await queryRunner.query('DROP TABLE IF EXISTS white_label_domains');
    await queryRunner.query('DROP TABLE IF EXISTS usage_meters');
    await queryRunner.query('DROP TABLE IF EXISTS saas_invoices');
    await queryRunner.query('DROP TABLE IF EXISTS coupons');
    await queryRunner.query('DROP TABLE IF EXISTS subscription_plans');
    await queryRunner.query('DROP TABLE IF EXISTS tenant_messages');
    await queryRunner.query('DROP TABLE IF EXISTS platform_settings');
    await queryRunner.query('DROP TABLE IF EXISTS support_tickets');
    await queryRunner.query('DROP TABLE IF EXISTS tenants');
    await queryRunner.query('DROP TABLE IF EXISTS broadcasts');
    await queryRunner.query('DROP TABLE IF EXISTS affiliates');
  }
}
