// RESPONSIBILITY: Constants, style maps, and mock data for the Churn Alerts module.
// All status-to-style mappings live here — never inline in JSX (Rule 3B).

import type { ChurnRiskLevel, ChurnActionStatus, ChurnAlert, ChurnKpiData } from '@/app/superadmin/churn-alerts/churn_types/churn_types';

export const CHURN_RISK_STYLES: Record<ChurnRiskLevel, string> = {
  CRITICAL: 'bg-danger-bg text-danger',
  HIGH: 'bg-warning-bg text-warning',
  MEDIUM: 'bg-info-bg text-info',
  LOW: 'bg-success-bg text-success',
};

export const CHURN_ACTION_STATUS_STYLES: Record<ChurnActionStatus, string> = {
  PENDING: 'bg-warning-bg text-warning',
  CONTACTED: 'bg-info-bg text-info',
  RESOLVED: 'bg-success-bg text-success',
  CHURNED: 'bg-danger-bg text-danger',
};

export const KPI_CARD_GRADIENT = 'linear-gradient(180deg, rgba(250,204,21,0.08), rgba(255,255,255,0.02))';

export const MOCK_CHURN_KPI: ChurnKpiData = {
  totalAtRisk: 14,
  criticalCount: 3,
  highCount: 5,
  estimatedMrrAtRisk: 42500,
};

export const MOCK_CHURN_ALERTS: ChurnAlert[] = [
  {
    id: 'ca-001',
    tenantId: 'ten-001',
    gymName: 'Iron Peak Fitness',
    ownerName: 'Rajesh Sharma',
    adminEmail: 'rajesh@ironpeak.in',
    phone: '9876543210',
    plan: 'PRO',
    riskLevel: 'CRITICAL',
    actionStatus: 'PENDING',
    riskScore: 92,
    lastLoginDays: 21,
    memberDrop: 34,
    paymentFailures: 2,
    renewalDaysLeft: 5,
    mrrAtRisk: 8500,
    notes: '',
    flaggedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'ca-002',
    tenantId: 'ten-002',
    gymName: 'FitZone Studio',
    ownerName: 'Priya Nair',
    adminEmail: 'priya@fitzone.in',
    phone: '9123456780',
    plan: 'STARTER',
    riskLevel: 'HIGH',
    actionStatus: 'CONTACTED',
    riskScore: 74,
    lastLoginDays: 14,
    memberDrop: 18,
    paymentFailures: 1,
    renewalDaysLeft: 12,
    mrrAtRisk: 3200,
    notes: 'Called on Jan 8 — owner mentioned cash flow issues.',
    flaggedAt: '2025-01-08T10:30:00Z',
  },
  {
    id: 'ca-003',
    tenantId: 'ten-003',
    gymName: 'Muscle Factory',
    ownerName: 'Arjun Mehta',
    adminEmail: 'arjun@musclefactory.in',
    phone: '9988776655',
    plan: 'ENTERPRISE',
    riskLevel: 'MEDIUM',
    actionStatus: 'PENDING',
    riskScore: 55,
    lastLoginDays: 7,
    memberDrop: 9,
    paymentFailures: 0,
    renewalDaysLeft: 22,
    mrrAtRisk: 15000,
    notes: '',
    flaggedAt: '2025-01-12T14:00:00Z',
  },
  {
    id: 'ca-004',
    tenantId: 'ten-004',
    gymName: 'Zen Wellness Hub',
    ownerName: 'Sneha Kapoor',
    adminEmail: 'sneha@zenwellness.in',
    phone: '9001122334',
    plan: 'BASIC',
    riskLevel: 'CRITICAL',
    actionStatus: 'PENDING',
    riskScore: 88,
    lastLoginDays: 30,
    memberDrop: 45,
    paymentFailures: 3,
    renewalDaysLeft: 2,
    mrrAtRisk: 1800,
    notes: '',
    flaggedAt: '2025-01-13T09:15:00Z',
  },
  {
    id: 'ca-005',
    tenantId: 'ten-005',
    gymName: 'PowerHouse Gym',
    ownerName: 'Vikram Singh',
    adminEmail: 'vikram@powerhouse.in',
    phone: '9876001234',
    plan: 'PRO',
    riskLevel: 'HIGH',
    actionStatus: 'RESOLVED',
    riskScore: 68,
    lastLoginDays: 10,
    memberDrop: 12,
    paymentFailures: 1,
    renewalDaysLeft: 18,
    mrrAtRisk: 7200,
    notes: 'Resolved — owner upgraded plan and re-engaged.',
    flaggedAt: '2025-01-05T11:00:00Z',
  },
];
