// RESPONSIBILITY: Centralized route constants for the GymSmart frontend.
// Used by middleware.ts to protect authenticated pages and redirect unauthenticated users.
// All page navigation in the app must use these constants — never hardcode route strings.
export const ROUTES = {
  LOGIN: '/frontend_auth/auth/login',
  ADMIN_DASHBOARD: '/frontend_admin/admin_dashboard',
  MANAGER_DASHBOARD: '/frontend_manager/manager_dashboard',
  TRAINER_DASHBOARD: '/frontend_trainer/trainer_dashboard',
  SUPERADMIN_DASHBOARD: '/frontend_superadmin/superadmin_dashboard',
  ADMIN_PREFIXES: [
    '/frontend_admin',
    '/admin',
    '/admin/members',
    '/admin/plans',
    '/admin/finance',
    '/admin/hr',
    '/admin/attendance',
    '/admin/store',
    '/admin/workout',
    '/admin/inquiries',
    '/admin/settings',
    '/admin/library',
    '/admin/sales',
    '/admin/audit',
  ],
  MANAGER_PREFIXES: [
    '/frontend_manager',
    '/manager',
    '/manager/members',
    '/manager/plans',
    '/manager/finance',
    '/manager/hr',
    '/manager/attendance',
    '/manager/store',
    '/manager/workout',
    '/manager/inquiries',
    '/manager/settings',
    '/manager/library',
    '/manager/sales',
    '/manager/audit',
  ],
  TRAINER_PREFIXES: [
    '/frontend_trainer',
    '/trainer',
    '/trainer/members',
    '/trainer/attendance',
    '/trainer/workout',
    '/trainer/library',
  ]
};
