"use client";
// RESPONSIBILITY: Renders the tax-ready P&L statement with functional sortable headers and empty state.

import { useAdminPayoutsLogic } from '@/app/admin/payouts/payouts_context/useAdminPayoutsLogic';
import AdminTableSkeleton from '@/app/admin/admin_layout/AdminShared/AdminTableSkeleton';
import AdminPayoutsPnLStatementCell from '@/app/admin/payouts/payouts_components/AdminPayoutsPnLStatement/AdminPayoutsPnLStatementCell';
import type { PnlSortKey } from '@/app/admin/payouts/payouts_types/AdminPayoutsTypes';
import AdminPayoutsPnLStatementSortIcon from '@/app/admin/payouts/payouts_components/AdminPayoutsPnLStatement/AdminPayoutsPnLStatementSortIcon';
import AdminPayoutsEmptyState from '@/app/admin/payouts/payouts_components/AdminPayoutsEmptyState/AdminPayoutsEmptyState';

const HEADERS: ReadonlyArray<{ key: PnlSortKey; label: string }> = [
  {key:'gymName',label:'Gym'},{key:'month',label:'Month'},{key:'revenue',label:'Revenue'},{key:'cogs',label:'COGS'},{key:'grossProfit',label:'Gross Profit'},{key:'staffCost',label:'Staff Cost'},{key:'rentUtilities',label:'Rent & Utilities'},{key:'marketing',label:'Marketing'},{key:'miscExpenses',label:'Misc'},{key:'ebitda',label:'EBITDA'},{key:'tax',label:'Tax'},{key:'netProfit',label:'Net Profit'}
];

export default function AdminPayoutsPnLStatement(){const logic=useAdminPayoutsLogic();if(logic.loadingPnL)return <AdminTableSkeleton rows={4} cols={HEADERS.length}/>;return <div className="bg-card rounded-xl border border-border overflow-hidden"><div className="px-5 py-3 border-b border-border"><p className="text-sm font-semibold text-primary">Profit &amp; Loss Statement</p><p className="text-xs text-secondary mt-0.5">Tax-ready breakdown per gym per month</p></div><div className="overflow-x-auto"><table data-admin-responsive-table className="w-full"><thead><tr className="bg-surface-highlight border-b border-border">{HEADERS.map(h=><th role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); event.currentTarget.click(); } }}  key={h.key} onClick={()=>logic.onPnlSort(h.key)} className="px-4 py-3 text-left text-xs font-semibold text-secondary uppercase tracking-wider whitespace-nowrap cursor-pointer select-none" aria-sort={logic.pnlSortKey===h.key?(logic.pnlSortDir==='asc'?'ascending':'descending'):'none'}><div className="flex items-center gap-1.5">{h.label}<AdminPayoutsPnLStatementSortIcon column={h.key} sortKey={logic.pnlSortKey} sortDir={logic.pnlSortDir}/></div></th>)}</tr></thead><tbody className="divide-y divide-border">{logic.pnlData.length===0?<tr><td colSpan={HEADERS.length}><AdminPayoutsEmptyState title="No P&L records found" description="No P&L records match the current filters." /></td></tr>:logic.pnlData.map(p=><tr key={`${p.gymId}-${p.month}`} className="hover:bg-surface-highlight motion-safe:transition-colors motion-safe:duration-base"> <td className="px-4 py-3 text-sm font-medium text-primary">{p.gymName}</td><td className="px-4 py-3 text-sm text-secondary">{p.month}</td><AdminPayoutsPnLStatementCell value={p.revenue}/><AdminPayoutsPnLStatementCell value={p.cogs} tone="text-danger"/><AdminPayoutsPnLStatementCell value={p.grossProfit}/><AdminPayoutsPnLStatementCell value={p.staffCost} tone="text-danger"/><AdminPayoutsPnLStatementCell value={p.rentUtilities} tone="text-danger"/><AdminPayoutsPnLStatementCell value={p.marketing} tone="text-danger"/><AdminPayoutsPnLStatementCell value={p.miscExpenses} tone="text-danger"/><AdminPayoutsPnLStatementCell value={p.ebitda} tone="text-info"/><AdminPayoutsPnLStatementCell value={p.tax} tone="text-danger"/><AdminPayoutsPnLStatementCell value={p.netProfit} tone="font-bold text-success"/></tr>)}</tbody></table></div></div>}
