// RESPONSIBILITY: Renders ManagerWorkoutModal's feature UI and orchestrates presentation through module-owned state/hooks; it does not own API transport or business rules.
'use client';
import { useRef } from 'react';
import { X, Save, Loader2 } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { Controller } from 'react-hook-form';
import { useManagerDialogFocusTrap } from '@/app/frontend_manager/manager_infrastructure/useManagerDialogFocusTrap';
import ManagerSearchableDropdown from '@/components/ui/manager_searchable_dropdown/ManagerSearchableDropdown';
import { MANAGER_WORKOUT_LEVELS, MANAGER_WORKOUT_MAX_DAYS, MANAGER_WORKOUT_MAX_EXERCISES } from '@/app/frontend_manager/manager_workout/manager_workout_constants/ManagerWorkoutFormConstants';
import { useManagerWorkoutForm } from '@/app/frontend_manager/manager_workout/manager_workout_hooks/useManagerWorkoutForm';




/** @description Renders the ManagerWorkoutModal component for its owning Manager frontend boundary. @dependencies Local dependencies are owned by this feature module (3 documented module/import dependencies).. @edge-case Preserves error state, modal lifecycle. */
export default function ManagerWorkoutModal() {
  const t = useTranslations('MANAGER_WORKOUT');

  const { form, showWkModal, editWkId, handleClose, submit } = useManagerWorkoutForm();
  const dialogRef = useRef<HTMLDivElement>(null);
  useManagerDialogFocusTrap({ dialogRef, isOpen: showWkModal, onClose: handleClose });
  const { register, control, formState: { errors, isSubmitting } } = form;
  if (!showWkModal) return null;
  return (
    <div data-testid="manager_workout-managerworkoutmodal-presentation" className="fixed inset-0 z-40 flex items-center justify-center bg-overlay-backdrop p-4"role="presentation">
      <div data-testid="manager_workout-managerworkoutmodal-dialog" ref={dialogRef} className="bg-overlay rounded-2xl shadow-dialog w-full max-w-md overflow-hidden border-2 border-warning"role="dialog" aria-modal="true" aria-labelledby="manager-workout-title">
        <div className="flex justify-between items-center p-5 border-b border-border"><h3 id="manager-workout-title" className="font-bold text-lg text-primary">{editWkId ? t('COPY_EDIT_WORKOUT_PLAN') : t('COPY_ADD_WORKOUT_PLAN')}</h3><button data-testid="manager_workout-manager-workout-modal-close-1" type="button" aria-label={t("COPY_CLOSE_WORKOUT_FORM")} onClick={handleClose} className="text-secondary hover:text-primary hover:bg-primary-subtle p-2 rounded-md motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110"><X size={18} strokeWidth={2} aria-hidden="true"/></button></div>
        <form data-testid="manager_workout-managerworkoutmodal-form-1" onSubmit={submit} className="p-5 space-y-4">
          <div><label htmlFor="manager-workout-name" className="block text-sm font-medium text-secondary mb-1">{t("COPY_PLAN_NAME")}</label><input data-testid="manager_workout-manager-workout-modal-manager-workout-name" id="manager-workout-name" type="text" {...register('name')} className={`w-full px-3 py-2 border rounded-lg focus-visible:outline-none focus-visible:ring-2 ${errors.name ? 'border-danger focus-visible:ring-danger' : 'border-border focus-visible:ring-warning'} bg-input text-primary`} aria-invalid={errors.name ? 'true' : undefined} aria-describedby={errors.name ? 'managerworkoutmodal-name-error' : undefined} />{errors.name && <p id="managerworkoutmodal-name-error" data-testid="manager_workout-manager-workout-modal-status-1" role="alert" className="text-danger text-xs mt-1">{String(errors.name.message ?? '')}</p>}</div>
          <div><label className="block text-sm font-medium text-secondary mb-1">{t("COPY_LEVEL")}</label><Controller name="level" control={control} render={({ field }) => <ManagerSearchableDropdown ariaLabel={t("COPY_LEVEL")} dataTestId="manager_workout-managerworkoutmodal-managersearchabledropdown-1" options={MANAGER_WORKOUT_LEVELS.map((option) => ({ value: option.value, label: t(option.labelKey) }))} value={field.value} onChange={field.onChange}  data-testid="manager_workout-managerworkoutmodal-searchable-dropdown-1"/>} /></div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label htmlFor="manager-workout-days" className="block text-sm font-medium text-secondary mb-1">{t("COPY_DAYS")}</label><input data-testid="manager_workout-manager-workout-modal-manager-workout-days" id="manager-workout-days" type="number" min="1" max={MANAGER_WORKOUT_MAX_DAYS} step="1" {...register('days', { valueAsNumber: true })} className="w-full px-3 py-2 border border-border rounded-lg bg-input text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" aria-invalid={errors.days ? 'true' : undefined} aria-describedby={errors.days ? 'managerworkoutmodal-days-error' : undefined} />{errors.days && <p id="managerworkoutmodal-days-error" data-testid="manager_workout-manager-workout-modal-status-2" role="alert" className="text-danger text-xs mt-1">{String(errors.days.message ?? '')}</p>}</div><div><label htmlFor="manager-workout-exercises" className="block text-sm font-medium text-secondary mb-1">{t("COPY_EXERCISES_1")}</label><input data-testid="manager_workout-manager-workout-modal-manager-workout-exercises" id="manager-workout-exercises" type="number" min="1" max={MANAGER_WORKOUT_MAX_EXERCISES} step="1" {...register('exercises', { valueAsNumber: true })} className="w-full px-3 py-2 border border-border rounded-lg bg-input text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" aria-invalid={errors.exercises ? 'true' : undefined} aria-describedby={errors.exercises ? 'managerworkoutmodal-exercises-error' : undefined} />{errors.exercises && <p id="managerworkoutmodal-exercises-error" data-testid="manager_workout-manager-workout-modal-status-3" role="alert" className="text-danger text-xs mt-1">{String(errors.exercises.message ?? '')}</p>}</div></div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label htmlFor="manager-workout-focus" className="block text-sm font-medium text-secondary mb-1">{t("COPY_FOCUS_1")}</label><input data-testid="manager_workout-manager-workout-modal-manager-workout-focus" id="manager-workout-focus" type="text" {...register('focus')} className="w-full px-3 py-2 border border-border rounded-lg bg-input text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div><div><label htmlFor="manager-workout-duration" className="block text-sm font-medium text-secondary mb-1">{t("COPY_DURATION")}</label><input data-testid="manager_workout-manager-workout-modal-manager-workout-duration" id="manager-workout-duration" type="text" {...register('duration')} className="w-full px-3 py-2 border border-border rounded-lg bg-input text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div></div>
          <div><label htmlFor="manager-workout-tags" className="block text-sm font-medium text-secondary mb-1">{t("COPY_TAGS")}</label><input data-testid="manager_workout-manager-workout-modal-manager-workout-tags" id="manager-workout-tags" type="text" placeholder={t("COPY_STRENGTH_BEGINNER")} {...register('tags')} className="w-full px-3 py-2 border border-border rounded-lg bg-input text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-page" /></div>
          <div className="flex flex-col-reverse sm:flex-row gap-3 pt-2"><button data-testid="manager_workout-manager-workout-modal-close-2" type="button" onClick={handleClose} className="flex-1 min-h-10 py-2.5 border border-border rounded-xl text-sm font-medium text-primary hover:bg-primary-subtle motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{t("COPY_CANCEL_1")}</button><button data-testid="manager_workout-manager-workout-modal-button-submit" type="submit" disabled={isSubmitting} className="min-w-32 flex-1 min-h-10 py-2.5 rounded-xl text-sm font-bold text-on-primary bg-primary flex items-center justify-center gap-2 disabled:opacity-70 motion-safe:transition-all motion-safe:duration-base ease-in-out motion-safe:active:scale-95 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none hover:brightness-110">{isSubmitting ? <Loader2 size={18} strokeWidth={2} className="motion-safe:animate-spin" aria-hidden="true"/> : <Save size={18} strokeWidth={2} aria-hidden="true"/>}<span>{(() => { if (isSubmitting) return t('COPY_SAVING'); return (() => { if (editWkId) return t('COPY_UPDATE'); return t('COPY_SAVE'); })(); })()}</span></button></div>
        </form>
      </div>
    </div>
  );
}
