// Generated by ts-to-zod
import { z } from "zod";

export const statusSchema = z.union([z.literal("idle"), z.literal("loading"), z.literal("success"), z.literal("error")]);

export const exportFormatSchema = z.union([z.literal("csv"), z.literal("excel"), z.literal("pdf")]);

export const exportDataTypeSchema = z.union([z.literal("members"), z.literal("payments"), z.literal("attendance"), z.literal("staff"), z.literal("full_report")]);

export const exportStatusSchema = z.union([z.literal("completed"), z.literal("processing"), z.literal("failed")]);

export const exportJobSchema = z.object({
    id: z.string(),
    dataType: exportDataTypeSchema,
    format: exportFormatSchema,
    gymIds: z.array(z.string()),
    gymNames: z.array(z.string()),
    dateFrom: z.string(),
    dateTo: z.string(),
    status: exportStatusSchema,
    rowCount: z.number().optional(),
    fileSizeKb: z.number().optional(),
    createdAt: z.string(),
    completedAt: z.string().optional(),
    createdBy: z.string()
});

export const exportFormValuesSchema = z.object({
    dataType: exportDataTypeSchema,
    format: exportFormatSchema,
    gymIds: z.array(z.string()),
    dateFrom: z.string(),
    dateTo: z.string()
});

export const dataExportKpiDataSchema = z.object({
    totalExports: z.number(),
    totalRowsExported: z.number(),
    lastExportDate: z.string(),
    pendingJobs: z.number()
});
