// RESPONSIBILITY: Critical mutation idempotency route policy derived from frontend Idempotency-Key usage and backend Rule 31.
// FLOW: Request method/path -> route allowlist -> Redis reservation/replay.

export const CORE_IDEMPOTENT_ROUTES: readonly RegExp[] = [
  new RegExp('^manager/notifications/:id$', 'i'),
  new RegExp('^manager/inquiries/:id$', 'i'),
  new RegExp('^manager/expenses/:id$', 'i'),
  new RegExp('^manager/finance/payments$', 'i'),
  new RegExp('^manager/hr/staff/:id$', 'i'),
  new RegExp('^manager/hr/payrolls/generate$', 'i'),
  new RegExp('^manager/hr/payrolls$', 'i'),
  new RegExp('^manager/hr/payrolls/:id$', 'i'),
  new RegExp('^manager/hr/ledger/advance$', 'i'),
  new RegExp('^manager/hr/ledger/paydue$', 'i'),
  new RegExp('^manager/plans/:id$', 'i'),
  new RegExp('^manager/plans/membership-activate$', 'i'),
  new RegExp('^manager/plans/membership-renew$', 'i'),
  new RegExp('^manager/plans/membership-freeze$', 'i'),
  new RegExp('^manager/members/:id$', 'i'),
  new RegExp('^manager/members/:id/renew$', 'i'),
  new RegExp('^manager/members/:memberId/payments$', 'i'),
  new RegExp('^manager/library/exercises/:id$', 'i'),
  new RegExp('^manager/library/diet-plans/:id$', 'i'),
  new RegExp('^manager/schedule/shifts/:id$', 'i'),
  new RegExp('^manager/store/products/:id$', 'i'),
  new RegExp('^manager/store/orders$', 'i'),
  new RegExp('^manager/workouts/:id$', 'i'),
  new RegExp('^manager/workouts/exercises/:id$', 'i'),
  new RegExp('^manager/referrals/:referralId/claim$', 'i'),
];
